<?php
require_once __DIR__.'/includes/auth.php';
require_once __DIR__.'/includes/roles.php';
require_once __DIR__.'/includes/permissions.php';
require_once __DIR__.'/includes/icons.php';
auth_require_admin(); permissions_require_menu('admin_usuarios'); permissions_ensure_tables();
$cfg=require __DIR__.'/config.php'; $APP_USER=auth_user(); $APP_ROLE='Administrador'; $ACTIVE='admin_usuarios';
$msg='';$msgType='ok';
if($_SERVER['REQUEST_METHOD']==='POST'){
  $a=$_POST['accion']??''; $u=trim($_POST['usuario']??'');
  if($a==='guardar'){
    $isNew=empty($_POST['existente']);
    if($isNew){$r=usuario_crear($u,$_POST['pass']??'',($_POST['perfil']??'operador')==='admin'?'admin':'operador');}
    else{$r=usuario_actualizar($u,$_POST['pass']??'',($_POST['perfil']??'operador')==='admin'?'admin':'operador');}
    if(!empty($r['ok'])){
      $p=['active'=>isset($_POST['active']),'profile'=>$_POST['perfil']??'operador','comment_view'=>isset($_POST['comment_view']),'comment_create'=>isset($_POST['comment_create']),'comment_edit_own'=>isset($_POST['comment_edit_own']),'comment_edit_all'=>isset($_POST['comment_edit_all']),'comment_disable'=>isset($_POST['comment_disable']),'menus'=>$_POST['menus']??[],'session_timeout_min'=>(int)($_POST['session_timeout_min']??60)];
      permissions_save_user($u,$p,$APP_USER); audit_log($isNew?'USUARIO_CREADO':'USUARIO_ACTUALIZADO','usuarios',json_encode(['usuario'=>$u,'perfil'=>$p['profile'],'menus'=>$p['menus']],JSON_UNESCAPED_UNICODE));
      $msg=$isNew?'Usuario creado correctamente.':'Usuario y permisos actualizados.';
    }else{$msg=$r['error']??'No se pudo guardar.';$msgType='err';}
  }elseif($a==='borrar'){
    if($u===$APP_USER){$msg='No podés eliminar tu propio usuario.';$msgType='err';}
    else{$r=usuario_borrar($u);$msg=!empty($r['ok'])?'Usuario eliminado.':($r['error']??'Error');$msgType=!empty($r['ok'])?'ok':'err';}
  }
}
$usuarios=usuarios_listar();$profiles=permissions_profiles();$menus=permissions_menu_catalog();
/* Resguardo v1.1: debe aparecer en Pantallas habilitadas incluso si el
   servidor conserva temporalmente en OPcache una versión anterior del catálogo. */
if(!isset($menus['micros_contables'])){
    $menusActualizados=[];
    foreach($menus as $clave=>$etiqueta){
        $menusActualizados[$clave]=$etiqueta;
        if($clave==='novedades_semanales_panel')$menusActualizados['micros_contables']='Novedades semanales · Micros contables';
    }
    if(!isset($menusActualizados['micros_contables']))$menusActualizados['micros_contables']='Novedades semanales · Micros contables';
    $menus=$menusActualizados;
}
/* Resguardo v1.5: Cierre diario debe aparecer junto con Micros contables. */
if(!isset($menus['micros_contables_cierre'])){
    $menusActualizados=[];
    foreach($menus as $clave=>$etiqueta){
        $menusActualizados[$clave]=$etiqueta;
        if($clave==='micros_contables')$menusActualizados['micros_contables_cierre']='Novedades semanales · Cierre diario';
    }
    if(!isset($menusActualizados['micros_contables_cierre']))$menusActualizados['micros_contables_cierre']='Novedades semanales · Cierre diario';
    $menus=$menusActualizados;
}
foreach($usuarios as &$usr){$usr['ACCESS']=permissions_get_user($usr['USUARIO']);}unset($usr);
$userAccessMap=[]; foreach($usuarios as $usr){$userAccessMap[(string)$usr['USUARIO']]=$usr['ACCESS'];}
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Usuarios y permisos</title><link rel="stylesheet" href="assets/css/app.css?v=20260714-perms"><style>
.admin-layout{display:grid;grid-template-columns:minmax(620px,1fr) 520px;gap:20px;align-items:start}.user-card{background:#fff;border:1px solid var(--line-mid);border-top:3px solid var(--petrol);border-radius:14px;padding:20px;position:sticky;top:15px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.ff{margin-bottom:12px}.ff label{display:block;font-size:12px;font-weight:700;color:var(--text-soft);margin-bottom:5px}.ff input,.ff select{width:100%;padding:10px;border:1px solid var(--line-mid);border-radius:9px;background:#f8fbfc}.perm-section{margin-top:16px;padding-top:14px;border-top:1px solid var(--line)}.perm-section h4{font-family:var(--font-head);font-size:16px;margin:0 0 10px}.checks{display:grid;grid-template-columns:1fr 1fr;gap:8px}.check{display:flex;gap:8px;align-items:flex-start;padding:9px;border:1px solid var(--line);border-radius:9px;background:#fafcfd;font-size:12px}.check input{margin-top:2px;accent-color:var(--petrol)}.menu-checks{max-height:260px;overflow:auto;grid-template-columns:1fr 1fr}.actions{display:flex;gap:8px;margin-top:16px}.btn-main{flex:1;padding:11px;border:0;border-radius:9px;background:var(--petrol);color:#fff;font-weight:700;cursor:pointer}.btn-alt{padding:11px;border:1px solid var(--line-mid);border-radius:9px;background:#fff;cursor:pointer}.status-active{color:var(--green-tx);background:var(--green-soft)}.status-off{color:var(--red-tx);background:var(--red-soft)}.pill{padding:4px 8px;border-radius:999px;font-size:11px}.msg{padding:12px 14px;border-radius:10px;margin-bottom:14px}.msg.ok{background:var(--green-soft);color:var(--green-tx)}.msg.err{background:var(--red-soft);color:var(--red-tx)}.profile-tools{display:flex;gap:8px;align-items:end}.profile-tools .ff{flex:1}.small{font-size:11px;color:var(--text-mut)}.user-actions{display:flex;align-items:center;gap:7px;white-space:nowrap}.user-action-btn{display:inline-flex;align-items:center;justify-content:center;gap:6px;min-height:34px;padding:0 11px;border:1px solid var(--line-mid);border-radius:8px;background:#fff;color:var(--petrol);font-size:12px;font-weight:700;cursor:pointer}.user-action-btn:hover{border-color:var(--petrol);background:var(--petrol-soft)}.user-action-btn svg{width:15px;height:15px}.user-action-btn.danger{color:var(--red-tx)}.user-action-btn.danger:hover{border-color:var(--red);background:var(--red-soft)}.grid tr.is-editing td{background:var(--petrol-soft)}@media(max-width:1200px){.admin-layout{grid-template-columns:1fr}.user-card{position:static}}
</style></head><body><div class="app"><?php include __DIR__.'/includes/sidebar.php';?><main class="main"><?php include __DIR__.'/includes/topbar.php';?><div class="page__head"><div><h1 class="page__title">Administración de usuarios</h1><div class="page__sub">Perfiles, comentarios, menú y seguridad</div></div><div class="page__live"><span class="dot"></span>Área admin</div></div>
<?php if($msg):?><div class="msg <?=$msgType?>"><?=h($msg)?></div><?php endif;?>
<div class="admin-layout"><div class="tablewrap"><div class="tablescroll"><table class="grid"><thead><tr><th>Usuario</th><th>Perfil</th><th>Estado</th><th>Comentarios</th><th>Menú</th><th>Acciones</th></tr></thead><tbody><?php foreach($usuarios as $u):$a=$u['ACCESS'];?><tr><td><b><?=h($u['USUARIO'])?></b></td><td><?=h($profiles[$a['profile']]['label']??ucfirst($a['profile']))?></td><td><span class="pill <?=$a['active']?'status-active':'status-off'?>"><?=$a['active']?'Activo':'Inactivo'?></span></td><td><?=($a['comment_view']?'Ver ':'').($a['comment_create']?'· Crear ':'').($a['comment_edit_all']?'· Administrar':'')?></td><td><?=count($a['menus'])?> pantallas</td><td><div class="user-actions"><button class="user-action-btn" type="button" onclick='editUserByName(<?=json_encode((string)$u['USUARIO'],JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT)?>,this)'><?=icon('check')?> <span>Editar</span></button><form method="post" style="display:inline" onsubmit="return confirm('¿Eliminar el usuario <?=h($u['USUARIO'])?>?')"><input type="hidden" name="accion" value="borrar"><input type="hidden" name="usuario" value="<?=h($u['USUARIO'])?>"><button class="user-action-btn danger" type="submit"><?=icon('logout')?> <span>Eliminar</span></button></form></div></td></tr><?php endforeach;?></tbody></table></div></div>
<section class="user-card"><h3 id="formTitle">Nuevo usuario</h3><p class="small">Los perfiles completan permisos automáticamente y luego pueden ajustarse.</p><form method="post" id="userForm"><input type="hidden" name="accion" value="guardar"><input type="hidden" name="existente" id="existente" value=""><div class="form-grid"><div class="ff"><label>Usuario</label><input required name="usuario" id="usuario"></div><div class="ff"><label>Contraseña</label><input type="password" name="pass" id="pass"><span class="small" id="passHint"></span></div><div class="ff"><label>Perfil</label><select name="perfil" id="perfil" onchange="applyProfile(this.value)"><?php foreach($profiles as $k=>$p):?><option value="<?=h($k)?>"><?=h($p['label'])?></option><?php endforeach;?></select></div><div class="ff"><label>Sesión por inactividad</label><select name="session_timeout_min" id="timeout"><option value="15">15 minutos</option><option value="30">30 minutos</option><option value="60" selected>60 minutos</option><option value="120">2 horas</option><option value="480">8 horas</option></select></div></div><label class="check"><input type="checkbox" name="active" id="active" checked><span><b>Usuario activo</b><br><span class="small">Puede iniciar sesión.</span></span></label>
<div class="perm-section"><h4>Permisos de comentarios</h4><div class="checks"><?php foreach(['comment_view'=>'Ver comentarios','comment_create'=>'Crear comentarios','comment_edit_own'=>'Editar comentarios propios','comment_edit_all'=>'Editar comentarios de otros','comment_disable'=>'Desactivar comentarios'] as $k=>$l):?><label class="check"><input type="checkbox" name="<?=$k?>" id="<?=$k?>"><span><?=$l?></span></label><?php endforeach;?></div></div>
<div class="perm-section"><h4>Pantallas habilitadas</h4><div class="checks menu-checks"><?php foreach($menus as $k=>$l):?><label class="check"><input type="checkbox" name="menus[]" value="<?=h($k)?>" data-menu="<?=h($k)?>"><span><?=h($l)?></span></label><?php endforeach;?></div><div class="actions"><button type="button" class="btn-alt" onclick="toggleMenus(true)">Marcar todas</button><button type="button" class="btn-alt" onclick="toggleMenus(false)">Desmarcar</button></div></div>
<div class="actions"><button class="btn-main">Guardar usuario y permisos</button><button type="button" class="btn-alt" onclick="resetForm()">Cancelar</button></div></form></section></div></main></div>
<script>const PROFILES=<?=json_encode($profiles,JSON_UNESCAPED_UNICODE)?>;const USER_ACCESS=<?=json_encode($userAccessMap,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;function setCheck(id,v){document.getElementById(id).checked=!!v}function applyProfile(k){let p=PROFILES[k]||PROFILES.operador;['comment_view','comment_create','comment_edit_own','comment_edit_all','comment_disable'].forEach((id,i)=>setCheck(id,p.comments[i]));document.querySelectorAll('[data-menu]').forEach(x=>x.checked=p.menus.includes(x.value));}function editUserByName(u,button){const a=USER_ACCESS[u];if(!a){alert('No se pudieron cargar los permisos del usuario.');return;}document.querySelectorAll('.grid tbody tr').forEach(tr=>tr.classList.remove('is-editing'));const row=button&&button.closest('tr');if(row)row.classList.add('is-editing');editUser(u,a);}function editUser(u,a){document.getElementById('formTitle').textContent='Editar '+u;document.getElementById('existente').value='1';document.getElementById('usuario').value=u;document.getElementById('usuario').readOnly=true;document.getElementById('pass').value='';document.getElementById('passHint').textContent='Dejar vacío para conservarla';document.getElementById('perfil').value=a.profile;document.getElementById('timeout').value=String(a.session_timeout_min||60);setCheck('active',a.active);['comment_view','comment_create','comment_edit_own','comment_edit_all','comment_disable'].forEach(id=>setCheck(id,a[id]));document.querySelectorAll('[data-menu]').forEach(x=>x.checked=(a.menus||[]).includes(x.value));document.querySelector('.user-card').scrollIntoView({behavior:'smooth',block:'start'})}function resetForm(){document.querySelectorAll('.grid tbody tr').forEach(tr=>tr.classList.remove('is-editing'));document.getElementById('userForm').reset();document.getElementById('formTitle').textContent='Nuevo usuario';document.getElementById('existente').value='';document.getElementById('usuario').readOnly=false;document.getElementById('passHint').textContent='';document.getElementById('active').checked=true;applyProfile('operador')}function toggleMenus(v){document.querySelectorAll('[data-menu]').forEach(x=>x.checked=v)}applyProfile('operador');</script><script src="assets/js/app.js"></script></body></html>
