<?php
require_once __DIR__.'/includes/auth.php';
require_once __DIR__.'/includes/icons.php';
require_once __DIR__.'/includes/permissions.php';
require_once __DIR__.'/includes/ai_analysis.php';
auth_require(); permissions_require_menu('analisis_ia'); ai_analysis_ensure_tables();
$cfg=require __DIR__.'/config.php';date_default_timezone_set($cfg['app']['tz']??'America/Argentina/Buenos_Aires');
$APP_USER=auth_user();$APP_ROLE=auth_es_admin()?'Administrador':'Operador';$ACTIVE='analisis_ia';
$db=clear_db();$current=ai_analysis_collect(7);$rows=$db->all("SELECT TOP 20 * FROM dbo.CLEAR_AI_DIAGNOSTICS ORDER BY FECHA_GENERACION DESC");$latest=$rows[0]??null;$settings=ai_analysis_settings();
function ai_h($v){return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function ai_n($v){return number_format((int)$v,0,',','.');}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Análisis IA · CLEAR</title><link rel="stylesheet" href="assets/css/app.css?v=20260716-ai1"><style>
.aiGrid{display:grid;grid-template-columns:1fr;gap:18px}.aiPanel{background:#fff;border:1px solid var(--line-mid);border-top:3px solid var(--petrol);border-radius:14px;padding:18px}.aiPanel h2{font-family:var(--font-head);font-size:21px;margin:0 0 12px}.aiKpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}.aiText{white-space:pre-wrap;line-height:1.55;color:var(--text);font-size:14px}.aiMeta{display:flex;gap:12px;flex-wrap:wrap;color:var(--text-mut);font-size:12px;margin-bottom:12px}.aiHistory{display:grid;gap:9px}.aiHistoryItem{border:1px solid var(--line);border-radius:10px;padding:10px}.aiForm{display:grid;gap:10px}.aiForm label{display:grid;gap:5px;font-size:12px;font-weight:700;color:var(--text-soft)}.aiForm input,.aiForm select{width:100%;padding:10px;border:1px solid var(--line-mid);border-radius:9px;font:inherit}.aiActions{display:flex;gap:8px;flex-wrap:wrap}.aiNote{background:#eef8fb;border:1px solid #cde2e8;border-radius:10px;padding:12px;font-size:12px;color:var(--text-soft)}@media(max-width:1050px){.aiGrid{grid-template-columns:1fr}.aiKpis{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.aiKpis{grid-template-columns:1fr}}
</style></head><body><div class="app"><?php include __DIR__.'/includes/sidebar.php';?><main class="main"><?php include __DIR__.'/includes/topbar.php';?><div class="page__head"><div><h1 class="page__title">Análisis IA</h1><div class="page__sub">Diagnóstico diario de alarmas basado en la última semana</div></div><div class="page__live"><span class="dot"></span><?= $settings['enabled']?'Automático activo':'Configuración pendiente' ?></div></div>
<div id="aiMsg"></div><section class="aiKpis"><article class="stat acc-blue"><div class="stat__label">Alarmas 7 días</div><div class="stat__value is-blue"><?=ai_n($current['total'])?></div><div class="stat__detail">Registros analizados.</div></article><article class="stat acc-red"><div class="stat__label">Prioridad alta</div><div class="stat__value is-red"><?=ai_n($current['alta'])?></div><div class="stat__detail">Eventos a priorizar.</div></article><article class="stat acc-green"><div class="stat__label">Tags únicos</div><div class="stat__value is-green"><?=ai_n($current['tags_unicos'])?></div><div class="stat__detail">Diversidad de señales.</div></article><article class="stat acc-amber"><div class="stat__label">Pozos únicos</div><div class="stat__value is-amber"><?=ai_n($current['pozos_unicos'])?></div><div class="stat__detail">Con actividad registrada.</div></article></section>
<div class="aiGrid"><section class="aiPanel"><h2>Último diagnóstico</h2><?php if($latest):?><div class="aiMeta"><span>Generado: <b><?=ai_h($latest['FECHA_GENERACION'])?></b></span><span>Modelo: <b><?=ai_h($latest['MODELO'])?></b></span><span>Estado: <b><?=ai_h($latest['ESTADO'])?></b></span></div><?php if(($latest['ESTADO']??'')==='OK'):?><div class="aiText"><?=ai_h($latest['RESUMEN'])?></div><?php else:?><div class="status error" style="display:block"><?=ai_h($latest['ERROR'])?></div><?php endif;?><?php else:?><div class="empty"><p>Todavía no se generó ningún diagnóstico.</p></div><?php endif;?><?php if(auth_es_admin()):?><div style="margin-top:16px"><a class="btn" href="config_ia.php">Administrar configuración de IA</a></div><?php endif;?></section></div>
<section class="aiPanel" style="margin-top:18px"><h2>Historial de diagnósticos</h2><div class="aiHistory"><?php foreach($rows as $r):?><div class="aiHistoryItem"><b><?=ai_h($r['FECHA_GENERACION'])?> · <?=ai_h($r['ESTADO'])?></b><div class="muted"><?=ai_h($r['MODELO'])?> · <?=ai_h($r['PERIODO_DESDE'])?> a <?=ai_h($r['PERIODO_HASTA'])?></div><?php if(($r['ESTADO']??'')==='ERROR'):?><div style="color:#b42318"><?=ai_h($r['ERROR'])?></div><?php endif;?></div><?php endforeach;?></div></section></main></div></body></html>