<?php
require_once __DIR__.'/includes/db.php';require_once __DIR__.'/includes/auth.php';require_once __DIR__.'/includes/permissions.php';require_once __DIR__.'/includes/icons.php';require_once __DIR__.'/includes/novedades_semanales_common.php';require_once __DIR__.'/includes/reporting.php';require_once __DIR__.'/includes/comments_repository.php';
auth_require();if(!permissions_can('comments.view')){http_response_code(403);header('Location: index.php?denied=1');exit;}
$cfg=require __DIR__.'/config.php';date_default_timezone_set($cfg['app']['tz']??'UTC');$APP_USER=auth_user();$APP_ROLE=auth_es_admin()?'Administrador':'Operador';$ACTIVE='comentarios';
$db=clear_db();$ready=$db->ok();$reportReady=$ready&&ns_report_ready($db)&&permissions_can_menu('novedades_semanales_reporte');$sources=clear_comments_sources();$source=trim((string)($_GET['origen']??''));if(!isset($sources[$source]))$source='';$q=ns_clean($_GET['q']??'',200);$from=ns_parse_date($_GET['desde']??'');$to=ns_parse_date($_GET['hasta']??'');
$result=$ready?clear_comments_search($db,['source'=>$source,'q'=>$q,'from'=>$from?$from->format('Y-m-d'):'','to'=>$to?$to->format('Y-m-d'):''],(int)($_GET['pagina']??1),100):['rows'=>[],'total'=>0,'page'=>1,'pages'=>1];
function cc_date($value,$dateOnly=false){$value=trim((string)$value);if($value==='')return '—';try{$d=new DateTimeImmutable($value);return $d->format($dateOnly?'d/m/Y':'d/m/Y H:i');}catch(Exception $e){return $value;}}
function cc_query($page){$query=$_GET;$query['pagina']=$page;return http_build_query($query);}
function cc_installation_type($origin,$subject,$context){$value=strtoupper(trim((string)$subject).' '.trim((string)$context));if(strpos($value,'POZO:')!==false||$origin==='pozos')return 'Pozo';if(strpos($value,'BATERIA:')!==false||strpos($value,'BATERÍA:')!==false||strpos($value,'INSTALACION:')!==false||strpos($value,'INSTALACIÓN:')!==false)return 'Batería';if($origin==='instalaciones')return 'Instalación';return '—';}
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Comentarios · CLEAR</title><link rel="stylesheet" href="assets/css/app.css?v=20260915-comments-1"><link rel="stylesheet" href="assets/css/novedades_semanales.css?v=20260915-comments-1"><link rel="stylesheet" href="assets/css/comentarios.css?v=20260915-comments-3"><link rel="stylesheet" href="assets/css/comentarios_fix.css?v=20260915-comments-3"></head><body><div class="app"><?php include __DIR__.'/includes/sidebar.php'; ?><main class="main"><?php include __DIR__.'/includes/topbar.php'; ?>
<div class="page__head nsHead"><div><h1 class="page__title">Comentarios</h1><div class="page__sub">Todos los comentarios operativos reunidos en una sola pantalla.</div></div><div class="page__live"><span class="dot"></span><?php echo ns_num($result['total']); ?> comentarios</div></div>
<?php if(!$ready): ?><div class="nsNotice is-error">No se pudo conectar con la base de datos.</div><?php else: ?>
<form class="nsToolbar commentsFilters" method="get"><label class="nsControl nsControl--wide"><span>Buscar</span><input type="search" name="q" value="<?php echo h($q); ?>" placeholder="TAG, pozo, instalación, usuario o texto"></label><label class="nsControl"><span>Origen</span><select name="origen"><option value="">Todos</option><?php foreach($sources as $key=>$label): ?><option value="<?php echo h($key); ?>" <?php echo $source===$key?'selected':''; ?>><?php echo h($label); ?></option><?php endforeach; ?></select></label><label class="nsControl"><span>Desde</span><input type="date" name="desde" value="<?php echo $from?h($from->format('Y-m-d')):''; ?>"></label><label class="nsControl"><span>Hasta</span><input type="date" name="hasta" value="<?php echo $to?h($to->format('Y-m-d')):''; ?>"></label><button class="nsButton" type="submit">Aplicar</button><a class="nsButton is-secondary" href="comentarios.php">Limpiar</a><div class="commentsColumns"><button class="nsButton is-secondary" type="button" id="commentsColumnsButton" aria-expanded="false">Columnas ▾</button><div class="commentsColumnsMenu" id="commentsColumnsMenu" hidden></div></div><?php if($reportReady): ?><button class="nsButton is-secondary" type="button" data-ns-report-open>Ver reporte <span class="nsReportCount" data-ns-report-count hidden>0</span></button><?php endif; ?></form>
<section class="nsTableCard"><div class="nsTableHead"><div><h2>Registro consolidado</h2><p>Doble clic sobre una fila para ver todos los datos. Arrastrá el borde derecho de cada encabezado para cambiar su ancho.</p></div><div class="nsTableMeta">Página <?php echo (int)$result['page']; ?> de <?php echo (int)$result['pages']; ?></div></div><div class="tablescroll"><table class="grid nsTable commentsTable" id="commentsTable"><thead><tr><?php if($reportReady): ?><th data-column="report" data-label="Reporte">REPORTE</th><?php endif; ?><th data-column="updated" data-label="Actualizado">ACTUALIZADO</th><th data-column="origin" data-label="Origen">ORIGEN</th><th data-column="installation_type" data-label="Tipo de instalación">TIPO DE INSTALACIÓN</th><th data-column="subject" data-label="Asunto">ASUNTO</th><th data-column="context" data-label="Contexto">CONTEXTO</th><th data-column="comment" data-label="Comentario">COMENTARIO</th><th data-column="user" data-label="Usuario">USUARIO</th><th data-column="period" data-label="Período">PERÍODO</th></tr></thead><tbody>
<?php if(!$result['rows']): ?><tr><td colspan="<?php echo $reportReady?9:8; ?>" class="nsEmpty">No hay comentarios para los filtros seleccionados.</td></tr><?php else:foreach($result['rows'] as $row):$origin=(string)ns_value($row,'ORIGEN');$label=$sources[$origin]??$origin;$installationType=cc_installation_type($origin,ns_value($row,'ASUNTO'),ns_value($row,'CONTEXTO'));$columns=['Actualizado'=>cc_date(ns_value($row,'FECHA_ACTUALIZACION')),'Origen'=>$label,'Tipo de instalación'=>$installationType,'Asunto'=>ns_value($row,'ASUNTO'),'Contexto'=>ns_value($row,'CONTEXTO'),'Comentario'=>ns_value($row,'COMENTARIO'),'Usuario'=>ns_value($row,'USUARIO'),'Período'=>cc_date(ns_value($row,'FECHA_DESDE'),true).' — '.cc_date(ns_value($row,'FECHA_HASTA'),true)];$key=ns_report_key('comentario',[$origin,ns_value($row,'ID')]);$details=['ID'=>ns_value($row,'ID'),'Actualizado'=>$columns['Actualizado'],'Fecha de carga'=>cc_date(ns_value($row,'FECHA_CARGA')),'Origen'=>$label,'Tipo de instalación'=>$installationType,'Asunto'=>$columns['Asunto'],'Contexto'=>$columns['Contexto'],'Comentario'=>$columns['Comentario'],'Usuario'=>$columns['Usuario'],'Período'=>$columns['Período']]; ?>
<tr class="commentsRow" tabindex="0" data-comment-details="<?php echo h(json_encode($details,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)); ?>"><?php if($reportReady): ?><td data-column="report" class="nsCheckCell"><?php echo ns_report_pick($key,'row','Comentario · '.ns_value($row,'ASUNTO'),ns_report_row_payload($columns),'Incluir'); ?></td><?php endif; ?><td data-column="updated" class="commentsDate"><?php echo h($columns['Actualizado']); ?></td><td data-column="origin"><span class="commentsSource commentsSource--<?php echo h($origin); ?>"><?php echo h($label); ?></span></td><td data-column="installation_type"><span class="commentsType"><?php echo h($installationType); ?></span></td><td data-column="subject"><b><?php echo h(ns_value($row,'ASUNTO')); ?></b></td><td data-column="context"><?php echo h(ns_value($row,'CONTEXTO')); ?></td><td data-column="comment" class="commentsText"><?php echo nl2br(h(ns_value($row,'COMENTARIO'))); ?></td><td data-column="user"><?php echo h(ns_value($row,'USUARIO')); ?></td><td data-column="period"><?php echo h($columns['Período']); ?></td></tr>
<?php endforeach;endif; ?></tbody></table></div></section>
<?php if($result['pages']>1): ?><nav class="commentsPager" aria-label="Paginación"><?php if($result['page']>1): ?><a class="nsButton is-secondary" href="?<?php echo h(cc_query($result['page']-1)); ?>">Anterior</a><?php endif; ?><span><?php echo ns_num($result['total']); ?> resultados</span><?php if($result['page']<$result['pages']): ?><a class="nsButton is-secondary" href="?<?php echo h(cc_query($result['page']+1)); ?>">Siguiente</a><?php endif; ?></nav><?php endif; ?>
<?php endif; ?></main></div><div class="commentsModalBackdrop" id="commentsModalBackdrop" hidden></div><section class="commentsModal" id="commentsModal" role="dialog" aria-modal="true" aria-labelledby="commentsModalTitle" hidden><header><div><span>Detalle completo</span><h2 id="commentsModalTitle">Comentario</h2></div><button type="button" id="commentsModalClose" aria-label="Cerrar">×</button></header><div class="commentsModalBody" id="commentsModalBody"></div><footer><button class="nsButton" type="button" id="commentsModalAccept">Cerrar</button></footer></section><script>window.CLEAR_WEEKLY_NEWS={};</script><script src="assets/js/app.js?v=20260915-comments-2"></script><script src="assets/js/comentarios.js?v=20260915-comments-3"></script><script src="assets/js/comentarios_sort.js?v=20260915-comments-3"></script><?php if($reportReady): ?><script src="assets/js/novedades_semanales.js?v=20260915-comments-2"></script><?php endif; ?></body></html>
