<?php
require_once __DIR__.'/includes/db.php';require_once __DIR__.'/includes/dashboard_data.php';require_once __DIR__.'/includes/reporting.php';
$id=(int)($_GET['id']??0);$token=$_GET['token']??'';if(!$id||!hash_equals(report_generate_token($id),$token)){http_response_code(403);exit('Acceso denegado');}
$db=clear_db();$r=$db->all("SELECT * FROM dbo.CLEAR_REPORT_SCHEDULES WHERE ID=?",[$id]);if(!$r){http_response_code(404);exit('Reporte no encontrado');}$r=$r[0];$stats=dashboard_stats();$mods=dashboard_module_metrics();$visual=dashboard_visual_metrics();date_default_timezone_set($r['ZONA_HORARIA']?:'America/Argentina/Buenos_Aires');
function pct($v,$max){return $max>0?max(2,round($v/$max*100)):0;}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><title><?=htmlspecialchars($r['NOMBRE'])?></title><style>
@page{size:A4 landscape;margin:10mm}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#183746;background:#fff}.head{display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #1a596b;padding-bottom:10px}.brand{font-weight:800;font-size:24px}.sub{color:#718697;font-size:12px}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:14px 0}.card,.panel{border:1px solid #d8e2e7;border-radius:10px;padding:12px;background:#fff}.card b{font-size:24px;display:block;margin-top:6px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.panel h2{font-size:15px;margin:0 0 10px;color:#1a596b}.barrow{display:grid;grid-template-columns:180px 1fr 60px;gap:8px;align-items:center;margin:6px 0;font-size:11px}.bar{height:9px;background:#e9f0f3;border-radius:6px;overflow:hidden}.bar i{display:block;height:100%;background:#1a596b}.red i{background:#e94035}.small{font-size:10px;color:#718697}.footer{margin-top:12px;border-top:1px solid #d8e2e7;padding-top:8px;font-size:9px;color:#718697}table{width:100%;border-collapse:collapse;font-size:10px}th,td{padding:6px;border-bottom:1px solid #e5ecef;text-align:left}th{background:#1a596b;color:#fff}
</style></head><body><div class="head"><div><div class="brand">CLEAR PETROLEUM · Reporte operativo</div><div class="sub"><?=htmlspecialchars($r['NOMBRE'])?> · Generado <?=date('d/m/Y H:i:s')?></div></div><div class="sub">Plataforma inteligente de monitoreo de alarmas</div></div>
<div class="cards"><div class="card"><span>Alarmas 24h</span><b><?=fmt_num($stats['total24h']??0)?></b></div><div class="card"><span>Críticas</span><b style="color:#e94035"><?=fmt_num($stats['criticas']??0)?></b></div><div class="card"><span>Activas</span><b><?=fmt_num($stats['activas']??0)?></b></div><div class="card"><span>Reconocidas</span><b style="color:#0c8a63"><?=fmt_num($stats['reconocidas']??0)?></b></div><div class="card"><span>Suprimidas</span><b><?=fmt_num($stats['suprimidas']??0)?></b></div></div>
<div class="grid"><section class="panel"><h2>Top de alarmas</h2><?php $mx=max(array_column($mods['top_alarmas']?:[['value'=>1]],'value'));foreach($mods['top_alarmas'] as $x):?><div class="barrow"><span><?=htmlspecialchars($x['label'])?></span><div class="bar"><i style="width:<?=pct($x['value'],$mx)?>%"></i></div><b><?=fmt_num($x['value'])?></b></div><?php endforeach;?></section>
<section class="panel"><h2>Alarmas por instalación</h2><?php $mx=max(array_column($visual['installations']?:[['total'=>1]],'total'));foreach($visual['installations'] as $x):?><div class="barrow"><span><?=htmlspecialchars($x['name']??'-')?></span><div class="bar red"><i style="width:<?=pct($x['total']??0,$mx)?>%"></i></div><b><?=fmt_num($x['total']??0)?></b></div><?php endforeach;?></section>
<section class="panel"><h2>Reconocimientos y comentarios</h2><p>Total reconocidos: <b><?=fmt_num($visual['recognition']['total']??0)?></b></p><p>Con comentario: <b><?=fmt_num($visual['recognition']['commented']??0)?></b></p><p>Pendientes: <b><?=fmt_num($visual['recognition']['pending']??0)?></b></p><p>Cobertura documental: <b><?=number_format((float)($visual['recognition']['coverage']??0),1,',','.')?>%</b></p></section>
<section class="panel"><h2>Reconocimientos pendientes de comentario</h2><table><thead><tr><th>Fecha</th><th>TAG</th><th>Operador</th><th>Prioridad</th></tr></thead><tbody><?php foreach(array_slice($visual['pending_comments']??[],0,10) as $x):?><tr><td><?=htmlspecialchars($x['date']??'')?></td><td><?=htmlspecialchars($x['tag']??'')?></td><td><?=htmlspecialchars($x['operator']??'')?></td><td><?=htmlspecialchars($x['priority']??'')?></td></tr><?php endforeach;?></tbody></table></section></div>
<div class="footer">Reporte generado automáticamente por CLEAR Plataforma. La información refleja el estado disponible al momento de la generación.</div></body></html>
