<?php
require_once __DIR__.'/includes/db.php';require_once __DIR__.'/includes/auth.php';require_once __DIR__.'/includes/permissions.php';require_once __DIR__.'/includes/novedades_semanales_common.php';
auth_require();$view=strtolower(ns_clean($_GET['vista']??'malos_actores',30));$permission=['panel'=>'novedades_semanales_panel','malos_actores'=>'novedades_semanales_malos_actores','comparativa'=>'novedades_semanales_comparativa','seguimiento'=>'novedades_semanales_seguimiento','reporte'=>'novedades_semanales_reporte'][$view]??'';if($permission==='')exit('Vista no válida.');permissions_require_menu($permission);
$cfg=require __DIR__.'/config.php';date_default_timezone_set($cfg['app']['tz']??'UTC');$db=clear_db();if(!$db->ok()){http_response_code(500);exit('Sin conexión a SQL Server.');}if(!ns_module_ready($db)){http_response_code(503);exit('Falta instalar el módulo.');}$today=new DateTimeImmutable('now');$prefs=ns_preferences();$period=ns_period($_GET,$today,$prefs);
function ns_xls($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}function ns_xls_table($title,array $headers,array $rows){echo '<h2>'.ns_xls($title).'</h2><table><thead><tr>';foreach($headers as $h)echo '<th>'.ns_xls($h).'</th>';echo '</tr></thead><tbody>';foreach($rows as $row){echo '<tr>';foreach($headers as $h)echo '<td>'.ns_xls($row[$h]??'').'</td>';echo '</tr>';}echo '</tbody></table>';}
$filename='CLEAR_Novedades_'.ucfirst($view).'_'.$period['from_value'].'_'.$period['to_value'].'.xls';header('Content-Type: application/vnd.ms-excel; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$filename.'"');echo "\xEF\xBB\xBF";echo '<html><head><meta charset="UTF-8"><style>body{font-family:Arial}h1{color:#1a4d5c}table{border-collapse:collapse;margin-bottom:24px}th{background:#1a4d5c;color:white}th,td{border:1px solid #bbb;padding:6px;text-align:left}</style></head><body><h1>CLEAR · Novedades semanales</h1><p>'.ns_xls(ns_period_label($period)).'</p>';
if($view==='reporte'){$items=ns_report_items($db,auth_user());foreach($items as $item){$payload=json_decode((string)ns_value($item,'PAYLOAD_JSON'),true);if(!is_array($payload))$payload=[];if(!empty($payload['context']))echo '<p>'.ns_xls((string)$payload['context']).'</p>';if(($payload['kind']??'')==='chart'){$sets=$payload['datasets']??[];$axis=(string)($payload['axis_label']??'Período');$headers=[$axis];foreach($sets as $set)$headers[]=(string)($set['label']??'Valor');$rows=[];foreach(($payload['labels']??[]) as $i=>$label){$r=[$axis=>$label];foreach($sets as $set)$r[(string)($set['label']??'Valor')]=(array_key_exists($i,$set['values']??[])?($set['values'][$i]===null?'Sin datos':$set['values'][$i]):0);$rows[]=$r;}ns_xls_table((string)ns_value($item,'TITULO'),$headers,$rows);}else{$columns=$payload['columns']??[];$rows=[];foreach($columns as $k=>$v)$rows[]=['Campo'=>$k,'Valor'=>$v];ns_xls_table((string)ns_value($item,'TITULO'),['Campo','Valor'],$rows);}}audit_log('EXPORTACION','novedades_semanales','Reporte seleccionado');echo '</body></html>';exit;}
if($view==='panel'){$weekly=$db->all("SELECT 'Semana '+RIGHT('0'+CONVERT(varchar(2),DATEPART(ISO_WEEK,SEMANA_HASTA)),2) SEMANA,CONVERT(varchar(10),MIN(SEMANA_DESDE),23) DESDE,CONVERT(varchar(10),MAX(SEMANA_HASTA),23) HASTA,SUM(TOTAL_ALARMAS) TOTAL FROM dbo.CLEAR_NOVEDADES_SEMANALES_CACHE WHERE SEMANA_DESDE BETWEEN CONVERT(date,?,23) AND CONVERT(date,?,23) GROUP BY SEMANA_DESDE,SEMANA_HASTA ORDER BY SEMANA_DESDE",[$period['from_value'],$period['to_value']]);$types=$db->all("SELECT TIPO_INSTALACION TIPO,SUM(TOTAL_ALARMAS) TOTAL FROM dbo.CLEAR_NOVEDADES_SEMANALES_CACHE WHERE SEMANA_DESDE BETWEEN CONVERT(date,?,23) AND CONVERT(date,?,23) GROUP BY TIPO_INSTALACION ORDER BY SUM(TOTAL_ALARMAS) DESC",[$period['from_value'],$period['to_value']]);ns_xls_table('Evolución semanal',['SEMANA','DESDE','HASTA','TOTAL'],$weekly);ns_xls_table('Distribución por tipo',['TIPO','TOTAL'],$types);}
else{
  $commentsReady=ns_comments_ready($db);$join=$commentsReady?"LEFT JOIN dbo.CLEAR_NOVEDADES_SEMANALES_COMENTARIOS CO ON CO.SEMANA_DESDE=C.SEMANA_DESDE AND CO.TIPO_INSTALACION=C.TIPO_INSTALACION AND CO.INSTALACION=C.INSTALACION AND CO.TAG=C.TAG":"";$commentSelect=$commentsReady?",CO.COMENTARIO,CO.ACTIVO COMENTARIO_ACTIVO,CO.USUARIO_CARGA,CO.USUARIO_MODIFICACION":",N'' COMENTARIO,CONVERT(bit,0) COMENTARIO_ACTIVO,N'' USUARIO_CARGA,N'' USUARIO_MODIFICACION";
  if($view==='malos_actores'){$filters=ns_bad_actor_filters($_GET,$period);$params=[];$where=ns_bad_actor_where($filters,$params,$commentsReady);$rows=$db->all("SELECT TOP 50000 ".ns_cache_select('C')."$commentSelect FROM dbo.CLEAR_NOVEDADES_SEMANALES_CACHE C $join WHERE ".implode(' AND ',$where)." ORDER BY ".ns_order_sql($filters),$params);}
  else{$params=[$period['from_value'],$period['to_value']];$where=['C.SEMANA_DESDE>=CONVERT(date,?,23)','C.SEMANA_DESDE<=CONVERT(date,?,23)'];$type=ns_clean($_GET['tipo_instalacion']??'',30);if($type!==''){$where[]='C.TIPO_INSTALACION=?';$params[]=$type;}$installation=ns_clean($_GET['instalacion']??'',180);if($installation!==''&&$view==='comparativa'){$where[]='C.INSTALACION LIKE ?';$params[]='%'.$installation.'%';}$rawTags=ns_clean($_GET['tags']??'',900);$tags=array_values(array_filter(array_map('trim',preg_split('/[,;\r\n]+/',$rawTags))));$tags=array_slice($tags,0,5);if($tags&&$view==='comparativa'){$where[]='C.TAG IN ('.implode(',',array_fill(0,count($tags),'?')).')';foreach($tags as $tag)$params[]=$tag;}if($view==='seguimiento'){$q=ns_clean($_GET['q']??'',220);if($q!==''){$where[]='(C.INSTALACION LIKE ? OR C.TAG LIKE ? OR C.DESCRIPCION LIKE ? OR C.CAMPO_EXT LIKE ? OR CO.COMENTARIO LIKE ?)';for($i=0;$i<5;$i++)$params[]='%'.$q.'%';}$scope=strtolower(ns_clean($_GET['estado']??'sin',10));if($scope==='con')$where[]="CO.ACTIVO=1 AND CO.COMENTARIO<>N''";elseif($scope==='sin')$where[]="(CO.ID IS NULL OR CO.ACTIVO=0 OR CO.COMENTARIO=N'')";}$rows=$db->all("SELECT TOP 50000 ".ns_cache_select('C')."$commentSelect FROM dbo.CLEAR_NOVEDADES_SEMANALES_CACHE C $join WHERE ".implode(' AND ',$where)." ORDER BY C.SEMANA_DESDE,C.TOTAL_ALARMAS DESC",$params);}
  $out=[];foreach($rows as $row){$start=ns_parse_date(ns_value($row,'SEMANA_DESDE'));$comment=(int)ns_value($row,'COMENTARIO_ACTIVO',0)===1?(string)ns_value($row,'COMENTARIO'):'';$out[]=['SEMANA'=>$start?'Semana '.$start->modify('+6 days')->format('W'):'','SEMANA_DESDE'=>ns_value($row,'SEMANA_DESDE'),'SEMANA_HASTA'=>ns_value($row,'SEMANA_HASTA'),'TIPO'=>ns_value($row,'TIPO_INSTALACION'),'INSTALACION'=>ns_value($row,'INSTALACION'),'TAG'=>ns_value($row,'TAG'),'DESCRIPCION'=>ns_value($row,'DESCRIPCION'),'TOTAL_ALARMAS'=>ns_value($row,'TOTAL_ALARMAS'),'CAMPO_EXT'=>ns_value($row,'CAMPO_EXT'),'COMENTARIO'=>$comment,'USUARIO'=>(string)(ns_value($row,'USUARIO_MODIFICACION')?:ns_value($row,'USUARIO_CARGA'))];}ns_xls_table(ucfirst(str_replace('_',' ',$view)),['SEMANA','SEMANA_DESDE','SEMANA_HASTA','TIPO','INSTALACION','TAG','DESCRIPCION','TOTAL_ALARMAS','CAMPO_EXT','COMENTARIO','USUARIO'],$out);
}
audit_log('EXPORTACION','novedades_semanales',$view.' '.$period['from_value'].' al '.$period['to_value']);echo '</body></html>';
