<?php
require_once __DIR__.'/db.php';require_once __DIR__.'/auth.php';require_once __DIR__.'/permissions.php';require_once __DIR__.'/icons.php';require_once __DIR__.'/novedades_gestion.php';
$spec=ng_spec($gestionTipo);auth_require();permissions_require_menu($spec['key']);
$cfg=require dirname(__DIR__).'/config.php';date_default_timezone_set($cfg['app']['tz']??'UTC');
$APP_USER=auth_user();$APP_ROLE=auth_es_admin()?'Administrador':'Operador';$ACTIVE=$spec['key'];$now=new DateTimeImmutable('now');$today=$now->format('Y-m-d');
$defaultFrom=ns_week_for_date($now)['start']->modify('-49 days')->format('Y-m-d');$from=$defaultFrom;$to=$today;$error='';
try{$from=ng_date($_GET['desde']??$defaultFrom,'Desde');$to=ng_date($_GET['hasta']??$today,'Hasta');if($from>$to||$to>$today||(new DateTimeImmutable($from))->diff(new DateTimeImmutable($to))->days>83)throw new RuntimeException('Elegí un período de hasta 12 semanas, sin fechas futuras.');}catch(Throwable $e){$error=$e->getMessage();}
$db=clear_db();$data=$error?['ready'=>ng_ready($db),'rows'=>[],'error'=>$error]:ng_list($db,$gestionTipo,$from,$to);$rows=$data['rows'];$ready=$data['ready']&&$data['error']==='';
$canCreate=pfp_can_create();$canEdit=$canCreate||auth_es_admin()||permissions_can('comments.edit_own')||permissions_can('comments.edit_all');
if(empty($_SESSION['novedades_gestion_token']))$_SESSION['novedades_gestion_token']=bin2hex(random_bytes(24));
$reportReady=$db->ok()&&permissions_can_menu('novedades_semanales_reporte')&&ns_report_ready($db);
$columns=$spec['columns'];$isAudit=$gestionTipo==='AUDITORIA';
$chartKeys=['estado'=>ns_report_key('auditoria_estado',[$from,$to]),'semanal'=>ns_report_key('auditoria_cierres',[$from,$to])];
?><!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo h($spec['title']); ?> · CLEAR</title>
<link rel="stylesheet" href="assets/css/app.css"><link rel="stylesheet" href="assets/css/novedades_semanales.css"><link rel="stylesheet" href="assets/css/novedades_monitoreo.css?v=20260828-gestion1"><link rel="stylesheet" href="assets/css/novedades_gestion.css?v=20260828-responsables2"></head>
<body class="ngBody"><div class="app"><?php include __DIR__.'/sidebar.php'; ?><main class="main"><?php include __DIR__.'/topbar.php'; ?><section class="page nsPage ngPage">
<header class="pfHeading"><div><span class="pfEyebrow">NOVEDADES SEMANALES</span><h1><?php echo h($spec['title']); ?></h1><p><?php echo $isAudit?'Estado de las auditorías, evidencias y evolución semanal':'Carga y seguimiento de requerimientos puntuales'; ?></p></div><span class="pfWeekBadge">Gestión manual · historial de cambios</span></header>
<?php ns_render_module_nav($ACTIVE); ?>
<form class="nsToolbar" method="get"><?php if($canCreate): ?><button type="button" id="ngAdd" class="nsButton" <?php echo $ready?'':'disabled'; ?>>+ Agregar <?php echo h($spec['single']); ?></button><?php endif; ?><label class="nsControl">Desde<input type="date" name="desde" value="<?php echo h($from); ?>" max="<?php echo h($today); ?>" required></label><label class="nsControl">Hasta<input type="date" name="hasta" value="<?php echo h($to); ?>" max="<?php echo h($today); ?>" required></label><button type="submit" class="nsButton">Actualizar</button><button type="button" id="ngReset" class="nsButton is-secondary">Ver todos / limpiar filtros</button><?php if($reportReady): ?><button type="button" class="nsButton is-secondary" data-ns-report-open>Ver reporte <span data-ns-report-count hidden>0</span></button><?php endif; ?></form>
<div class="nsNotice">Se incluyen abiertos hasta la fecha Hasta y registros con alta o cierre en el período. Los estados son los actuales, no una fotografía histórica. <?php echo $isAudit?'Cada nueva auditoría tiene su propio registro, aunque sea de la misma instalación.':'Por defecto se muestran pendientes e iniciados.'; ?></div>
<?php if(!$data['ready']): ?><div class="nsNotice is-warning">Falta instalar <b>SQL/CLEAR_NOVEDADES_GESTION.sql</b>. No se modifican Jobs ni tablas de telemetría.</div><?php endif; ?>
<?php if($data['error']): ?><div class="nsNotice is-warning" role="alert"><?php echo h($data['error']); ?></div><?php endif; ?>
<?php if(($_GET['guardado']??'')==='1'): ?><div class="nsNotice" role="status">Registro guardado con su historial. Si no se ve, revisá los filtros.</div><?php endif; ?>
<?php if($canEdit): ?><section id="ngFormPanel" class="nsCard" hidden><div class="nsCard__head"><h2 id="ngFormTitle"></h2><p>Los campos con * son obligatorios. Observaciones y adjunto son opcionales.</p></div>
<form id="ngForm" class="nsCard__body" enctype="multipart/form-data">
<input type="hidden" name="ID" value="0"><input type="hidden" name="VERSION" value="0"><input type="hidden" name="SOLICITUD" value="">
<div class="pfCatalogBar"><span id="ngCatalogStatus" role="status">Las asignaciones se obtienen del catálogo local.</span><button type="button" id="ngReloadCatalog" class="nsButton is-secondary">Actualizar listas</button></div>
<p class="ngHint">Relaciones del maestro Supervisores de instalaciones. Si no tiene Jefe de producción, se utiliza Jefe de zona. No se modifican esas asignaciones desde este formulario.</p>
<div class="ngFields">
<label class="nsControl">Fecha *<input type="date" name="FECHA" value="<?php echo h($today); ?>" min="2000-01-01" max="<?php echo h($today); ?>" required></label>
<?php if($isAudit): ?>
<label class="nsControl">Zona *<select name="ZONA" required><option value="">Seleccionar zona</option><?php foreach(pfp_zones() as $z): ?><option><?php echo h($z); ?></option><?php endforeach; ?></select></label>
<label class="nsControl">Batería / instalación *<input name="BATERIA" list="ngBatteries" maxlength="255" placeholder="Buscar o escribir…" autocomplete="off" required><datalist id="ngBatteries"></datalist></label>
<label class="nsControl">Supervisor *<select name="SUPERVISOR" required><option value="">Seleccionar supervisor</option></select></label>
<label class="nsControl">Jefe de producción *<select name="JEFE_PRODUCCION" required><option value="">Seleccionar jefe</option></select></label>
<?php else: ?>
<label class="nsControl ngWide">Requerimiento *<textarea name="REQUERIMIENTO" maxlength="1000" rows="3" placeholder="Describí lo solicitado…" required></textarea></label>
<label class="nsControl">Tipo de responsable *<select name="RESPONSABLE_TIPO" required><option value="">Seleccionar tipo</option><?php foreach(ngr_types() as $key=>$label): if($key==='LEGADO')continue; ?><option value="<?php echo h($key); ?>"><?php echo h($label); ?></option><?php endforeach; ?></select></label>
<label class="nsControl">Responsable *<select name="RESPONSABLE" required><option value="">Seleccionar responsable</option></select></label>
<label class="nsControl" id="ngRelatedChiefControl" hidden>Jefe de producción *<select name="JEFE_PRODUCCION"><option value="">Seleccionar jefe</option></select></label>
<label class="nsControl ngWide" id="ngRelatedSupervisorsControl" hidden>Supervisores del jefe (opcional)<select id="ngRelatedSupervisors" name="SUPERVISORES[]" multiple size="5"></select><small>Podés elegir varios con Ctrl + clic (hasta 30). Solo se muestran los del jefe elegido.</small></label>
<?php if($canCreate): ?><div class="nsControl ngWide ngNewResponsible" id="ngNewResponsibleControl" hidden><label for="ngNewResponsible">Agregar un responsable para futuras cargas</label><div><input id="ngNewResponsible" maxlength="200" placeholder="Nombre y apellido" autocomplete="off"><button type="button" id="ngSaveResponsible" class="nsButton is-secondary">Guardar responsable</button></div><small>Se comparte en este catálogo. No crea un usuario, contraseña ni permisos de acceso.</small><small id="ngResponsibleStatus" role="status"></small></div><?php endif; ?>
<?php endif; ?>
<label class="nsControl">Estado *<select name="ESTADO" required><?php foreach($spec['states'] as $state): ?><option><?php echo h($state); ?></option><?php endforeach; ?></select></label>
<label class="nsControl" id="ngClosureControl" hidden>Fecha de cierre *<input type="date" name="FECHA_CIERRE" max="<?php echo h($today); ?>"><small>El primer cierre se conserva para la evolución semanal.</small></label>
<label class="nsControl ngWide" id="ngReopenControl" hidden>Motivo de reapertura *<textarea name="MOTIVO_REAPERTURA" maxlength="500" rows="2"></textarea></label>
</div>
<div class="rpPartExtras"><label class="nsControl">Observaciones (opcional)<textarea name="OBSERVACIONES" rows="4" maxlength="2000" placeholder="Escribí las observaciones…"></textarea><small>Hasta 2.000 caracteres.</small></label><div class="nsControl"><label for="ngFile">Adjunto (opcional · máximo 5 MB)</label><input id="ngFile" type="file" name="ADJUNTO" accept=".pdf,.jpg,.jpeg,.png,.webp,.txt,.csv,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.zip"><small>PDF, imágenes, Office, TXT/CSV o ZIP.</small><small id="ngFileInfo" role="status"></small><button type="button" id="ngClearFile" class="nsButton is-secondary" hidden>Cancelar archivo elegido</button><div id="ngOldFile" hidden><a id="ngDownload">Descargar adjunto actual</a><label class="rpRemoveFile"><input type="checkbox" name="QUITAR_ADJUNTO" value="1"> Quitar adjunto al guardar</label></div></div></div>
<p class="pfPartError" id="ngError" hidden role="alert"></p><div class="pfPartActions"><button type="submit" id="ngSave" class="nsButton">Guardar</button><button type="button" id="ngCancel" class="nsButton is-secondary">Cancelar</button><small>El cambio se guarda junto con usuario, fecha y versión.</small></div>
</form></section><?php endif; ?>
<?php if($isAudit): ?><div class="ngCharts">
<article class="nsCard"><div class="nsCard__head"><div><span class="pfEyebrow">ESTADO ACTUAL</span><h2>Distribución de auditorías</h2></div><?php if($reportReady): ?><button type="button" class="nsButton is-secondary" data-ng-chart="estado" disabled>Agregar gráfico al reporte</button><?php endif; ?></div><div class="ngChartArea"><canvas id="ngStateChart" data-clear-chart-local="true" aria-label="Auditorías por estado" role="img"></canvas></div><div class="ngLegend" id="ngStateLegend"></div><p class="ngHint">Clic en un estado para filtrar la grilla. Porcentaje sobre las auditorías incluidas, no sobre todo el catálogo.</p></article>
<article class="nsCard"><div class="nsCard__head"><div><span class="pfEyebrow">MIÉRCOLES A MARTES</span><h2>Finalizadas por semana</h2></div><?php if($reportReady): ?><button type="button" class="nsButton is-secondary" data-ng-chart="semanal" disabled>Agregar gráfico al reporte</button><?php endif; ?></div><div class="ngChartArea"><canvas id="ngWeekChart" data-clear-chart-local="true" aria-label="Primeros cierres por semana" role="img"></canvas></div><p class="ngHint">Cada auditoría cuenta una vez por su primer cierre. Reabrirla no borra ese cierre ni agrega otra auditoría. Clic en un punto para ver el detalle.</p></article>
</div><p id="ngChartMessage" class="ngHint" role="status"></p><?php endif; ?>
<section class="nsTableCard"><div class="nsTableHead"><div><h2><?php echo $isAudit?'Registro de auditorías':'Requerimientos registrados'; ?></h2><p id="ngCount"></p><small id="ngFilterSummary"></small></div><div class="nsTableHead__actions"><?php if($reportReady): ?><button class="nsButton" id="ngReport" type="button">Agregar seleccionados al reporte</button><?php endif; ?><button type="button" id="ngExport" class="nsButton is-secondary">Exportar CSV</button><div class="nsColumnTools"><button class="nsButton is-secondary" type="button" data-ns-columns-toggle>Columnas ▾</button><div class="nsColumnsMenu" data-ns-columns-menu></div></div></div></div>
<div class="tablescroll"><table class="grid nsTable" id="ngTable" data-ns-custom-columns data-ns-no-auto-select-all><thead><tr><?php foreach($columns as $key=>$title): ?><th data-column-key="<?php echo h($key); ?>" data-column-label="<?php echo h($title); ?>"><?php if($key==='ID'&&$reportReady): ?><input id="ngSelectAll" type="checkbox" aria-label="Seleccionar todos los visibles"><?php endif; ?><button type="button" class="nsClientSort" data-ng-sort="<?php echo h($key); ?>"><?php echo h($title); ?></button></th><?php endforeach; ?></tr><tr class="nsFilterRow"><?php foreach($columns as $key=>$title): ?><th data-column-key="<?php echo h($key); ?>"><?php if(in_array($key,['ZONA','BATERIA','SUPERVISOR','JEFE_PRODUCCION','RESPONSABLE_CLASE','RESPONSABLE','ESTADO'],true)): ?><select data-ng-filter="<?php echo h($key); ?>" aria-label="Filtrar <?php echo h($title); ?>"><option value="">Todos</option></select><?php else: ?><input data-ng-filter="<?php echo h($key); ?>" placeholder="Buscar" aria-label="Filtrar <?php echo h($title); ?>"><?php endif; ?></th><?php endforeach; ?></tr></thead>
<tbody><?php foreach($rows as $i=>$row): $payload=['Origen'=>$spec['title']];foreach($columns as $key=>$title)$payload[$title]=$row[$key];$payload['Primer cierre']=$row['FECHA_PRIMER_CIERRE'];$payload['Última modificación']=$row['FECHA_MODIFICACION']; ?><tr data-ng-row="<?php echo $i; ?>"><?php foreach($columns as $key=>$title): ?><td data-column-key="<?php echo h($key); ?>">
<?php if($key==='ID'): ?><?php if($reportReady)echo ns_report_pick(ns_report_key('gestion_'.strtolower($gestionTipo),[$row['ID']]),'row',$spec['title'].' · #'.$row['ID'],ns_report_row_payload($payload)); ?><b>#<?php echo $row['ID']; ?></b><div class="ngRowActions"><?php if($row['CAN_EDIT']): ?><button type="button" class="pfEditPart" data-ng-edit="<?php echo $i; ?>">Editar</button><?php endif; ?><button type="button" class="pfEditPart" data-ng-history="<?php echo $row['ID']; ?>">Historial</button></div>
<?php elseif($key==='ADJUNTO_NOMBRE'): ?><?php if($row[$key]!==''): ?><a class="rpAttachmentLink" href="novedades_gestion_adjunto.php?tipo=<?php echo h($gestionTipo); ?>&amp;id=<?php echo $row['ID']; ?>"><?php echo h($row[$key]); ?></a><?php else: ?>—<?php endif; ?>
<?php elseif($key==='ESTADO'): ?><span class="ngState ngState--<?php echo h(str_replace(' ','-',strtolower($row[$key]))); ?>"><?php echo h($row[$key]); ?></span>
<?php elseif(in_array($key,['OBSERVACIONES','REQUERIMIENTO'],true)): ?><div class="rpObservation"><?php echo h($row[$key]); ?></div><?php else: ?><?php echo h($row[$key]!==''?$row[$key]:'—'); ?><?php endif; ?></td><?php endforeach; ?></tr><?php endforeach; ?><tr id="ngEmpty" <?php echo $rows?'hidden':''; ?>><td colspan="<?php echo count($columns); ?>" class="nsEmpty">Sin registros para mostrar.</td></tr></tbody></table></div></section>
<p id="ngStatus" role="status" class="pfStatus"></p><noscript>Activá JavaScript para editar, filtrar y seleccionar registros.</noscript>
<section class="ngHistory" id="ngHistory" role="dialog" aria-modal="true" aria-labelledby="ngHistoryTitle" hidden><div class="nsCard"><div class="nsCard__head"><h2 id="ngHistoryTitle" tabindex="-1">Historial</h2><button type="button" id="ngCloseHistory" class="nsButton is-secondary">Cerrar</button></div><div id="ngHistoryBody" class="nsCard__body"></div></div></section>
</section></main></div>
<script>window.CLEAR_GESTION=<?php echo nm_json(['type'=>$gestionTipo,'title'=>$spec['title'],'single'=>$spec['single'],'states'=>$spec['states'],'rows'=>$rows,'columns'=>$columns,'from'=>$from,'to'=>$to,'today'=>$today,'user'=>(string)auth_user(),'token'=>$canEdit?$_SESSION['novedades_gestion_token']:'','ready'=>$ready,'canCreate'=>$canCreate,'reportReady'=>$reportReady,'chartKeys'=>$chartKeys]); ?>;</script>
<?php if($isAudit): ?><script src="assets/js/chart.umd.js"></script><?php endif; ?><script src="assets/js/app.js"></script><script src="assets/js/novedades_semanales.js?v=20260828-gestion1"></script><script src="assets/js/novedades_responsables.js?v=20260828-responsables2"></script><script src="assets/js/novedades_gestion.js?v=20260828-responsables2"></script></body></html>
