<?php
/*
 * Historial central de versiones de CLEAR Plataforma.
 * Agregar las nuevas publicaciones al comienzo del arreglo.
 */
function clear_version_history(): array
{
    return [
        [
            'version' => '3.1.0',
            'date' => '2026-07-22 14:30:00',
            'title' => 'Telemetrías unificadas y comunicación de pozos',
            'type' => 'Funcional',
            'status' => 'Publicada',
            'author' => 'Patagonia Control Systems',
            'summary' => 'Se unificaron las pantallas PCP, BES y TECCS con el diseño de Monitoreo Pozos y se incorporó el estado YAT:COM para identificar fallas de comunicación.',
            'changes' => [
                'Diseño y herramientas comunes para Monitoreo Pozos, PCP, BES y TECCS.',
                'Nueva columna Falla de comunicación basada en YAT:COM.',
                'Valores OK y FALLA visibles mediante etiquetas de estado.',
                'Filtros múltiples específicos para batería, estado, método, tipo y comunicación.',
                'La columna de comunicación se incluye en búsqueda, ordenamiento, selector de columnas y exportación.',
                'PCP utiliza exclusivamente las columnas reales configuradas, sin incluir ID.',
                'Se evita mostrar dos veces el campo de comunicación en la grilla.'
            ],
            'modules' => ['Monitoreo Pozos','Telemetría PCP','Telemetría BES','Telemetría TECCS']
        ],
        [
            'version' => '2.8.0',
            'date' => '2026-07-15 00:30:00',
            'title' => 'Reportes PDF programados por correo',
            'type' => 'Funcional',
            'status' => 'Publicada',
            'author' => 'Patagonia Control Systems',
            'summary' => 'Se incorporó la generación automática del reporte operativo del Dashboard en PDF, envío por SMTP y programación de horarios.',
            'changes' => [
                'Nueva pantalla Reportes por correo en Administración.',
                'Configuración SMTP, remitente, URL interna y ruta de Google Chrome.',
                'Programaciones diarias, laborales, semanales, mensuales y por días específicos.',
                'Uno o varios horarios por día y múltiples destinatarios, CC y CCO.',
                'Generación de PDF mediante Chrome Headless.',
                'Historial de ejecuciones y registro de errores.',
                'Scheduler ejecutable desde PHP CLI y Programador de tareas de Windows.',
                'Scripts SQL idempotentes incluidos en el proyecto.'
            ],
            'modules' => ['Dashboard','Administración','Reportes','Seguridad','SQL Server']
        ],
        [
            'version' => '2.7.1',
            'date' => '2026-07-14 23:59:50',
            'title' => 'Eliminación administrativa de comentarios',
            'type' => 'Funcional',
            'status' => 'Publicada',
            'author' => 'Patagonia Control Systems',
            'summary' => 'Los administradores pueden eliminar comentarios desde el historial del Dashboard conservando la trazabilidad en SQL Server.',
            'modules' => ['Dashboard', 'Comentarios', 'Auditoría', 'Administración'],
            'changes' => [
                'Nueva columna Acciones en el historial de comentarios para administradores.',
                'Botón Eliminar con confirmación antes de ejecutar la acción.',
                'Borrado lógico mediante ACTIVO = 0 en dbo.FIXALARMS_COMENTARIOS.',
                'Registro automático de la eliminación en la auditoría del sistema.',
                'Actualización inmediata del contador de comentarios sin recargar la página.',
                'La exportación a Excel excluye la columna de acciones.',
            ],
        ],
        [
            'version' => '2.7.0',
            'date' => '2026-07-14 23:59:30',
            'title' => 'Paquete visual y analítico operativo',
            'type' => 'Mayor',
            'status' => 'Publicada',
            'author' => 'Patagonia Control Systems',
            'summary' => 'Se amplió el Dashboard con gráficos operativos, indicadores de salud, análisis de alarmas y mejoras globales de lectura de grillas.',
            'modules' => ['Dashboard', 'Gráficos', 'Grillas', 'Comentarios', 'Instalaciones'],
            'changes' => [
                'Franja de estado para SQL Server, PI Web API, última alarma, demora y criticidad.',
                'Gráfico de alarmas por hora segmentado por prioridad.',
                'Comparación de activaciones frente a normalizaciones por hora.',
                'Gráfico Pareto del Top 20 con porcentaje acumulado.',
                'Mapa de calor de siete días por veinticuatro horas.',
                'Ranking de alarmas por instalación y cantidad crítica.',
                'Indicador de cobertura documental de reconocimientos.',
                'Listado prioritario de reconocimientos pendientes de comentario.',
                'Selector global de densidad de tablas: normal, compacta y ampliada.',
                'Mejoras de resaltado, selección y coherencia de estados en las grillas.',
            ],
        ],
        [
            'version' => '2.6.1',
            'date' => '2026-07-14 23:59:00',
            'title' => 'Corrección de edición de usuarios',
            'type' => 'Corrección',
            'status' => 'Publicada',
            'author' => 'Patagonia Control Systems',
            'summary' => 'Se restauró el acceso visible y confiable a la edición de usuarios y permisos desde el área administrativa.',
            'modules' => ['Administración', 'Usuarios', 'Permisos'],
            'changes' => [
                'Botón Editar visible con texto e ícono en cada fila de usuario.',
                'Botón Eliminar diferenciado visualmente y con confirmación del usuario seleccionado.',
                'Carga segura de permisos mediante un mapa JavaScript centralizado.',
                'Resaltado de la fila que se encuentra en edición.',
                'Desplazamiento automático al formulario al seleccionar Editar.',
                'Se mantienen la contraseña actual cuando el campo se deja vacío y todos los permisos configurados.',
            ],
        ],
        [
            'version' => '2.6.0',
            'date' => '2026-07-14 23:55:00',
            'title' => 'Control de versiones de la plataforma',
            'type' => 'Funcional',
            'status' => 'Publicada',
            'author' => 'Patagonia Control Systems',
            'summary' => 'Se incorporó una página administrativa para consultar el historial completo de cambios desde la versión más reciente hasta la más antigua.',
            'modules' => ['Administración', 'Versiones'],
            'changes' => [
                'Nueva opción Control de versiones dentro del menú de Administración.',
                'Historial cronológico ordenado de la publicación más reciente a la más antigua.',
                'Tarjetas con versión actual, cantidad de publicaciones y cambios documentados.',
                'Detalle desplegable con módulos afectados y cambios incluidos en cada versión.',
                'Búsqueda por texto y filtros por tipo de versión y módulo.',
                'Exportación CSV del historial filtrado.',
                'Permiso independiente para habilitar o bloquear el acceso a la página.',
            ],
        ],
        [
            'version' => '2.5.0',
            'date' => '2026-07-14 23:30:00',
            'title' => 'Usuarios, permisos y administración integral',
            'type' => 'Mayor',
            'status' => 'Publicada',
            'author' => 'Patagonia Control Systems',
            'summary' => 'Se incorporó la administración granular de accesos, permisos de comentarios, seguridad, auditoría y preferencias por usuario.',
            'modules' => ['Administración', 'Seguridad', 'Usuarios'],
            'changes' => [
                'Perfiles predefinidos: Administrador, Supervisor, Operador, Consulta y PI / Mantenimiento.',
                'Permisos independientes para ver, crear, editar y desactivar comentarios.',
                'Selección individual de las pantallas visibles para cada usuario.',
                'Validación de permisos tanto en el menú como en las páginas, APIs y exportaciones.',
                'Bloqueo temporal por intentos fallidos y cierre de sesión por inactividad.',
                'Auditoría de accesos, cambios de permisos, comentarios y exportaciones.',
                'Favoritos y preferencias guardadas por usuario.',
            ],
        ],
        [
            'version' => '2.4.0',
            'date' => '2026-07-14 22:50:00',
            'title' => 'PI Histórico y eventos SQL',
            'type' => 'Mayor',
            'status' => 'Publicada',
            'author' => 'Patagonia Control Systems',
            'summary' => 'Evolución de PI Histórico para comparar tendencias del PI System con eventos y valores registrados en SQL Server.',
            'modules' => ['PI Histórico', 'SQL Server'],
            'changes' => [
                'Acceso directo a PI Histórico al seleccionar un TAG desde las grillas.',
                'Rangos rápidos desde un minuto hasta un mes y rango personalizado desde/hasta.',
                'TAG seleccionado destacado visualmente y sugerencias de TAG relacionados.',
                'Consulta independiente de eventos SQL cuando PI Web API no está disponible.',
                'Gráfico paralelo de baja altura para los valores o actuaciones provenientes de SQL.',
                'Comentarios sobre puntos SQL con almacenamiento centralizado.',
                'Fondo institucional incorporado a la pantalla de inicio de sesión.',
            ],
        ],
        [
            'version' => '2.3.0',
            'date' => '2026-07-14 21:40:00',
            'title' => 'Comentarios centralizados en SQL Server',
            'type' => 'Mayor',
            'status' => 'Publicada',
            'author' => 'Patagonia Control Systems',
            'summary' => 'Todos los comentarios de reconocimientos quedaron centralizados en dbo.FIXALARMS_COMENTARIOS.',
            'modules' => ['Reconocidas', 'Dashboard', 'Comentarios'],
            'changes' => [
                'Carga de motivo y comentario desde Alarmas reconocidas.',
                'Carga y consulta agrupada desde Reconocidas por usuario.',
                'Indicador visual cuando un TAG posee comentarios.',
                'Historial de comentarios en el Dashboard, ordenado del más reciente al más antiguo.',
                'Grilla ordenable, filtro aproximado por TAG y exportación compatible con Excel.',
                'Corrección del tratamiento de fechas en formato argentino e ISO para SQL Server.',
                'Eliminación del almacenamiento local JSON para comentarios de reconocimientos.',
            ],
        ],
        [
            'version' => '2.2.0',
            'date' => '2026-07-14 19:30:00',
            'title' => 'Nueva vista Todas las alarmas',
            'type' => 'Funcional',
            'status' => 'Publicada',
            'author' => 'Patagonia Control Systems',
            'summary' => 'Se incorporó la consulta completa de dbo.FIXALARMS con herramientas avanzadas de búsqueda y personalización.',
            'modules' => ['Todas las alarmas'],
            'changes' => [
                'Ordenamiento desde la alarma más reciente a la más antigua.',
                'Buscadores aproximados independientes por TAG y descripción.',
                'Filtro de fecha y hora desde/hasta.',
                'Selector para mostrar u ocultar cualquier columna.',
                'Vista compacta y persistencia de columnas en el navegador.',
                'Paginación de cien registros y panel lateral con detalle completo.',
                'Exportación a Excel respetando filtros y columnas visibles.',
            ],
        ],
        [
            'version' => '2.1.0',
            'date' => '2026-07-14 17:45:00',
            'title' => 'Indicadores, rankings y resumen semanal',
            'type' => 'Funcional',
            'status' => 'Publicada',
            'author' => 'Patagonia Control Systems',
            'summary' => 'Se ampliaron las pantallas de análisis con indicadores interactivos, tarjetas y gráficos semanales.',
            'modules' => ['Alarmas 24h', 'Top 20', 'Top semanal'],
            'changes' => [
                'Indicadores clickeables por Valor, Estado y Prioridad en Alarmas 24h.',
                'Cantidad total, cantidad de TAG y TAG más repetido.',
                'Tarjetas de total, TAG principal, instalación principal y concentración del Top 5.',
                'Top semanal con criticidad alta, media y baja de los últimos siete días.',
                'Gráficos diarios comparativos y tendencia del volumen total.',
                'Actualización automática configurable por pantalla.',
            ],
        ],
        [
            'version' => '2.0.0',
            'date' => '2026-07-14 15:15:00',
            'title' => 'Rediseño operativo y filtros avanzados',
            'type' => 'Mayor',
            'status' => 'Publicada',
            'author' => 'Patagonia Control Systems',
            'summary' => 'Modernización general de la plataforma de monitoreo y normalización de la experiencia de todas las grillas.',
            'modules' => ['Interfaz', 'Grillas', 'Filtros'],
            'changes' => [
                'Ordenamiento ascendente y descendente en columnas.',
                'Encabezados fijos y panel lateral de detalle.',
                'Filtros por instalación, estado, prioridad, fecha y hora.',
                'Búsqueda aproximada y autocompletado de TAG.',
                'Exportación CSV respetando los filtros aplicados.',
                'Renombre de Alarmas activas a Alarmas por Históricos.',
                'Diseño responsivo y mejoras generales de legibilidad.',
            ],
        ],
        [
            'version' => '1.0.0',
            'date' => '2026-07-01 09:00:00',
            'title' => 'Primera versión operativa',
            'type' => 'Inicial',
            'status' => 'Histórica',
            'author' => 'Patagonia Control Systems',
            'summary' => 'Versión inicial de la plataforma CLEAR para visualización y seguimiento de alarmas.',
            'modules' => ['Plataforma'],
            'changes' => [
                'Dashboard operativo.',
                'Pantallas de Alarmas 24h, alarmas activas, suprimidas y reconocidas.',
                'Rankings generales y de las últimas 24 horas.',
                'Conexión con SQL Server y PI Web API.',
                'Autenticación básica de usuarios.',
            ],
        ],
    ];
}

function clear_current_version(): string
{
    $history = clear_version_history();
    return $history[0]['version'] ?? '1.0.0';
}
