USE [LC_MDB];
GO
SET NOCOUNT ON;
PRINT '=== CLEAR - ACTUALIZACION DE ESTADISTICAS ===';

IF OBJECT_ID('dbo.FIXALARMS','U') IS NOT NULL
BEGIN
    PRINT 'Actualizando estadísticas de dbo.FIXALARMS...';
    UPDATE STATISTICS dbo.FIXALARMS WITH RESAMPLE;
END

IF OBJECT_ID('dbo.BM_RTQP','U') IS NOT NULL
BEGIN
    PRINT 'Actualizando estadísticas de dbo.BM_RTQP...';
    UPDATE STATISTICS dbo.BM_RTQP WITH RESAMPLE;
END

PRINT 'Finalizado: ' + CONVERT(varchar(19),GETDATE(),120);
