USE [LC_MDB];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

/*
  CLEAR 8 - OPTIMIZACION GLOBAL
  =============================
  - dbo.FIXALARMS permanece exclusivamente en modo lectura.
  - No agrega columnas, índices ni triggers a dbo.FIXALARMS.
  - Los objetos DDL se instalan una sola vez; PHP deja de ejecutar ALTER VIEW.
  - Materializa indicadores operativos cada 5 minutos en una tabla CLEAR.
*/

IF OBJECT_ID(N'dbo.CLEAR_ALARM_FILTERS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CLEAR_ALARM_FILTERS
    (
        ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CLEAR_ALARM_FILTERS PRIMARY KEY,
        CAMPO NVARCHAR(20) NOT NULL CONSTRAINT DF_CLEAR_ALARM_FILTERS_CAMPO DEFAULT N'AMBOS',
        MODO NVARCHAR(20) NOT NULL CONSTRAINT DF_CLEAR_ALARM_FILTERS_MODO DEFAULT N'CONTIENE',
        VALOR NVARCHAR(500) NOT NULL,
        ACTIVO BIT NOT NULL CONSTRAINT DF_CLEAR_ALARM_FILTERS_ACTIVO DEFAULT (1),
        FECHA_ALTA DATETIME2(0) NOT NULL CONSTRAINT DF_CLEAR_ALARM_FILTERS_FECHA DEFAULT SYSDATETIME(),
        USUARIO_ALTA NVARCHAR(128) NULL
    );
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.CLEAR_ALARM_FILTERS WHERE VALOR=N'Shutdown attempt in progress...PTALH03')
BEGIN
    INSERT dbo.CLEAR_ALARM_FILTERS(CAMPO,MODO,VALOR,ACTIVO,USUARIO_ALTA)
    VALUES(N'DESCRIPCION',N'CONTIENE',N'Shutdown attempt in progress...PTALH03',1,N'SISTEMA');
END;
GO

/* Las vistas filtradas se actualizan aquí una sola vez. */
EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS AS
SELECT A.*
FROM dbo.FIXALARMS A
WHERE NOT EXISTS
(
  SELECT 1 FROM dbo.CLEAR_ALARM_FILTERS F
  WHERE F.ACTIVO=1 AND
  (
    (F.CAMPO IN (N''TAG'',N''AMBOS'') AND
      ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_TAGNAME)))=F.VALOR)
       OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) LIKE F.VALOR+N''%'')
       OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) LIKE N''%''+F.VALOR+N''%'')))
    OR
    (F.CAMPO IN (N''DESCRIPCION'',N''AMBOS'') AND
      ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_DESCR)))=F.VALOR)
       OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE F.VALOR+N''%'')
       OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE N''%''+F.VALOR+N''%'')))
  )
)');
GO

EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS_24H AS SELECT A.* FROM dbo.FIXALARMS_24H A WHERE NOT EXISTS (SELECT 1 FROM dbo.CLEAR_ALARM_FILTERS F WHERE F.ACTIVO=1 AND ((F.CAMPO IN (N''TAG'',N''AMBOS'') AND ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_TAGNAME)))=F.VALOR) OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) LIKE F.VALOR+N''%'') OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) LIKE N''%''+F.VALOR+N''%''))) OR (F.CAMPO IN (N''DESCRIPCION'',N''AMBOS'') AND ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_DESCR)))=F.VALOR) OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE F.VALOR+N''%'') OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE N''%''+F.VALOR+N''%'')))))');
GO
EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS_ONLY AS SELECT A.* FROM dbo.FIXALARMS_ONLY A WHERE NOT EXISTS (SELECT 1 FROM dbo.CLEAR_ALARM_FILTERS F WHERE F.ACTIVO=1 AND ((F.CAMPO IN (N''TAG'',N''AMBOS'') AND ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_TAGNAME)))=F.VALOR) OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) LIKE F.VALOR+N''%'') OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) LIKE N''%''+F.VALOR+N''%''))) OR (F.CAMPO IN (N''DESCRIPCION'',N''AMBOS'') AND ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_DESCR)))=F.VALOR) OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE F.VALOR+N''%'') OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE N''%''+F.VALOR+N''%'')))))');
GO
EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS_RECONOCIDAS AS SELECT A.* FROM dbo.FIXALARMS_RECONOCIDAS A WHERE NOT EXISTS (SELECT 1 FROM dbo.CLEAR_ALARM_FILTERS F WHERE F.ACTIVO=1 AND ((F.CAMPO IN (N''TAG'',N''AMBOS'') AND ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.TAG_FIX)))=F.VALOR) OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.TAG_FIX) LIKE F.VALOR+N''%'') OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.TAG_FIX) LIKE N''%''+F.VALOR+N''%''))) OR (F.CAMPO IN (N''DESCRIPCION'',N''AMBOS'') AND ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_DESCR)))=F.VALOR) OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE F.VALOR+N''%'') OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE N''%''+F.VALOR+N''%'')))))');
GO
EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS_SUPRIMIDAS24H AS SELECT A.* FROM dbo.FIXALARMS_SUPRIMIDAS24H A WHERE NOT EXISTS (SELECT 1 FROM dbo.CLEAR_ALARM_FILTERS F WHERE F.ACTIVO=1 AND ((F.CAMPO IN (N''TAG'',N''AMBOS'') AND ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.TagID)))=F.VALOR) OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.TagID) LIKE F.VALOR+N''%'') OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.TagID) LIKE N''%''+F.VALOR+N''%''))) OR (F.CAMPO IN (N''DESCRIPCION'',N''AMBOS'') AND ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.Descripcion)))=F.VALOR) OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.Descripcion) LIKE F.VALOR+N''%'') OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.Descripcion) LIKE N''%''+F.VALOR+N''%'')))))');
GO

EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS_TOP20_ALL AS SELECT ALM_TAGNAME,MAX(CONVERT(nvarchar(1000),ALM_DESCR)) DESCRIPCION,COUNT_BIG(*) TOTAL_ALARMAS,MAX(CONVERT(nvarchar(500),ALM_ALMEXTFLD2)) ALM_ALMEXTFLD2 FROM dbo.CLEAR_F_FIXALARMS WHERE ALM_TAGNAME IS NOT NULL AND LTRIM(RTRIM(CONVERT(nvarchar(500),ALM_TAGNAME)))<>N'''' GROUP BY ALM_TAGNAME');
EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS_TOP20_24H AS SELECT ALM_TAGNAME,MAX(CONVERT(nvarchar(1000),ALM_DESCR)) DESCRIPCION,COUNT_BIG(*) TOTAL_ALARMAS,MAX(CONVERT(nvarchar(500),ALM_ALMEXTFLD2)) ALM_ALMEXTFLD2 FROM dbo.CLEAR_F_FIXALARMS_24H WHERE ALM_TAGNAME IS NOT NULL AND LTRIM(RTRIM(CONVERT(nvarchar(500),ALM_TAGNAME)))<>N'''' GROUP BY ALM_TAGNAME');
EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS_TOP20 AS SELECT * FROM dbo.CLEAR_F_FIXALARMS_TOP20_ALL');
EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS_RANK24H AS SELECT ROW_NUMBER() OVER(ORDER BY COUNT_BIG(*) DESC) Ranking,ALM_TAGNAME,MAX(CONVERT(nvarchar(1000),ALM_DESCR)) ALM_DESCR,COUNT_BIG(*) Cantidad_Repeticiones FROM dbo.CLEAR_F_FIXALARMS_24H WHERE ALM_TAGNAME IS NOT NULL GROUP BY ALM_TAGNAME');
EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS_TENDENCIA_SEM AS SELECT CONVERT(date,ALM_NATIVETIMEIN) Fecha,COUNT_BIG(*) Total_Alarmas FROM dbo.CLEAR_F_FIXALARMS WHERE ALM_NATIVETIMEIN>=DATEADD(day,-6,CONVERT(date,GETDATE())) GROUP BY CONVERT(date,ALM_NATIVETIMEIN)');
EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS_TEND_SEM_TAGS AS SELECT CONVERT(date,ALM_NATIVETIMEIN) Fecha,ALM_TAGNAME,COUNT_BIG(*) Total_Alarmas FROM dbo.CLEAR_F_FIXALARMS WHERE ALM_NATIVETIMEIN>=DATEADD(day,-6,CONVERT(date,GETDATE())) AND ALM_TAGNAME IS NOT NULL GROUP BY CONVERT(date,ALM_NATIVETIMEIN),ALM_TAGNAME');
EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS_PRIORITY AS SELECT ALM_ALMPRIORITY,COUNT_BIG(*) TOTAL FROM dbo.CLEAR_F_FIXALARMS GROUP BY ALM_ALMPRIORITY');
EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALAMRS_TOP_HML AS SELECT CONVERT(date,ALM_NATIVETIMEIN) Fecha,SUM(CASE WHEN UPPER(CONVERT(nvarchar(100),ALM_ALMPRIORITY)) IN (N''HIGH'',N''HI'',N''ALTA'',N''CRITICAL'',N''CRITICA'') THEN 1 ELSE 0 END) PrioridadAlta,SUM(CASE WHEN UPPER(CONVERT(nvarchar(100),ALM_ALMPRIORITY)) IN (N''MED'',N''MEDIUM'',N''MEDIA'') THEN 1 ELSE 0 END) PrioridadMedia,SUM(CASE WHEN UPPER(CONVERT(nvarchar(100),ALM_ALMPRIORITY)) IN (N''LOW'',N''LO'',N''BAJA'',N''INFO'') THEN 1 ELSE 0 END) PrioridadBaja FROM dbo.CLEAR_F_FIXALARMS WHERE ALM_NATIVETIMEIN>=DATEADD(day,-6,CONVERT(date,GETDATE())) GROUP BY CONVERT(date,ALM_NATIVETIMEIN)');
EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS_RECONOCIDAS_usr AS SELECT ROW_NUMBER() OVER(ORDER BY COUNT_BIG(*) DESC) RANKING,TAG_FIX,OPERADOR,COUNT_BIG(*) CANTIDAD_RECONOCIMIENTOS FROM dbo.CLEAR_F_FIXALARMS_RECONOCIDAS GROUP BY TAG_FIX,OPERADOR');
GO

IF OBJECT_ID(N'dbo.CLEAR_CACHE_OPERATIVA', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CLEAR_CACHE_OPERATIVA
    (
        METRICA NVARCHAR(50) NOT NULL,
        ORDEN INT NOT NULL,
        DIMENSION1 NVARCHAR(500) NULL,
        DIMENSION2 NVARCHAR(500) NULL,
        VALOR1 DECIMAL(38,4) NULL,
        VALOR2 DECIMAL(38,4) NULL,
        VALOR3 DECIMAL(38,4) NULL,
        TEXTO1 NVARCHAR(1000) NULL,
        FECHA_CACHE DATETIME2(0) NOT NULL
    );
    CREATE CLUSTERED INDEX IX_CLEAR_CACHE_OPERATIVA_METRICA
      ON dbo.CLEAR_CACHE_OPERATIVA(METRICA,ORDEN);
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_CLEAR_ACTUALIZAR_CACHE_OPERATIVA
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET DEADLOCK_PRIORITY LOW;

    DECLARE @ahora DATETIME2(0)=SYSDATETIME();
    DECLARE @lockResult INT;
    EXEC @lockResult=sys.sp_getapplock @Resource=N'CLEAR_CACHE_OPERATIVA',@LockMode=N'Exclusive',@LockOwner=N'Session',@LockTimeout=0;
    IF @lockResult<0 RETURN;

    CREATE TABLE #N
    (
        METRICA NVARCHAR(50) NOT NULL, ORDEN INT NOT NULL,
        DIMENSION1 NVARCHAR(500) NULL, DIMENSION2 NVARCHAR(500) NULL,
        VALOR1 DECIMAL(38,4) NULL, VALOR2 DECIMAL(38,4) NULL, VALOR3 DECIMAL(38,4) NULL,
        TEXTO1 NVARCHAR(1000) NULL, FECHA_CACHE DATETIME2(0) NOT NULL
    );

    SELECT
      A.ALM_NATIVETIMEIN,
      LTRIM(RTRIM(CONVERT(nvarchar(500),A.ALM_TAGNAME))) TAG,
      UPPER(LTRIM(RTRIM(CONVERT(nvarchar(100),A.ALM_ALMPRIORITY)))) PRIORIDAD,
      UPPER(LTRIM(RTRIM(CONVERT(nvarchar(255),A.ALM_ALMSTATUS)))) ESTADO,
      UPPER(LTRIM(RTRIM(CONVERT(nvarchar(500),A.ALM_VALUE)))) VALOR
    INTO #BASE7
    FROM dbo.CLEAR_F_FIXALARMS A
    WHERE A.ALM_NATIVETIMEIN>=DATEADD(day,-6,CONVERT(date,@ahora));

    CREATE CLUSTERED INDEX IX_BASE7_FECHA ON #BASE7(ALM_NATIVETIMEIN);
    SELECT * INTO #BASE24 FROM #BASE7 WHERE ALM_NATIVETIMEIN>=DATEADD(hour,-24,@ahora);

    INSERT #N VALUES(N'KPI',1,N'TOTAL24H',NULL,(SELECT COUNT_BIG(*) FROM #BASE24),NULL,NULL,NULL,@ahora);
    INSERT #N VALUES(N'KPI',2,N'TAGS_UNICOS24H',NULL,(SELECT COUNT_BIG(DISTINCT NULLIF(TAG,N'')) FROM #BASE24),NULL,NULL,NULL,@ahora);
    INSERT #N VALUES(N'KPI',3,N'CRITICAS',NULL,(SELECT COUNT_BIG(*) FROM #BASE24 WHERE PRIORIDAD IN (N'HIGH',N'HI',N'ALTA',N'CRITICAL',N'CRITICA',N'CRÍTICA')),NULL,NULL,NULL,@ahora);
    INSERT #N VALUES(N'KPI',4,N'ACTIVAS',NULL,(SELECT COUNT_BIG(*) FROM dbo.CLEAR_F_FIXALARMS_ONLY),NULL,NULL,NULL,@ahora);
    INSERT #N VALUES(N'KPI',5,N'RECONOCIDAS',NULL,(SELECT COUNT_BIG(*) FROM dbo.CLEAR_F_FIXALARMS_RECONOCIDAS),NULL,NULL,NULL,@ahora);
    INSERT #N VALUES(N'KPI',6,N'SUPRIMIDAS',NULL,(SELECT COUNT_BIG(*) FROM dbo.CLEAR_F_FIXALARMS_SUPRIMIDAS24H),NULL,NULL,NULL,@ahora);
    INSERT #N VALUES(N'KPI',7,N'COMENTADAS',NULL,(SELECT COUNT_BIG(*) FROM dbo.FIXALARMS_COMENTARIOS WHERE ACTIVO=1 AND COMENTARIO IS NOT NULL AND LTRIM(RTRIM(COMENTARIO))<>N''),NULL,NULL,NULL,@ahora);
    INSERT #N VALUES(N'KPI',8,N'ULTIMA_ALARMA',NULL,NULL,NULL,NULL,(SELECT TOP(1) CONVERT(nvarchar(19),ALM_NATIVETIMEIN,120) FROM #BASE7 ORDER BY ALM_NATIVETIMEIN DESC),@ahora);
    IF OBJECT_ID(N'dbo.POZOS') IS NOT NULL INSERT #N VALUES(N'KPI',9,N'POZOS',NULL,(SELECT COUNT_BIG(*) FROM dbo.POZOS),NULL,NULL,NULL,@ahora);
    IF OBJECT_ID(N'dbo.ALM_Importadas') IS NOT NULL INSERT #N VALUES(N'KPI',10,N'IMPORTADAS',NULL,(SELECT COUNT_BIG(*) FROM dbo.ALM_Importadas),NULL,NULL,NULL,@ahora);

    ;WITH T AS (SELECT TAG,COUNT_BIG(*) TOTAL FROM #BASE24 WHERE NULLIF(TAG,N'') IS NOT NULL GROUP BY TAG),
    R AS (SELECT ROW_NUMBER() OVER(ORDER BY TOTAL DESC,TAG) ORDEN,TAG,TOTAL FROM T)
    INSERT #N SELECT N'TOP_ALARMAS',ORDEN,TAG,NULL,TOTAL,NULL,NULL,NULL,@ahora FROM R WHERE ORDEN<=20;

    INSERT #N
    SELECT N'TENDENCIA',ROW_NUMBER() OVER(ORDER BY CONVERT(date,ALM_NATIVETIMEIN)),CONVERT(nvarchar(10),CONVERT(date,ALM_NATIVETIMEIN),23),NULL,COUNT_BIG(*),NULL,NULL,NULL,@ahora
    FROM #BASE7 GROUP BY CONVERT(date,ALM_NATIVETIMEIN);

    ;WITH P AS
    (
      SELECT CASE WHEN PRIORIDAD IN (N'HIGH',N'HI',N'ALTA',N'CRITICAL',N'CRITICA',N'CRÍTICA') THEN N'HIGH'
                  WHEN PRIORIDAD IN (N'MED',N'MEDIUM',N'MEDIA') THEN N'MEDIUM'
                  WHEN PRIORIDAD IN (N'LOW',N'LO',N'BAJA') THEN N'LOW' ELSE N'INFO' END CLASE,COUNT_BIG(*) TOTAL
      FROM #BASE24 GROUP BY CASE WHEN PRIORIDAD IN (N'HIGH',N'HI',N'ALTA',N'CRITICAL',N'CRITICA',N'CRÍTICA') THEN N'HIGH' WHEN PRIORIDAD IN (N'MED',N'MEDIUM',N'MEDIA') THEN N'MEDIUM' WHEN PRIORIDAD IN (N'LOW',N'LO',N'BAJA') THEN N'LOW' ELSE N'INFO' END
    ) INSERT #N SELECT N'PRIORIDAD',ROW_NUMBER() OVER(ORDER BY CLASE),CLASE,NULL,TOTAL,NULL,NULL,NULL,@ahora FROM P;

    ;WITH O AS (SELECT OPERADOR,COUNT_BIG(*) TOTAL FROM dbo.CLEAR_F_FIXALARMS_RECONOCIDAS WHERE OPERADOR IS NOT NULL GROUP BY OPERADOR),
    R AS (SELECT ROW_NUMBER() OVER(ORDER BY TOTAL DESC,OPERADOR) ORDEN,OPERADOR,TOTAL FROM O)
    INSERT #N SELECT N'OPERADORES',ORDEN,CONVERT(nvarchar(500),OPERADOR),NULL,TOTAL,NULL,NULL,NULL,@ahora FROM R WHERE ORDEN<=3;

    INSERT #N
    SELECT N'HORARIA',DATEPART(hour,ALM_NATIVETIMEIN)+1,CONVERT(nvarchar(2),DATEPART(hour,ALM_NATIVETIMEIN)),NULL,
      SUM(CASE WHEN PRIORIDAD IN (N'HIGH',N'HI',N'ALTA',N'CRITICAL',N'CRITICA',N'CRÍTICA') THEN 1 ELSE 0 END),
      SUM(CASE WHEN PRIORIDAD IN (N'MED',N'MEDIUM',N'MEDIA') THEN 1 ELSE 0 END),
      SUM(CASE WHEN PRIORIDAD NOT IN (N'HIGH',N'HI',N'ALTA',N'CRITICAL',N'CRITICA',N'CRÍTICA',N'MED',N'MEDIUM',N'MEDIA') THEN 1 ELSE 0 END),NULL,@ahora
    FROM #BASE24 GROUP BY DATEPART(hour,ALM_NATIVETIMEIN);

    INSERT #N
    SELECT N'FLUJO',DATEPART(hour,ALM_NATIVETIMEIN)+1,CONVERT(nvarchar(2),DATEPART(hour,ALM_NATIVETIMEIN)),NULL,
      SUM(CASE WHEN VALOR NOT IN (N'NORMAL',N'OK',N'HABILITADO') THEN 1 ELSE 0 END),
      SUM(CASE WHEN VALOR IN (N'NORMAL',N'OK',N'HABILITADO') THEN 1 ELSE 0 END),NULL,NULL,@ahora
    FROM #BASE24 GROUP BY DATEPART(hour,ALM_NATIVETIMEIN);

    INSERT #N
    SELECT N'HEATMAP',ROW_NUMBER() OVER(ORDER BY CONVERT(date,ALM_NATIVETIMEIN),DATEPART(hour,ALM_NATIVETIMEIN)),
      CONVERT(nvarchar(10),CONVERT(date,ALM_NATIVETIMEIN),23),CONVERT(nvarchar(2),DATEPART(hour,ALM_NATIVETIMEIN)),COUNT_BIG(*),NULL,NULL,NULL,@ahora
    FROM #BASE7 GROUP BY CONVERT(date,ALM_NATIVETIMEIN),DATEPART(hour,ALM_NATIVETIMEIN);

    ;WITH I AS
    (
      SELECT CASE WHEN CHARINDEX(N'_',TAG)>0 THEN LEFT(TAG,CHARINDEX(N'_',TAG)-1) ELSE TAG END INSTALACION,
        COUNT_BIG(*) TOTAL,SUM(CASE WHEN PRIORIDAD IN (N'HIGH',N'HI',N'ALTA',N'CRITICAL',N'CRITICA',N'CRÍTICA') THEN 1 ELSE 0 END) CRITICAS
      FROM #BASE24 WHERE NULLIF(TAG,N'') IS NOT NULL
      GROUP BY CASE WHEN CHARINDEX(N'_',TAG)>0 THEN LEFT(TAG,CHARINDEX(N'_',TAG)-1) ELSE TAG END
    ), R AS (SELECT ROW_NUMBER() OVER(ORDER BY TOTAL DESC,INSTALACION) ORDEN,* FROM I)
    INSERT #N SELECT N'INSTALACIONES',ORDEN,INSTALACION,NULL,TOTAL,CRITICAS,NULL,NULL,@ahora FROM R WHERE ORDEN<=8;

    INSERT #N SELECT N'FILTRO_ESTADO',ROW_NUMBER() OVER(ORDER BY E),E,NULL,NULL,NULL,NULL,NULL,@ahora
    FROM (SELECT DISTINCT ESTADO E FROM #BASE24 WHERE ESTADO IS NOT NULL) X WHERE E<>N'' AND E<>N'CFN';
    INSERT #N SELECT N'FILTRO_PRIORIDAD',ROW_NUMBER() OVER(ORDER BY P),P,NULL,NULL,NULL,NULL,NULL,@ahora
    FROM (SELECT DISTINCT PRIORIDAD P FROM #BASE24 WHERE PRIORIDAD IS NOT NULL) X WHERE P<>N'';
    INSERT #N SELECT N'FILTRO_INSTALACION',ROW_NUMBER() OVER(ORDER BY I),I,NULL,NULL,NULL,NULL,NULL,@ahora
    FROM (SELECT DISTINCT CASE WHEN CHARINDEX(N'_',TAG)>0 THEN LEFT(TAG,CHARINDEX(N'_',TAG)-1) ELSE TAG END I FROM #BASE24 WHERE NULLIF(TAG,N'') IS NOT NULL) X WHERE I<>N'';

    INSERT #N SELECT N'VALORES',ROW_NUMBER() OVER(ORDER BY VALOR),VALOR,NULL,COUNT_BIG(*),NULL,NULL,NULL,@ahora FROM #BASE24 WHERE VALOR IN (N'ALARMA',N'NORMAL',N'FALLA') GROUP BY VALOR;
    INSERT #N SELECT N'ESTADOS',ROW_NUMBER() OVER(ORDER BY ESTADO),ESTADO,NULL,COUNT_BIG(*),NULL,NULL,NULL,@ahora FROM #BASE24 WHERE ESTADO IN (N'OK',N'HI',N'LO') GROUP BY ESTADO;
    INSERT #N SELECT N'PRIORIDADES',ROW_NUMBER() OVER(ORDER BY P),P,NULL,COUNT_BIG(*),NULL,NULL,NULL,@ahora FROM (SELECT CASE WHEN PRIORIDAD IN (N'LOW',N'BAJA') THEN N'LOW' WHEN PRIORIDAD IN (N'CRITICAL',N'CRITICA',N'CRÍTICA') THEN N'CRITICAL' ELSE PRIORIDAD END P FROM #BASE24) X WHERE P IN (N'LOW',N'CRITICAL',N'INFO') GROUP BY P;

    BEGIN TRY
      BEGIN TRANSACTION;
        TRUNCATE TABLE dbo.CLEAR_CACHE_OPERATIVA;
        INSERT dbo.CLEAR_CACHE_OPERATIVA SELECT * FROM #N;
      COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
      IF @@TRANCOUNT>0 ROLLBACK TRANSACTION;
      EXEC sys.sp_releaseapplock @Resource=N'CLEAR_CACHE_OPERATIVA',@LockOwner=N'Session';
      THROW;
    END CATCH;
    EXEC sys.sp_releaseapplock @Resource=N'CLEAR_CACHE_OPERATIVA',@LockOwner=N'Session';
END;
GO

EXEC dbo.SP_CLEAR_ACTUALIZAR_CACHE_OPERATIVA;
GO

USE [msdb];
GO
IF EXISTS(SELECT 1 FROM dbo.sysjobs WHERE name=N'CLEAR - Caché operativa cada 5 minutos')
  EXEC dbo.sp_delete_job @job_name=N'CLEAR - Caché operativa cada 5 minutos',@delete_unused_schedule=1;
GO
EXEC dbo.sp_add_job @job_name=N'CLEAR - Caché operativa cada 5 minutos',@enabled=1,
  @description=N'Actualiza indicadores CLEAR. dbo.FIXALARMS se utiliza solo como fuente de lectura.';
EXEC dbo.sp_add_jobstep @job_name=N'CLEAR - Caché operativa cada 5 minutos',@step_name=N'Actualizar caché',
  @subsystem=N'TSQL',@database_name=N'LC_MDB',@command=N'EXEC dbo.SP_CLEAR_ACTUALIZAR_CACHE_OPERATIVA;',@retry_attempts=2,@retry_interval=1;
/* Inicia a las 00:02 para no coincidir con el Job Top 20 que parte a las 00:00. */
EXEC dbo.sp_add_schedule @schedule_name=N'CLEAR - Caché operativa 5m',@enabled=1,@freq_type=4,@freq_interval=1,@freq_subday_type=4,@freq_subday_interval=5,@active_start_time=200;
EXEC dbo.sp_attach_schedule @job_name=N'CLEAR - Caché operativa cada 5 minutos',@schedule_name=N'CLEAR - Caché operativa 5m';
EXEC dbo.sp_add_jobserver @job_name=N'CLEAR - Caché operativa cada 5 minutos';
GO

USE [LC_MDB];
GO
SELECT METRICA,COUNT(*) FILAS,MAX(FECHA_CACHE) FECHA_CACHE
FROM dbo.CLEAR_CACHE_OPERATIVA GROUP BY METRICA ORDER BY METRICA;
GO
