USE [LC_MDB];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
PRINT '=== CLEAR - REVERSION OPTIMIZACION FASE 1 ===';

IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.FIXALARMS') AND name='IX_CLEAR_OPT_FIXALARMS_FECHA')
BEGIN
    DROP INDEX [IX_CLEAR_OPT_FIXALARMS_FECHA] ON dbo.FIXALARMS;
    PRINT 'Eliminado IX_CLEAR_OPT_FIXALARMS_FECHA';
END

IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.FIXALARMS') AND name='IX_CLEAR_OPT_FIXALARMS_TAG_FECHA')
BEGIN
    DROP INDEX [IX_CLEAR_OPT_FIXALARMS_TAG_FECHA] ON dbo.FIXALARMS;
    PRINT 'Eliminado IX_CLEAR_OPT_FIXALARMS_TAG_FECHA';
END

IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.FIXALARMS') AND name='IX_CLEAR_OPT_FIXALARMS_POZO_FECHA')
BEGIN
    DROP INDEX [IX_CLEAR_OPT_FIXALARMS_POZO_FECHA] ON dbo.FIXALARMS;
    PRINT 'Eliminado IX_CLEAR_OPT_FIXALARMS_POZO_FECHA';
END

IF OBJECT_ID('dbo.BM_RTQP','U') IS NOT NULL
AND EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.BM_RTQP') AND name='IX_CLEAR_OPT_BMRTQP_POZO_FECHA')
BEGIN
    DROP INDEX [IX_CLEAR_OPT_BMRTQP_POZO_FECHA] ON dbo.BM_RTQP;
    PRINT 'Eliminado IX_CLEAR_OPT_BMRTQP_POZO_FECHA';
END

IF OBJECT_ID('dbo.BM_RTQP','U') IS NOT NULL
AND EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.BM_RTQP') AND name='IX_CLEAR_OPT_BMRTQP_BATERIA_POZO')
BEGIN
    DROP INDEX [IX_CLEAR_OPT_BMRTQP_BATERIA_POZO] ON dbo.BM_RTQP;
    PRINT 'Eliminado IX_CLEAR_OPT_BMRTQP_BATERIA_POZO';
END

PRINT 'Reversión finalizada: ' + CONVERT(varchar(19),GETDATE(),120);
SELECT OBJECT_NAME(object_id) AS Tabla,name AS Indice
FROM sys.indexes
WHERE name LIKE 'IX_CLEAR_OPT_%';
