USE [LC_MDB];
GO

/*
   Carga histórica OPCIONAL para habilitar aproximadamente 13 semanas.
   Ejecutar una sola vez, fuera del horario pico.

   La primera instrucción usa el procedimiento protegido ya publicado, que
   limita la recarga a 120 días. La segunda resume ese caché para el módulo.
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.SP_CLEAR_ACTUALIZAR_ALARMAS_SEMANA_CACHE',N'P') IS NULL
    THROW 50010,N'No existe SP_CLEAR_ACTUALIZAR_ALARMAS_SEMANA_CACHE.',1;
GO
IF OBJECT_ID(N'dbo.SP_CLEAR_ACTUALIZAR_NOVEDADES_SEMANALES',N'P') IS NULL
    THROW 50011,N'Primero debe ejecutar CLEAR_NOVEDADES_SEMANALES.sql.',1;
GO

EXEC dbo.SP_CLEAR_ACTUALIZAR_ALARMAS_SEMANA_CACHE @DiasRecarga=90;
GO
EXEC dbo.SP_CLEAR_ACTUALIZAR_NOVEDADES_SEMANALES @SemanasRecarga=14;
GO

SELECT SEMANA_DESDE,SEMANA_HASTA,COUNT_BIG(*) AS FILAS,SUM(TOTAL_ALARMAS) AS TOTAL_ALARMAS
FROM dbo.CLEAR_NOVEDADES_SEMANALES_CACHE
GROUP BY SEMANA_DESDE,SEMANA_HASTA
ORDER BY SEMANA_DESDE DESC;
GO
