USE [LC_MDB];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

/*
  CLEAR - EXCLUSION GLOBAL DE ESTADO CFN
  Fecha: 2026-09-08

  Objetivo:
    - CFN no aparece en grillas, históricos, APIs, reportes ni estadísticas.
    - CFN no participa en los cachés de Top 20, telemetría ni novedades.
    - dbo.FIXALARMS permanece como fuente SCADA de solo lectura.

  IMPORTANTE:
    Ejecutar una sola vez, preferentemente fuera del horario de mayor uso,
    porque al final se reconstruyen hasta 120 días de resúmenes semanales.
*/

IF OBJECT_ID(N'dbo.FIXALARMS',N'U') IS NULL
    THROW 51000, N'No existe dbo.FIXALARMS en LC_MDB.', 1;

IF COL_LENGTH(N'dbo.FIXALARMS',N'ALM_ALMSTATUS') IS NULL
    THROW 51001, N'No existe dbo.FIXALARMS.ALM_ALMSTATUS.', 1;
GO

IF OBJECT_ID(N'dbo.CLEAR_ALARM_FILTERS',N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CLEAR_ALARM_FILTERS
    (
        ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CLEAR_ALARM_FILTERS PRIMARY KEY,
        CAMPO NVARCHAR(20) NOT NULL CONSTRAINT DF_CLEAR_ALARM_FILTERS_CAMPO DEFAULT N'AMBOS',
        MODO NVARCHAR(20) NOT NULL CONSTRAINT DF_CLEAR_ALARM_FILTERS_MODO DEFAULT N'CONTIENE',
        VALOR NVARCHAR(500) NOT NULL,
        ACTIVO BIT NOT NULL CONSTRAINT DF_CLEAR_ALARM_FILTERS_ACTIVO DEFAULT (1),
        FECHA_ALTA DATETIME2(0) NOT NULL CONSTRAINT DF_CLEAR_ALARM_FILTERS_FECHA DEFAULT SYSDATETIME(),
        USUARIO_ALTA NVARCHAR(128) NULL
    );
END;
GO

/* Vista central: todas las consultas web a FIXALARMS se redirigen aquí. */
EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS AS
SELECT A.*
FROM dbo.FIXALARMS AS A
WHERE (A.ALM_ALMSTATUS IS NULL OR A.ALM_ALMSTATUS<>N''CFN'')
  AND NOT EXISTS
  (
      SELECT 1
      FROM dbo.CLEAR_ALARM_FILTERS AS F
      WHERE F.ACTIVO=1
        AND
        (
            (F.CAMPO IN (N''TAG'',N''AMBOS'') AND
             ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_TAGNAME)))=F.VALOR)
              OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) LIKE F.VALOR+N''%'')
              OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) LIKE N''%''+F.VALOR+N''%'')))
            OR
            (F.CAMPO IN (N''DESCRIPCION'',N''AMBOS'') AND
             ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_DESCR)))=F.VALOR)
              OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE F.VALOR+N''%'')
              OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE N''%''+F.VALOR+N''%'')))
        )
  )');
GO

IF OBJECT_ID(N'dbo.FIXALARMS_24H') IS NOT NULL
BEGIN
    EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS_24H AS
    SELECT A.*
    FROM dbo.FIXALARMS_24H AS A
    WHERE (A.ALM_ALMSTATUS IS NULL OR A.ALM_ALMSTATUS<>N''CFN'')
      AND NOT EXISTS
      (
          SELECT 1 FROM dbo.CLEAR_ALARM_FILTERS AS F
          WHERE F.ACTIVO=1 AND
          (
              (F.CAMPO IN (N''TAG'',N''AMBOS'') AND
               ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_TAGNAME)))=F.VALOR)
                OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) LIKE F.VALOR+N''%'')
                OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) LIKE N''%''+F.VALOR+N''%'')))
              OR
              (F.CAMPO IN (N''DESCRIPCION'',N''AMBOS'') AND
               ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_DESCR)))=F.VALOR)
                OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE F.VALOR+N''%'')
                OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE N''%''+F.VALOR+N''%'')))
          )
      )');
END;
GO

IF OBJECT_ID(N'dbo.FIXALARMS_ONLY') IS NOT NULL
BEGIN
    EXEC(N'CREATE OR ALTER VIEW dbo.CLEAR_F_FIXALARMS_ONLY AS
    SELECT A.*
    FROM dbo.FIXALARMS_ONLY AS A
    WHERE (A.ALM_ALMSTATUS IS NULL OR A.ALM_ALMSTATUS<>N''CFN'')
      AND NOT EXISTS
      (
          SELECT 1 FROM dbo.CLEAR_ALARM_FILTERS AS F
          WHERE F.ACTIVO=1 AND
          (
              (F.CAMPO IN (N''TAG'',N''AMBOS'') AND
               ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_TAGNAME)))=F.VALOR)
                OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) LIKE F.VALOR+N''%'')
                OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) LIKE N''%''+F.VALOR+N''%'')))
              OR
              (F.CAMPO IN (N''DESCRIPCION'',N''AMBOS'') AND
               ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_DESCR)))=F.VALOR)
                OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE F.VALOR+N''%'')
                OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE N''%''+F.VALOR+N''%'')))
          )
      )');
END;
GO

/* El Top 20 se recompone directamente desde FIXALARMS, por eso el filtro
   se aplica también dentro del procedimiento programado. */
CREATE OR ALTER PROCEDURE dbo.SP_CLEAR_ACTUALIZAR_CACHE_TOP20_24H
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    IF OBJECT_ID(N'dbo.CLEAR_CACHE_TOP20_24H',N'U') IS NULL RETURN;

    CREATE TABLE #NUEVOS_DATOS
    (
        ALM_TAGNAME NVARCHAR(500) NOT NULL,
        DESCRIPCION NVARCHAR(1000) NULL,
        TOTAL_ALARMAS BIGINT NOT NULL,
        ALM_ALMEXTFLD2 NVARCHAR(500) NULL,
        ULTIMA_APARICION DATETIME2(3) NULL
    );

    INSERT INTO #NUEVOS_DATOS
        (ALM_TAGNAME,DESCRIPCION,TOTAL_ALARMAS,ALM_ALMEXTFLD2,ULTIMA_APARICION)
    SELECT
        LTRIM(RTRIM(CONVERT(nvarchar(500),A.ALM_TAGNAME))),
        MAX(COALESCE(
            NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_DESCR))),N''),
            NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_TAGDESC))),N'')
        )),
        COUNT_BIG(*),
        MAX(NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(500),A.ALM_ALMEXTFLD2))),N'')),
        MAX(CONVERT(datetime2(3),A.ALM_NATIVETIMEIN))
    FROM dbo.FIXALARMS AS A
    WHERE A.ALM_NATIVETIMEIN>=DATEADD(hour,-24,SYSDATETIME())
      AND (A.ALM_ALMSTATUS IS NULL OR A.ALM_ALMSTATUS<>N'CFN')
      AND NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(500),A.ALM_TAGNAME))),N'') IS NOT NULL
      AND NOT EXISTS
      (
          SELECT 1 FROM dbo.CLEAR_ALARM_FILTERS AS F
          WHERE F.ACTIVO=1 AND
          (
              (F.CAMPO IN (N'TAG',N'AMBOS') AND
               ((F.MODO=N'EXACTO' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_TAGNAME)))=F.VALOR)
                OR (F.MODO=N'COMIENZA' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) LIKE F.VALOR+N'%')
                OR (F.MODO=N'CONTIENE' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) LIKE N'%'+F.VALOR+N'%')))
              OR
              (F.CAMPO IN (N'DESCRIPCION',N'AMBOS') AND
               ((F.MODO=N'EXACTO' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_DESCR)))=F.VALOR)
                OR (F.MODO=N'COMIENZA' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE F.VALOR+N'%')
                OR (F.MODO=N'CONTIENE' AND CONVERT(nvarchar(1000),A.ALM_DESCR) LIKE N'%'+F.VALOR+N'%')))
          )
      )
    GROUP BY LTRIM(RTRIM(CONVERT(nvarchar(500),A.ALM_TAGNAME)));

    BEGIN TRY
        BEGIN TRANSACTION;
            TRUNCATE TABLE dbo.CLEAR_CACHE_TOP20_24H;
            INSERT dbo.CLEAR_CACHE_TOP20_24H
                (ALM_TAGNAME,DESCRIPCION,TOTAL_ALARMAS,ALM_ALMEXTFLD2,ULTIMA_APARICION,FECHA_ACTUALIZACION)
            SELECT ALM_TAGNAME,DESCRIPCION,TOTAL_ALARMAS,ALM_ALMEXTFLD2,ULTIMA_APARICION,SYSDATETIME()
            FROM #NUEVOS_DATOS;
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT>0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH;
END;
GO

/* La grilla general de pozos guarda un conteo ALM de las últimas 24 horas. */
CREATE OR ALTER PROCEDURE dbo.SP_ACTUALIZAR_TELEMETRIA_POZOS_GENERAL_CACHE
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET DEADLOCK_PRIORITY LOW;
    SET LOCK_TIMEOUT 15000;

    IF OBJECT_ID(N'dbo.TELEMETRIA_POZOS_GENERAL_CACHE',N'U') IS NULL RETURN;
    IF OBJECT_ID(N'dbo.VW_TELEMETRIA_POZOS_GENERAL') IS NULL RETURN;

    DECLARE @Ahora datetime2(0)=SYSDATETIME();
    DECLARE @LockResult int;

    EXEC @LockResult=sys.sp_getapplock
        @Resource=N'CLEAR_TELEMETRIA_POZOS_GENERAL_CACHE',
        @LockMode=N'Exclusive',@LockOwner=N'Session',@LockTimeout=0;

    IF @LockResult<0 RETURN;

    BEGIN TRY
        CREATE TABLE #Alarmas24h
        (
            POZO nvarchar(255) NOT NULL PRIMARY KEY,
            TOTAL bigint NOT NULL
        );

        INSERT #Alarmas24h(POZO,TOTAL)
        SELECT
            UPPER(LTRIM(RTRIM(CONVERT(nvarchar(255),A.ALM_ALMEXTFLD2)))),
            COUNT_BIG(*)
        FROM dbo.FIXALARMS AS A
        WHERE A.ALM_NATIVETIMEIN>=DATEADD(hour,-24,@Ahora)
          AND (A.ALM_ALMSTATUS IS NULL OR A.ALM_ALMSTATUS<>N'CFN')
          AND A.ALM_ALMEXTFLD2 IS NOT NULL
          AND A.ALM_ALMEXTFLD2<>N''
        GROUP BY UPPER(LTRIM(RTRIM(CONVERT(nvarchar(255),A.ALM_ALMEXTFLD2))))
        OPTION (MAXDOP 1,RECOMPILE);

        CREATE TABLE #CacheNueva
        (
            POZO nvarchar(255) NOT NULL,
            BATERIA nvarchar(255) NULL,
            TIPO nvarchar(20) NOT NULL,
            ALM int NOT NULL,
            COMUNICACION nvarchar(255) NULL,
            ESTADO nvarchar(255) NULL,
            PANTALLA nvarchar(1000) NULL,
            ULTIMA_ACTUALIZACION datetime2(0) NULL,
            FECHA_CACHE datetime2(0) NOT NULL
        );

        INSERT #CacheNueva
            (POZO,BATERIA,TIPO,ALM,COMUNICACION,ESTADO,PANTALLA,ULTIMA_ACTUALIZACION,FECHA_CACHE)
        SELECT
            V.POZO,V.BATERIA,V.TIPO,CONVERT(int,ISNULL(A.TOTAL,0)),
            V.COMUNICACION,V.ESTADO,V.PANTALLA,V.ULTIMA_ACTUALIZACION,@Ahora
        FROM dbo.VW_TELEMETRIA_POZOS_GENERAL AS V
        LEFT JOIN #Alarmas24h AS A
          ON A.POZO=UPPER(LTRIM(RTRIM(V.POZO)))
        WHERE V.POZO IS NOT NULL AND V.POZO<>N''
        OPTION (MAXDOP 1);

        BEGIN TRANSACTION;
            TRUNCATE TABLE dbo.TELEMETRIA_POZOS_GENERAL_CACHE;
            INSERT dbo.TELEMETRIA_POZOS_GENERAL_CACHE
                (POZO,BATERIA,TIPO,ALM,COMUNICACION,ESTADO,PANTALLA,ULTIMA_ACTUALIZACION,FECHA_CACHE)
            SELECT POZO,BATERIA,TIPO,ALM,COMUNICACION,ESTADO,PANTALLA,ULTIMA_ACTUALIZACION,FECHA_CACHE
            FROM #CacheNueva;
        COMMIT TRANSACTION;

        EXEC sys.sp_releaseapplock
            @Resource=N'CLEAR_TELEMETRIA_POZOS_GENERAL_CACHE',@LockOwner=N'Session';
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT>0 ROLLBACK TRANSACTION;
        EXEC sys.sp_releaseapplock
            @Resource=N'CLEAR_TELEMETRIA_POZOS_GENERAL_CACHE',@LockOwner=N'Session';
        THROW;
    END CATCH;
END;
GO

/* Reconstrucción de cachés. Nunca se escribe en dbo.FIXALARMS. */
IF OBJECT_ID(N'dbo.SP_CLEAR_ACTUALIZAR_CACHE_OPERATIVA',N'P') IS NOT NULL
    EXEC dbo.SP_CLEAR_ACTUALIZAR_CACHE_OPERATIVA;
GO

IF OBJECT_ID(N'dbo.CLEAR_CACHE_TOP20_24H',N'U') IS NOT NULL
    EXEC dbo.SP_CLEAR_ACTUALIZAR_CACHE_TOP20_24H;
GO

IF OBJECT_ID(N'dbo.TELEMETRIA_POZOS_GENERAL_CACHE',N'U') IS NOT NULL
    EXEC dbo.SP_ACTUALIZAR_TELEMETRIA_POZOS_GENERAL_CACHE;
GO

/* La caché semanal no conserva Estado; debe reconstruirse para retirar los
   conteos CFN históricos. Las pantallas permiten 16 semanas (menos de 120 días). */
IF OBJECT_ID(N'dbo.CLEAR_ALARMAS_SEMANA_CACHE',N'U') IS NOT NULL
   AND OBJECT_ID(N'dbo.SP_CLEAR_ACTUALIZAR_ALARMAS_SEMANA_CACHE',N'P') IS NOT NULL
BEGIN
    TRUNCATE TABLE dbo.CLEAR_ALARMAS_SEMANA_CACHE;
    EXEC dbo.SP_CLEAR_ACTUALIZAR_ALARMAS_SEMANA_CACHE @DiasRecarga=120;
END;
GO

IF OBJECT_ID(N'dbo.CLEAR_NOVEDADES_SEMANALES_CACHE',N'U') IS NOT NULL
   AND OBJECT_ID(N'dbo.SP_CLEAR_ACTUALIZAR_NOVEDADES_SEMANALES',N'P') IS NOT NULL
BEGIN
    TRUNCATE TABLE dbo.CLEAR_NOVEDADES_SEMANALES_CACHE;
    EXEC dbo.SP_CLEAR_ACTUALIZAR_NOVEDADES_SEMANALES @SemanasRecarga=16;
END;
GO

/* Verificación final. RESULTADO debe ser 0. */
SELECT N'CFN visibles en CLEAR_F_FIXALARMS' AS CONTROL,COUNT_BIG(*) AS RESULTADO
FROM dbo.CLEAR_F_FIXALARMS
WHERE ALM_NATIVETIMEIN>=DATEADD(hour,-24,SYSDATETIME())
  AND ISNULL(UPPER(LTRIM(RTRIM(CONVERT(nvarchar(100),ALM_ALMSTATUS)))),N'')=N'CFN';

IF OBJECT_ID(N'dbo.CLEAR_F_FIXALARMS_24H',N'V') IS NOT NULL
    EXEC(N'SELECT N''CFN visibles en CLEAR_F_FIXALARMS_24H'' AS CONTROL,COUNT_BIG(*) AS RESULTADO FROM dbo.CLEAR_F_FIXALARMS_24H WHERE ISNULL(UPPER(LTRIM(RTRIM(CONVERT(nvarchar(100),ALM_ALMSTATUS)))),N'''')=N''CFN'';');

IF OBJECT_ID(N'dbo.CLEAR_CACHE_OPERATIVA',N'U') IS NOT NULL
    SELECT N'CFN visibles en CLEAR_CACHE_OPERATIVA' AS CONTROL,COUNT_BIG(*) AS RESULTADO
    FROM dbo.CLEAR_CACHE_OPERATIVA
    WHERE UPPER(LTRIM(RTRIM(ISNULL(DIMENSION1,N''))))=N'CFN';
GO

PRINT N'Actualización completada. Todos los controles RESULTADO deben indicar 0.';
PRINT N'dbo.FIXALARMS no fue modificada; Alarm ODBC continúa registrando normalmente.';
GO
