/* CLEAR · Novedades semanales v2
   Actualización incremental para instalaciones v1/v1.1 existentes.
   No modifica FIXALARMS ni las pantallas publicadas. */
USE [LC_MDB];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.CLEAR_NOVEDADES_SEMANALES_REPORTE_ITEMS',N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CLEAR_NOVEDADES_SEMANALES_REPORTE_ITEMS
    (
        ID           bigint IDENTITY(1,1) NOT NULL,
        USUARIO      nvarchar(128) COLLATE DATABASE_DEFAULT NOT NULL,
        ITEM_KEY     nvarchar(120) COLLATE DATABASE_DEFAULT NOT NULL,
        ITEM_TIPO    nvarchar(30) COLLATE DATABASE_DEFAULT NOT NULL,
        TITULO       nvarchar(255) COLLATE DATABASE_DEFAULT NOT NULL,
        PAYLOAD_JSON nvarchar(max) COLLATE DATABASE_DEFAULT NOT NULL,
        ACTIVO       bit NOT NULL CONSTRAINT DF_CLEAR_NS_REP_ACTIVO DEFAULT(1),
        FECHA_CARGA  datetime2(0) NOT NULL CONSTRAINT DF_CLEAR_NS_REP_FECHA DEFAULT(SYSDATETIME()),
        FECHA_CAMBIO datetime2(0) NULL,
        CONSTRAINT PK_CLEAR_NS_REPORTE_ITEMS PRIMARY KEY CLUSTERED(ID)
    );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.CLEAR_NOVEDADES_SEMANALES_REPORTE_ITEMS') AND name=N'UX_CLEAR_NS_REP_USUARIO_ITEM')
    CREATE UNIQUE INDEX UX_CLEAR_NS_REP_USUARIO_ITEM ON dbo.CLEAR_NOVEDADES_SEMANALES_REPORTE_ITEMS(USUARIO,ITEM_KEY);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.CLEAR_NOVEDADES_SEMANALES_REPORTE_ITEMS') AND name=N'IX_CLEAR_NS_REP_USUARIO_ACTIVO')
    CREATE INDEX IX_CLEAR_NS_REP_USUARIO_ACTIVO ON dbo.CLEAR_NOVEDADES_SEMANALES_REPORTE_ITEMS(USUARIO,ACTIVO,FECHA_CARGA) INCLUDE(ITEM_KEY,ITEM_TIPO,TITULO,FECHA_CAMBIO);
GO

IF OBJECT_ID(N'dbo.FIXALARMS_COMENTARIOS',N'U') IS NOT NULL
BEGIN
    DECLARE @ReportGrants nvarchar(max)=N'';
    SELECT @ReportGrants=@ReportGrants+N'GRANT '+P.permission_name+N' ON OBJECT::dbo.CLEAR_NOVEDADES_SEMANALES_REPORTE_ITEMS TO '+QUOTENAME(USER_NAME(P.grantee_principal_id))+N';'+CHAR(13)
    FROM sys.database_permissions P
    WHERE P.class=1 AND P.major_id=OBJECT_ID(N'dbo.FIXALARMS_COMENTARIOS') AND P.state IN(N'G',N'W') AND P.permission_name IN(N'SELECT',N'INSERT',N'UPDATE');
    IF @ReportGrants<>N'' EXEC sys.sp_executesql @ReportGrants;
END;
GO

SELECT N'Novedades semanales v2 instalada' AS RESULTADO,COUNT_BIG(*) AS ELEMENTOS_REPORTE
FROM dbo.CLEAR_NOVEDADES_SEMANALES_REPORTE_ITEMS;
GO
PRINT N'La caché, el histórico y FIXALARMS no fueron modificados.';
GO
