USE [LC_MDB];
GO

/* ============================================================
   CLEAR - MICROS CONTABLES v1.3

   Reejecutable y aditivo.
   - Corrige PLC001 como texto en MASICOS_SC y su histórico.
   - Conserva la fotografía diaria de las 09:00.
   - Crea el maestro editable de Micros contables.
   - Completa responsables desde CLEAR_SUPERVISORES_INSTALACIONES.
   - No consulta RTQP_IUP desde la pantalla web.
============================================================ */
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.CLEAR_SUPERVISORES_INSTALACIONES', N'U') IS NULL
    THROW 51020, N'Falta dbo.CLEAR_SUPERVISORES_INSTALACIONES. Ejecute primero SQL/CLEAR_SUPERVISORES_INSTALACIONES.sql.', 1;
GO

/* 1. Vista másica corregida: PLC001 es texto (ej.: NORMAL). */
CREATE OR ALTER VIEW dbo.MASICOS_SC
AS
SELECT
    CONVERT(nvarchar(255), q.Name) COLLATE DATABASE_DEFAULT AS [Name],
    CONVERT(nvarchar(255), q.NOMBRE_INATALACION) COLLATE DATABASE_DEFAULT AS NOMBRE_INSTALACION,
    CONVERT(nvarchar(100), q.BATERIA) COLLATE DATABASE_DEFAULT AS BATERIA,
    TRY_CONVERT(decimal(18,3), q.FT001) AS FT001,
    TRY_CONVERT(decimal(18,3), q.[ACUM. BRUTA]) AS ACUM_BRUTA,
    TRY_CONVERT(decimal(18,3), q.[PROY. BRUTA]) AS PROY_BRUTA,
    TRY_CONVERT(decimal(18,3), q.[CAUDAL INSTANT.]) AS CAUDAL_INSTANTANEO,
    TRY_CONVERT(decimal(18,3), q.[PROY. NETA]) AS PROY_NETA,
    TRY_CONVERT(decimal(18,3), q.[ACUM. NETA]) AS ACUM_NETA,
    TRY_CONVERT(decimal(18,3), q.LT001) AS LT001,
    TRY_CONVERT(decimal(18,3), q.FQYBrutaProm7) AS PROMEDIO_BRUTA_7_DIAS,
    CONVERT(nvarchar(100), q.PLC001) COLLATE DATABASE_DEFAULT AS PLC001
FROM OPENQUERY
(
    [RTQP_IUP],
    '
    SELECT
        Name,
        NOMBRE_INATALACION,
        BATERIA,
        FT001,
        [ACUM. BRUTA],
        [PROY. BRUTA],
        [CAUDAL INSTANT.],
        [PROY. NETA],
        [ACUM. NETA],
        LT001,
        FQYBrutaProm7,
        PLC001
    FROM [IUP].[pozos_IUP].[BATERIA SC]
    '
) AS q;
GO

/* 2. Histórico diario. Se conserva si ya fue creado. */
IF OBJECT_ID(N'dbo.MASICOS_SC_HISTORICO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.MASICOS_SC_HISTORICO
    (
        ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_MASICOS_SC_HISTORICO PRIMARY KEY,
        FECHA_DATO DATE NOT NULL,
        FECHA_INSERCION DATETIME2(0) NOT NULL,
        [Name] NVARCHAR(255) COLLATE DATABASE_DEFAULT NULL,
        NOMBRE_INSTALACION NVARCHAR(255) COLLATE DATABASE_DEFAULT NULL,
        BATERIA NVARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
        FT001 DECIMAL(18,3) NULL,
        ACUM_BRUTA DECIMAL(18,3) NULL,
        PROY_BRUTA DECIMAL(18,3) NULL,
        CAUDAL_INSTANTANEO DECIMAL(18,3) NULL,
        PROY_NETA DECIMAL(18,3) NULL,
        ACUM_NETA DECIMAL(18,3) NULL,
        LT001 DECIMAL(18,3) NULL,
        PROMEDIO_BRUTA_7_DIAS DECIMAL(18,3) NULL,
        PLC001 NVARCHAR(100) COLLATE DATABASE_DEFAULT NULL
    );
END;
GO

IF COL_LENGTH(N'dbo.MASICOS_SC_HISTORICO', N'PLC001') IS NULL
    ALTER TABLE dbo.MASICOS_SC_HISTORICO ADD PLC001 NVARCHAR(100) COLLATE DATABASE_DEFAULT NULL;
GO

IF EXISTS
(
    SELECT 1
    FROM sys.columns c
    JOIN sys.types t ON t.user_type_id=c.user_type_id
    WHERE c.object_id=OBJECT_ID(N'dbo.MASICOS_SC_HISTORICO')
      AND c.name=N'PLC001'
      AND t.name NOT IN (N'nvarchar',N'varchar',N'nchar',N'char')
)
    ALTER TABLE dbo.MASICOS_SC_HISTORICO ALTER COLUMN PLC001 NVARCHAR(100) COLLATE DATABASE_DEFAULT NULL;
GO

IF NOT EXISTS
(
    SELECT 1 FROM sys.indexes
    WHERE object_id=OBJECT_ID(N'dbo.MASICOS_SC_HISTORICO')
      AND name=N'IX_MASICOS_SC_HISTORICO_FECHA'
)
CREATE INDEX IX_MASICOS_SC_HISTORICO_FECHA
        ON dbo.MASICOS_SC_HISTORICO(FECHA_DATO,BATERIA,[Name]);
GO

/* Normalización común de baterías.
   @EsMasico=1 elimina el prefijo técnico B:
   BCE008 -> CE8, BBB002 -> BB2, BCG005 -> CG5.
   @EsMasico=0 conserva el código maestro:
   CE 08 -> CE8, BB 02 -> BB2, CG 05 -> CG5. */
CREATE OR ALTER FUNCTION dbo.FN_CLEAR_NORMALIZAR_BATERIA
(
    @Valor NVARCHAR(255),
    @EsMasico BIT
)
RETURNS NVARCHAR(255)
AS
BEGIN
    DECLARE @Clave NVARCHAR(255)=UPPER(LTRIM(RTRIM(ISNULL(@Valor,N''))));
    SET @Clave=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(@Clave,N' ',N''),N'-',N''),N'_',N''),N'.',N''),N'/',N'');

    IF @EsMasico=1 AND LEN(@Clave)>1 AND LEFT(@Clave,1)=N'B'
        SET @Clave=SUBSTRING(@Clave,2,255);

    DECLARE @PosNumero INT=PATINDEX(N'%[0-9]%',@Clave);
    IF @PosNumero>1
    BEGIN
        DECLARE @Prefijo NVARCHAR(100)=LEFT(@Clave,@PosNumero-1);
        DECLARE @NumeroTexto NVARCHAR(100)=SUBSTRING(@Clave,@PosNumero,100);
        DECLARE @Numero BIGINT=TRY_CONVERT(BIGINT,@NumeroTexto);
        IF @Numero IS NOT NULL SET @Clave=@Prefijo+CONVERT(NVARCHAR(30),@Numero);
    END;

    RETURN @Clave;
END;
GO

/* Fuente de solo lectura para la segunda grilla y el autocompletado. */
CREATE OR ALTER VIEW dbo.CLEAR_VW_MASICOS_DIARIOS
AS
SELECT
    H.ID,
    H.FECHA_DATO,
    H.FECHA_INSERCION,
    H.[Name],
    H.NOMBRE_INSTALACION,
    H.BATERIA,
    dbo.FN_CLEAR_NORMALIZAR_BATERIA(H.BATERIA,1) AS BATERIA_CLAVE,
    S.BATERIA AS BATERIA_MAESTRO,
    S.ZONA,
    S.SUPERVISOR,
    S.JEFE_ZONA,
    H.FT001,H.ACUM_BRUTA,H.PROY_BRUTA,H.CAUDAL_INSTANTANEO,
    H.PROY_NETA,H.ACUM_NETA,H.LT001,H.PROMEDIO_BRUTA_7_DIAS,H.PLC001
FROM dbo.MASICOS_SC_HISTORICO H
OUTER APPLY
(
    SELECT TOP (1) X.BATERIA,X.ZONA,X.SUPERVISOR,X.JEFE_ZONA
    FROM dbo.CLEAR_SUPERVISORES_INSTALACIONES X
    WHERE X.ACTIVO=1
      AND dbo.FN_CLEAR_NORMALIZAR_BATERIA(X.BATERIA,0)=dbo.FN_CLEAR_NORMALIZAR_BATERIA(H.BATERIA,1)
    ORDER BY X.ID
) S;
GO

/* 3. Tabla web editable. Los datos automáticos quedan identificados. */
IF OBJECT_ID(N'dbo.CLEAR_MICROS_CONTABLES', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CLEAR_MICROS_CONTABLES
    (
        ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CLEAR_MICROS_CONTABLES PRIMARY KEY,
        MASICO_HISTORICO_ID BIGINT NULL,
        ORIGEN NVARCHAR(20) NOT NULL CONSTRAINT DF_CLEAR_MICROS_ORIGEN DEFAULT N'MANUAL',
        EDITADO_MANUAL BIT NOT NULL CONSTRAINT DF_CLEAR_MICROS_EDITADO DEFAULT 0,
        FECHA_DATO DATE NOT NULL,
        FECHA_INSERCION_MASICO DATETIME2(0) NULL,
        [Name] NVARCHAR(255) COLLATE DATABASE_DEFAULT NULL,
        NOMBRE_INSTALACION NVARCHAR(255) COLLATE DATABASE_DEFAULT NULL,
        BATERIA NVARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
        ZONA NVARCHAR(150) COLLATE DATABASE_DEFAULT NULL,
        MODALIDAD NVARCHAR(30) COLLATE DATABASE_DEFAULT NOT NULL CONSTRAINT DF_CLEAR_MICROS_MODALIDAD DEFAULT N'SIN DEFINIR',
        FT001 DECIMAL(18,3) NULL,
        ACUM_BRUTA DECIMAL(18,3) NULL,
        PROY_BRUTA DECIMAL(18,3) NULL,
        CAUDAL_INSTANTANEO DECIMAL(18,3) NULL,
        PROY_NETA DECIMAL(18,3) NULL,
        ACUM_NETA DECIMAL(18,3) NULL,
        LT001 DECIMAL(18,3) NULL,
        PROMEDIO_BRUTA_7_DIAS DECIMAL(18,3) NULL,
        PLC001 NVARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
        SUPERVISOR NVARCHAR(200) COLLATE DATABASE_DEFAULT NULL,
        JEFE_ZONA NVARCHAR(200) COLLATE DATABASE_DEFAULT NULL,
        OBSERVACION NVARCHAR(2000) COLLATE DATABASE_DEFAULT NULL,
        ACTIVO BIT NOT NULL CONSTRAINT DF_CLEAR_MICROS_ACTIVO DEFAULT 1,
        FECHA_ALTA DATETIME2(0) NOT NULL CONSTRAINT DF_CLEAR_MICROS_ALTA DEFAULT SYSDATETIME(),
        USUARIO_ALTA NVARCHAR(128) COLLATE DATABASE_DEFAULT NULL,
        FECHA_MODIFICACION DATETIME2(0) NOT NULL CONSTRAINT DF_CLEAR_MICROS_MOD DEFAULT SYSDATETIME(),
        USUARIO_MODIFICACION NVARCHAR(128) COLLATE DATABASE_DEFAULT NULL
    );
END;
GO

IF NOT EXISTS
(
    SELECT 1 FROM sys.indexes
    WHERE object_id=OBJECT_ID(N'dbo.CLEAR_MICROS_CONTABLES')
      AND name=N'IX_CLEAR_MICROS_FECHA'
)
    CREATE INDEX IX_CLEAR_MICROS_FECHA
        ON dbo.CLEAR_MICROS_CONTABLES(FECHA_DATO,ZONA,BATERIA)
        INCLUDE(MODALIDAD,SUPERVISOR,JEFE_ZONA,ACUM_BRUTA,PROY_BRUTA,ACTIVO);
GO

/* 4. Sincroniza históricos sin pisar filas ya editadas por un usuario. */
CREATE OR ALTER PROCEDURE dbo.SP_CLEAR_SINCRONIZAR_MICROS_CONTABLES
    @FechaDesde DATE = NULL,
    @FechaHasta DATE = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    IF @FechaDesde IS NULL SET @FechaDesde=(SELECT MIN(FECHA_DATO) FROM dbo.MASICOS_SC_HISTORICO);
    IF @FechaHasta IS NULL SET @FechaHasta=(SELECT MAX(FECHA_DATO) FROM dbo.MASICOS_SC_HISTORICO);
    IF @FechaDesde IS NULL OR @FechaHasta IS NULL RETURN;

    ;WITH FUENTE AS
    (
        SELECT
            H.*,
            S.ZONA AS ZONA_AUTO,
            S.SUPERVISOR AS SUPERVISOR_AUTO,
            S.JEFE_ZONA AS JEFE_AUTO
        FROM dbo.MASICOS_SC_HISTORICO H
        OUTER APPLY
        (
            SELECT TOP (1) X.ZONA,X.SUPERVISOR,X.JEFE_ZONA
            FROM dbo.CLEAR_SUPERVISORES_INSTALACIONES X
            WHERE X.ACTIVO=1
              AND dbo.FN_CLEAR_NORMALIZAR_BATERIA(X.BATERIA,0)=dbo.FN_CLEAR_NORMALIZAR_BATERIA(H.BATERIA,1)
            ORDER BY X.ID
        ) S
        WHERE H.FECHA_DATO BETWEEN @FechaDesde AND @FechaHasta
    )
    MERGE dbo.CLEAR_MICROS_CONTABLES AS T
    USING FUENTE AS S
       ON T.ORIGEN=N'MASICOS'
      AND T.FECHA_DATO=S.FECHA_DATO
      AND ISNULL(T.[Name],N'')=ISNULL(S.[Name],N'') COLLATE DATABASE_DEFAULT
      AND ISNULL(T.BATERIA,N'')=ISNULL(S.BATERIA,N'') COLLATE DATABASE_DEFAULT
    WHEN MATCHED THEN
        UPDATE SET
            T.MASICO_HISTORICO_ID=S.ID,
            T.FECHA_INSERCION_MASICO=S.FECHA_INSERCION,
            T.NOMBRE_INSTALACION=CASE WHEN T.EDITADO_MANUAL=0 THEN S.NOMBRE_INSTALACION ELSE T.NOMBRE_INSTALACION END,
            T.BATERIA=CASE WHEN T.EDITADO_MANUAL=0 THEN S.BATERIA ELSE T.BATERIA END,
            T.ZONA=CASE WHEN T.EDITADO_MANUAL=0 THEN S.ZONA_AUTO ELSE T.ZONA END,
            T.MODALIDAD=CASE
                WHEN T.EDITADO_MANUAL=1 THEN T.MODALIDAD
                WHEN ABS(ISNULL(S.FT001,0))>0 THEN N'POR MEDIDOR'
                ELSE N'PRODUCCION TEORICA'
            END,
            T.FT001=CASE WHEN T.EDITADO_MANUAL=0 THEN S.FT001 ELSE T.FT001 END,
            T.ACUM_BRUTA=CASE WHEN T.EDITADO_MANUAL=0 THEN S.ACUM_BRUTA ELSE T.ACUM_BRUTA END,
            T.PROY_BRUTA=CASE WHEN T.EDITADO_MANUAL=0 THEN S.PROY_BRUTA ELSE T.PROY_BRUTA END,
            T.CAUDAL_INSTANTANEO=CASE WHEN T.EDITADO_MANUAL=0 THEN S.CAUDAL_INSTANTANEO ELSE T.CAUDAL_INSTANTANEO END,
            T.PROY_NETA=CASE WHEN T.EDITADO_MANUAL=0 THEN S.PROY_NETA ELSE T.PROY_NETA END,
            T.ACUM_NETA=CASE WHEN T.EDITADO_MANUAL=0 THEN S.ACUM_NETA ELSE T.ACUM_NETA END,
            T.LT001=CASE WHEN T.EDITADO_MANUAL=0 THEN S.LT001 ELSE T.LT001 END,
            T.PROMEDIO_BRUTA_7_DIAS=CASE WHEN T.EDITADO_MANUAL=0 THEN S.PROMEDIO_BRUTA_7_DIAS ELSE T.PROMEDIO_BRUTA_7_DIAS END,
            T.PLC001=CASE WHEN T.EDITADO_MANUAL=0 THEN S.PLC001 ELSE T.PLC001 END,
            T.SUPERVISOR=CASE WHEN T.EDITADO_MANUAL=0 THEN S.SUPERVISOR_AUTO ELSE T.SUPERVISOR END,
            T.JEFE_ZONA=CASE WHEN T.EDITADO_MANUAL=0 THEN S.JEFE_AUTO ELSE T.JEFE_ZONA END,
            T.ACTIVO=CASE WHEN T.EDITADO_MANUAL=0 THEN 1 ELSE T.ACTIVO END,
            T.FECHA_MODIFICACION=CASE WHEN T.EDITADO_MANUAL=0 THEN SYSDATETIME() ELSE T.FECHA_MODIFICACION END,
            T.USUARIO_MODIFICACION=CASE WHEN T.EDITADO_MANUAL=0 THEN N'SISTEMA' ELSE T.USUARIO_MODIFICACION END
    WHEN NOT MATCHED THEN
        INSERT
        (
            MASICO_HISTORICO_ID,ORIGEN,EDITADO_MANUAL,FECHA_DATO,FECHA_INSERCION_MASICO,
            [Name],NOMBRE_INSTALACION,BATERIA,ZONA,MODALIDAD,FT001,ACUM_BRUTA,PROY_BRUTA,
            CAUDAL_INSTANTANEO,PROY_NETA,ACUM_NETA,LT001,PROMEDIO_BRUTA_7_DIAS,PLC001,
            SUPERVISOR,JEFE_ZONA,ACTIVO,USUARIO_ALTA,USUARIO_MODIFICACION
        )
        VALUES
        (
            S.ID,N'MASICOS',0,S.FECHA_DATO,S.FECHA_INSERCION,S.[Name],S.NOMBRE_INSTALACION,
            S.BATERIA,S.ZONA_AUTO,
            CASE WHEN ABS(ISNULL(S.FT001,0))>0 THEN N'POR MEDIDOR' ELSE N'PRODUCCION TEORICA' END,
            S.FT001,S.ACUM_BRUTA,S.PROY_BRUTA,S.CAUDAL_INSTANTANEO,S.PROY_NETA,S.ACUM_NETA,
            S.LT001,S.PROMEDIO_BRUTA_7_DIAS,S.PLC001,S.SUPERVISOR_AUTO,S.JEFE_AUTO,
            1,N'SISTEMA',N'SISTEMA'
        );
END;
GO

/* 5. Carga diaria corregida y sincronización automática. */
CREATE OR ALTER PROCEDURE dbo.SP_CARGAR_MASICOS_SC_DIARIO
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @FechaInsercion DATETIME2(0)=SYSDATETIME();
    DECLARE @FechaDato DATE=CONVERT(date,@FechaInsercion);
    DECLARE @Cantidad INT;

    CREATE TABLE #CargaMasicos
    (
        [Name] NVARCHAR(255) COLLATE DATABASE_DEFAULT NULL,
        NOMBRE_INSTALACION NVARCHAR(255) COLLATE DATABASE_DEFAULT NULL,
        BATERIA NVARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
        FT001 DECIMAL(18,3) NULL,ACUM_BRUTA DECIMAL(18,3) NULL,PROY_BRUTA DECIMAL(18,3) NULL,
        CAUDAL_INSTANTANEO DECIMAL(18,3) NULL,PROY_NETA DECIMAL(18,3) NULL,
        ACUM_NETA DECIMAL(18,3) NULL,LT001 DECIMAL(18,3) NULL,
        PROMEDIO_BRUTA_7_DIAS DECIMAL(18,3) NULL,
        PLC001 NVARCHAR(100) COLLATE DATABASE_DEFAULT NULL
    );

    INSERT #CargaMasicos
    SELECT [Name],NOMBRE_INSTALACION,BATERIA,FT001,ACUM_BRUTA,PROY_BRUTA,
           CAUDAL_INSTANTANEO,PROY_NETA,ACUM_NETA,LT001,PROMEDIO_BRUTA_7_DIAS,PLC001
    FROM dbo.MASICOS_SC;

    SET @Cantidad=@@ROWCOUNT;
    IF @Cantidad=0
        THROW 51001, N'La vista dbo.MASICOS_SC no devolvió registros. Se conservó la carga existente.', 1;

    BEGIN TRY
        BEGIN TRANSACTION;
        DELETE dbo.MASICOS_SC_HISTORICO WHERE FECHA_DATO=@FechaDato;

        INSERT dbo.MASICOS_SC_HISTORICO
        (
            FECHA_DATO,FECHA_INSERCION,[Name],NOMBRE_INSTALACION,BATERIA,FT001,ACUM_BRUTA,
            PROY_BRUTA,CAUDAL_INSTANTANEO,PROY_NETA,ACUM_NETA,LT001,PROMEDIO_BRUTA_7_DIAS,PLC001
        )
        SELECT @FechaDato,@FechaInsercion,[Name],NOMBRE_INSTALACION,BATERIA,FT001,ACUM_BRUTA,
               PROY_BRUTA,CAUDAL_INSTANTANEO,PROY_NETA,ACUM_NETA,LT001,PROMEDIO_BRUTA_7_DIAS,PLC001
        FROM #CargaMasicos;
        COMMIT TRANSACTION;

        EXEC dbo.SP_CLEAR_SINCRONIZAR_MICROS_CONTABLES @FechaDato,@FechaDato;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT>0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH;

    SELECT @FechaDato FECHA_DATO,@FechaInsercion FECHA_INSERCION,@Cantidad REGISTROS_GUARDADOS;
END;
GO

CREATE OR ALTER VIEW dbo.CLEAR_VW_MICROS_CONTABLES
AS
SELECT
    ID,MASICO_HISTORICO_ID,ORIGEN,EDITADO_MANUAL,FECHA_DATO,FECHA_INSERCION_MASICO,
    [Name],NOMBRE_INSTALACION,BATERIA,ZONA,MODALIDAD,FT001,ACUM_BRUTA,PROY_BRUTA,
    CAUDAL_INSTANTANEO,PROY_NETA,ACUM_NETA,LT001,PROMEDIO_BRUTA_7_DIAS,PLC001,
    SUPERVISOR,JEFE_ZONA,OBSERVACION,ACTIVO,FECHA_ALTA,USUARIO_ALTA,
    FECHA_MODIFICACION,USUARIO_MODIFICACION
FROM dbo.CLEAR_MICROS_CONTABLES;
GO

/* La aplicación web se conecta con el usuario de base [fix]. Sin estos
   permisos OBJECT_ID puede devolver NULL aunque los objetos existan. */
IF DATABASE_PRINCIPAL_ID(N'fix') IS NOT NULL
BEGIN
    GRANT SELECT,INSERT,UPDATE ON dbo.CLEAR_MICROS_CONTABLES TO [fix];
    GRANT SELECT ON dbo.CLEAR_VW_MICROS_CONTABLES TO [fix];
    GRANT SELECT ON dbo.CLEAR_VW_MASICOS_DIARIOS TO [fix];
    GRANT SELECT ON dbo.MASICOS_SC_HISTORICO TO [fix];
    GRANT SELECT ON dbo.CLEAR_SUPERVISORES_INSTALACIONES TO [fix];
    GRANT EXECUTE ON dbo.FN_CLEAR_NORMALIZAR_BATERIA TO [fix];
END;
GO

/* Primera sincronización: solo lee la tabla local histórica. */
EXEC dbo.SP_CLEAR_SINCRONIZAR_MICROS_CONTABLES;
GO

/* 6. Mantener/crear el Job diario de las 09:00. */
USE [msdb];
GO

IF EXISTS (SELECT 1 FROM dbo.sysjobs WHERE name=N'CLEAR - Carga diaria MASICOS SC')
BEGIN
    EXEC dbo.sp_update_jobstep
        @job_name=N'CLEAR - Carga diaria MASICOS SC',
        @step_id=1,
        @step_name=N'Cargar histórico y Micros contables',
        @subsystem=N'TSQL',
        @database_name=N'LC_MDB',
        @command=N'EXEC dbo.SP_CARGAR_MASICOS_SC_DIARIO;',
        @retry_attempts=3,
        @retry_interval=5;
END
ELSE
BEGIN
    DECLARE @Hoy INT=CONVERT(int,CONVERT(char(8),GETDATE(),112));
    DECLARE @Owner sysname=SUSER_SNAME();
    EXEC dbo.sp_add_job
        @job_name=N'CLEAR - Carga diaria MASICOS SC',
        @enabled=1,
        @description=N'Fotografía diaria MASICOS SC y sincronización de Micros contables a las 09:00.',
        @owner_login_name=@Owner,
        @notify_level_eventlog=2;
    EXEC dbo.sp_add_jobstep
        @job_name=N'CLEAR - Carga diaria MASICOS SC',
        @step_name=N'Cargar histórico y Micros contables',
        @subsystem=N'TSQL',
        @database_name=N'LC_MDB',
        @command=N'EXEC dbo.SP_CARGAR_MASICOS_SC_DIARIO;',
        @retry_attempts=3,
        @retry_interval=5;
    EXEC dbo.sp_add_jobschedule
        @job_name=N'CLEAR - Carga diaria MASICOS SC',
        @name=N'CLEAR - MASICOS SC todos los días 09:00',
        @enabled=1,@freq_type=4,@freq_interval=1,@freq_subday_type=1,
        @active_start_date=@Hoy,@active_start_time=090000;
    EXEC dbo.sp_add_jobserver @job_name=N'CLEAR - Carga diaria MASICOS SC';
END;
GO

USE [LC_MDB];
GO
SELECT
    (SELECT COUNT_BIG(*) FROM dbo.MASICOS_SC_HISTORICO) AS FILAS_HISTORICAS,
    (SELECT COUNT_BIG(*) FROM dbo.CLEAR_VW_MASICOS_DIARIOS) AS DATOS_MASICOS_DISPONIBLES,
    (SELECT COUNT_BIG(*) FROM dbo.CLEAR_MICROS_CONTABLES WHERE ACTIVO=1) AS MICROS_ACTIVOS,
    (SELECT MAX(FECHA_DATO) FROM dbo.MASICOS_SC_HISTORICO) AS ULTIMA_FECHA_MASICO,
    N'INSTALADO' AS ESTADO;
GO
