USE [LC_MDB];
GO

/*
  CLEAR - Novedades semanales
  Baja logica de auditorias con trazabilidad.
  Fecha: 2026-10-02
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.CLEAR_NS_GESTIONES',N'U') IS NULL
    THROW 51000, N'No existe dbo.CLEAR_NS_GESTIONES. Instale primero el modulo de gestion de Novedades semanales.', 1;
GO

IF COL_LENGTH(N'dbo.CLEAR_NS_GESTIONES',N'ACTIVO') IS NULL
BEGIN
    ALTER TABLE dbo.CLEAR_NS_GESTIONES
      ADD ACTIVO bit NOT NULL
          CONSTRAINT DF_CLEAR_NS_GESTIONES_ACTIVO DEFAULT(1) WITH VALUES;
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id=OBJECT_ID(N'dbo.CLEAR_NS_GESTIONES')
      AND name=N'IX_CLEAR_NS_GESTIONES_TIPO_ACTIVO_FECHA'
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_CLEAR_NS_GESTIONES_TIPO_ACTIVO_FECHA
      ON dbo.CLEAR_NS_GESTIONES(TIPO,ACTIVO,FECHA)
      INCLUDE(ESTADO,FECHA_CIERRE,FECHA_PRIMER_CIERRE,VERSION);
END;
GO

SELECT
    COUNT_BIG(*) AS REGISTROS,
    SUM(CASE WHEN ACTIVO=1 THEN 1 ELSE 0 END) AS ACTIVOS,
    SUM(CASE WHEN ACTIVO=0 THEN 1 ELSE 0 END) AS ELIMINADOS
FROM dbo.CLEAR_NS_GESTIONES;
GO
