USE [LC_MDB];
GO

/*
    Vista unificada para la pantalla "Grilla general de pozos".
    Reúne la telemetría actual de BM, PCP, BES y TECCS.

    Columnas normalizadas:
      POZO, BATERIA, TIPO, COMUNICACION, ESTADO,
      PANTALLA y ULTIMA_ACTUALIZACION.
*/

CREATE OR ALTER VIEW dbo.VW_TELEMETRIA_POZOS_GENERAL
AS

SELECT
    LTRIM(RTRIM(CONVERT(nvarchar(255), [POZO]))) AS POZO,
    LTRIM(RTRIM(CONVERT(nvarchar(255), [BATERIA]))) AS BATERIA,
    CAST(N'BM' AS nvarchar(20)) AS TIPO,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255), [YAT:COM]))), N'') AS COMUNICACION,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255), [ESTADO]))), N'') AS ESTADO,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(1000), [PANTALLA]))), N'') AS PANTALLA,
    TRY_CONVERT(datetime2, [Fecha]) AS ULTIMA_ACTUALIZACION
FROM dbo.BM_RTQP
WHERE [POZO] IS NOT NULL
  AND LTRIM(RTRIM(CONVERT(nvarchar(255), [POZO]))) <> N''

UNION ALL

SELECT
    LTRIM(RTRIM(CONVERT(nvarchar(255), [POZO]))) AS POZO,
    LTRIM(RTRIM(CONVERT(nvarchar(255), [BATERIA]))) AS BATERIA,
    CAST(N'PCP' AS nvarchar(20)) AS TIPO,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255), [YAT:COM]))), N'') AS COMUNICACION,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255), [YT:POZO]))), N'') AS ESTADO,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(1000), [PANTALLA]))), N'') AS PANTALLA,
    CAST(NULL AS datetime2) AS ULTIMA_ACTUALIZACION
FROM dbo.PCP_RTQP
WHERE [POZO] IS NOT NULL
  AND LTRIM(RTRIM(CONVERT(nvarchar(255), [POZO]))) <> N''

UNION ALL

SELECT
    LTRIM(RTRIM(CONVERT(nvarchar(255), [POZO]))) AS POZO,
    LTRIM(RTRIM(CONVERT(nvarchar(255), [BATERIA]))) AS BATERIA,
    CAST(N'BES' AS nvarchar(20)) AS TIPO,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255), [YAT:COM]))), N'') AS COMUNICACION,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255), [ESTADO]))), N'') AS ESTADO,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(1000), [PANTALLA]))), N'') AS PANTALLA,
    TRY_CONVERT(datetime2, [FEHA]) AS ULTIMA_ACTUALIZACION
FROM dbo.BES_RTQP
WHERE [POZO] IS NOT NULL
  AND LTRIM(RTRIM(CONVERT(nvarchar(255), [POZO]))) <> N''

UNION ALL

SELECT
    LTRIM(RTRIM(CONVERT(nvarchar(255), [POZO]))) AS POZO,
    LTRIM(RTRIM(CONVERT(nvarchar(255), [BATERIA]))) AS BATERIA,
    CAST(N'TECCS' AS nvarchar(20)) AS TIPO,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255), [YAT:COM]))), N'') AS COMUNICACION,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(255), [ESTADO]))), N'') AS ESTADO,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(1000), [PANTALLA]))), N'') AS PANTALLA,
    TRY_CONVERT(datetime2, [HOY]) AS ULTIMA_ACTUALIZACION
FROM dbo.TECSS_RTQP
WHERE [POZO] IS NOT NULL
  AND LTRIM(RTRIM(CONVERT(nvarchar(255), [POZO]))) <> N'';
GO

-- Verificación rápida
SELECT TOP (100)
    POZO,
    BATERIA,
    TIPO,
    COMUNICACION,
    ESTADO,
    PANTALLA,
    ULTIMA_ACTUALIZACION
FROM dbo.VW_TELEMETRIA_POZOS_GENERAL
ORDER BY POZO, TIPO;
GO
