/* CLEAR · Reportes operativos guardados por usuario
   Ejecutar una sola vez en la base configurada para la plataforma. */
SET NOCOUNT ON;
SET XACT_ABORT ON;

IF OBJECT_ID(N'dbo.CLEAR_REPORTES_GUARDADOS',N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CLEAR_REPORTES_GUARDADOS(
        ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CLEAR_REPORTES_GUARDADOS PRIMARY KEY,
        USUARIO NVARCHAR(128) NOT NULL,
        NOMBRE NVARCHAR(200) NOT NULL,
        DESTINATARIOS NVARCHAR(MAX) NULL,
        ASUNTO NVARCHAR(250) NULL,
        CUERPO NVARCHAR(MAX) NULL,
        ITEMS_JSON NVARCHAR(MAX) NOT NULL,
        ACTIVO BIT NOT NULL CONSTRAINT DF_CLEAR_REPORTES_GUARDADOS_ACTIVO DEFAULT (1),
        FECHA_CARGA DATETIME2 NOT NULL CONSTRAINT DF_CLEAR_REPORTES_GUARDADOS_FECHA DEFAULT SYSDATETIME(),
        FECHA_MODIFICACION DATETIME2 NULL,
        ULTIMO_ENVIO DATETIME2 NULL
    );
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE object_id=OBJECT_ID(N'dbo.CLEAR_REPORTES_GUARDADOS')
      AND name=N'IX_CLEAR_REPORTES_GUARDADOS_USUARIO'
)
BEGIN
    CREATE INDEX IX_CLEAR_REPORTES_GUARDADOS_USUARIO
        ON dbo.CLEAR_REPORTES_GUARDADOS(USUARIO,ACTIVO,FECHA_MODIFICACION DESC,FECHA_CARGA DESC);
END;

SELECT N'CLEAR_REPORTES_GUARDADOS instalada correctamente.' AS RESULTADO;
