USE [LC_MDB];
GO

/*
  CLEAR - Novedades semanales
  Recalculo posterior a la correccion de conteo instalaciones/pozos.
  Ejecutar DESPUES de SQL/CLEAR_ALARMAS_SEMANAL_CACHE_JOB.sql actualizado.
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.SP_CLEAR_ACTUALIZAR_ALARMAS_SEMANA_CACHE',N'P') IS NULL
    THROW 51000, N'No existe SP_CLEAR_ACTUALIZAR_ALARMAS_SEMANA_CACHE.', 1;
IF OBJECT_ID(N'dbo.SP_CLEAR_ACTUALIZAR_NOVEDADES_SEMANALES',N'P') IS NULL
    THROW 51001, N'No existe SP_CLEAR_ACTUALIZAR_NOVEDADES_SEMANALES.', 1;
GO

/* Recalcula hasta 120 dias de la fuente resumida y luego 16 semanas del modulo. */
EXEC dbo.SP_CLEAR_ACTUALIZAR_ALARMAS_SEMANA_CACHE @DiasRecarga=120;
EXEC dbo.SP_CLEAR_ACTUALIZAR_NOVEDADES_SEMANALES @SemanasRecarga=16;
GO

/* Diagnostico diario: instalaciones vs pozos ya separados. */
SELECT
    FECHA,
    SUM(CASE WHEN TIPO='I' THEN TOTAL ELSE 0 END) AS ALARMAS_INSTALACIONES,
    SUM(CASE WHEN TIPO='P' THEN TOTAL ELSE 0 END) AS ALARMAS_POZOS,
    SUM(TOTAL) AS TOTAL_CACHE
FROM dbo.CLEAR_ALARMAS_SEMANA_CACHE
WHERE FECHA>=DATEADD(day,-30,CONVERT(date,SYSDATETIME()))
GROUP BY FECHA
ORDER BY FECHA DESC;
GO

/* Control: la rama I no debe contener filas clasificadas como POZO. */
SELECT COUNT_BIG(*) AS FILAS_POZO_DENTRO_DE_INSTALACIONES
FROM dbo.CLEAR_ALARMAS_SEMANA_CACHE
WHERE TIPO='I' AND TIPO_INSTALACION=N'POZO';
GO
