/* Tablas de seguridad, permisos, auditoría y preferencias */
IF OBJECT_ID('dbo.CLEAR_USER_ACCESS','U') IS NULL
CREATE TABLE dbo.CLEAR_USER_ACCESS (
 USUARIO NVARCHAR(128) NOT NULL PRIMARY KEY, ACTIVO BIT NOT NULL DEFAULT 1,
 PERFIL NVARCHAR(40) NOT NULL DEFAULT 'operador', COMMENT_VIEW BIT NOT NULL DEFAULT 1,
 COMMENT_CREATE BIT NOT NULL DEFAULT 1, COMMENT_EDIT_OWN BIT NOT NULL DEFAULT 1,
 COMMENT_EDIT_ALL BIT NOT NULL DEFAULT 0, COMMENT_DISABLE BIT NOT NULL DEFAULT 0,
 MENU_JSON NVARCHAR(MAX) NULL, SESSION_TIMEOUT_MIN INT NOT NULL DEFAULT 60,
 UPDATED_AT DATETIME2 NOT NULL DEFAULT SYSDATETIME(), UPDATED_BY NVARCHAR(128) NULL
);
IF OBJECT_ID('dbo.CLEAR_AUDIT_LOG','U') IS NULL
CREATE TABLE dbo.CLEAR_AUDIT_LOG (ID BIGINT IDENTITY(1,1) PRIMARY KEY, FECHA DATETIME2 NOT NULL DEFAULT SYSDATETIME(), USUARIO NVARCHAR(128), ACCION NVARCHAR(80) NOT NULL, MODULO NVARCHAR(80), DETALLE NVARCHAR(MAX), IP NVARCHAR(64));
IF OBJECT_ID('dbo.CLEAR_LOGIN_SECURITY','U') IS NULL
CREATE TABLE dbo.CLEAR_LOGIN_SECURITY (USUARIO NVARCHAR(128) NOT NULL PRIMARY KEY, INTENTOS INT NOT NULL DEFAULT 0, BLOQUEADO_HASTA DATETIME2 NULL, ULTIMO_INTENTO DATETIME2 NULL);
IF OBJECT_ID('dbo.CLEAR_USER_PREFS','U') IS NULL
CREATE TABLE dbo.CLEAR_USER_PREFS (USUARIO NVARCHAR(128) NOT NULL, PREF_KEY NVARCHAR(100) NOT NULL, PREF_VALUE NVARCHAR(MAX), UPDATED_AT DATETIME2 NOT NULL DEFAULT SYSDATETIME(), CONSTRAINT PK_CLEAR_USER_PREFS PRIMARY KEY(USUARIO,PREF_KEY));

IF OBJECT_ID('dbo.CLEAR_USER_PASSWORDS','U') IS NULL
CREATE TABLE dbo.CLEAR_USER_PASSWORDS (USUARIO NVARCHAR(128) NOT NULL PRIMARY KEY, PASSWORD_HASH NVARCHAR(255) NOT NULL, UPDATED_AT DATETIME2 NOT NULL DEFAULT SYSDATETIME());
