USE [LC_MDB];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

/*
  CLEAR - CONFIGURACION GLOBAL DEL ESTADO CFN
  Fecha: 2026-09-08

  Modos disponibles:
    OCULTAR_ESTADO : conserva las filas (incluidas las FALLA) y oculta CFN.
    MOSTRAR        : conserva las filas y muestra CFN como estado.
    EXCLUIR        : excluye completamente las filas cuyo estado es CFN.

  La web solamente registra una solicitud. SQL Agent procesa una única cola,
  en orden y con paralelismo limitado. dbo.FIXALARMS nunca se modifica.
*/

IF OBJECT_ID(N'dbo.FIXALARMS') IS NULL
    THROW 51050,N'No existe dbo.FIXALARMS en LC_MDB.',1;

IF OBJECT_ID(N'dbo.CLEAR_ALARM_FILTERS',N'U') IS NULL
    THROW 51051,N'No existe dbo.CLEAR_ALARM_FILTERS. Instale primero los filtros de CLEAR.',1;
GO

IF OBJECT_ID(N'dbo.CLEAR_ALARM_POLICY',N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CLEAR_ALARM_POLICY
    (
        ID tinyint NOT NULL CONSTRAINT PK_CLEAR_ALARM_POLICY PRIMARY KEY,
        MODO_ACTIVO nvarchar(30) NOT NULL,
        MODO_ANTERIOR nvarchar(30) NULL,
        ESTADO nvarchar(20) NOT NULL,
        RECALCULO_COMPLETO bit NOT NULL CONSTRAINT DF_CLEAR_ALARM_POLICY_FULL DEFAULT(0),
        SOLICITADO_POR nvarchar(128) NULL,
        SOLICITADO_EN datetime2(0) NULL,
        INICIADO_EN datetime2(0) NULL,
        FINALIZADO_EN datetime2(0) NULL,
        DETALLE nvarchar(2000) NULL,
        ULTIMO_ERROR nvarchar(4000) NULL,
        CONSTRAINT CK_CLEAR_ALARM_POLICY_ID CHECK(ID=1),
        CONSTRAINT CK_CLEAR_ALARM_POLICY_MODO CHECK(MODO_ACTIVO IN(N'OCULTAR_ESTADO',N'MOSTRAR',N'EXCLUIR')),
        CONSTRAINT CK_CLEAR_ALARM_POLICY_ESTADO CHECK(ESTADO IN(N'COMPLETADO',N'PENDIENTE',N'EJECUTANDO',N'ERROR'))
    );
END;
GO

IF NOT EXISTS(SELECT 1 FROM dbo.CLEAR_ALARM_POLICY WHERE ID=1)
BEGIN
    INSERT dbo.CLEAR_ALARM_POLICY
        (ID,MODO_ACTIVO,MODO_ANTERIOR,ESTADO,RECALCULO_COMPLETO,SOLICITADO_POR,SOLICITADO_EN,FINALIZADO_EN,DETALLE)
    VALUES
        (1,N'OCULTAR_ESTADO',NULL,N'COMPLETADO',0,N'INSTALACION',SYSDATETIME(),SYSDATETIME(),
         N'Modo inicial seguro: se conservan las filas y se oculta únicamente el texto CFN.');
END;
GO

/* Las tres fuentes centrales conservan exactamente las columnas originales.
   La unión contra la tabla singleton agrega un costo despreciable y hace que
   todas las consultas existentes hereden la política sin filtros repetidos. */
DECLARE @Objetos table(ORDEN int NOT NULL,ORIGEN sysname NOT NULL,DESTINO sysname NOT NULL);
INSERT @Objetos VALUES
    (1,N'FIXALARMS',N'CLEAR_F_FIXALARMS'),
    (2,N'FIXALARMS_24H',N'CLEAR_F_FIXALARMS_24H'),
    (3,N'FIXALARMS_ONLY',N'CLEAR_F_FIXALARMS_ONLY');

DECLARE @Origen sysname,@Destino sysname,@Columnas nvarchar(max),@Sql nvarchar(max);
DECLARE C_OBJETOS CURSOR LOCAL FAST_FORWARD FOR
    SELECT ORIGEN,DESTINO FROM @Objetos ORDER BY ORDEN;

OPEN C_OBJETOS;
FETCH NEXT FROM C_OBJETOS INTO @Origen,@Destino;
WHILE @@FETCH_STATUS=0
BEGIN
    IF OBJECT_ID(N'dbo.'+@Origen) IS NOT NULL
    BEGIN
        IF NOT EXISTS
        (
            SELECT 1 FROM sys.columns
            WHERE object_id=OBJECT_ID(N'dbo.'+@Origen) AND name=N'ALM_ALMSTATUS'
        )
            THROW 51052,N'Una fuente de alarmas no contiene ALM_ALMSTATUS.',1;

        SELECT @Columnas=STUFF
        (
            (
                SELECT N','+CASE WHEN C.name=N'ALM_ALMSTATUS' THEN
                    N'CASE WHEN P.MODO_ACTIVO=N''OCULTAR_ESTADO'' AND UPPER(LTRIM(RTRIM(CONVERT(nvarchar(100),A.'+
                    QUOTENAME(C.name)+N'))))=N''CFN'' THEN NULL ELSE A.'+QUOTENAME(C.name)+N' END AS '+QUOTENAME(C.name)
                    ELSE N'A.'+QUOTENAME(C.name) END
                FROM sys.columns C
                WHERE C.object_id=OBJECT_ID(N'dbo.'+@Origen)
                ORDER BY C.column_id
                FOR XML PATH(''),TYPE
            ).value('.','nvarchar(max)'),1,1,N''
        );

        SET @Sql=N'CREATE OR ALTER VIEW dbo.'+QUOTENAME(@Destino)+N' AS
SELECT '+@Columnas+N'
FROM dbo.'+QUOTENAME(@Origen)+N' AS A
CROSS JOIN dbo.CLEAR_ALARM_POLICY AS P
WHERE P.ID=1
  AND (P.MODO_ACTIVO<>N''EXCLUIR'' OR ISNULL(UPPER(LTRIM(RTRIM(CONVERT(nvarchar(100),A.ALM_ALMSTATUS)))),N'''')<>N''CFN'')
  AND NOT EXISTS
  (
      SELECT 1 FROM dbo.CLEAR_ALARM_FILTERS AS F
      WHERE F.ACTIVO=1 AND
      (
          (F.CAMPO IN(N''TAG'',N''AMBOS'') AND
           ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_TAGNAME))) COLLATE DATABASE_DEFAULT=F.VALOR COLLATE DATABASE_DEFAULT)
            OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) COLLATE DATABASE_DEFAULT LIKE (F.VALOR+N''%'') COLLATE DATABASE_DEFAULT)
            OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.ALM_TAGNAME) COLLATE DATABASE_DEFAULT LIKE (N''%''+F.VALOR+N''%'') COLLATE DATABASE_DEFAULT)))
          OR
          (F.CAMPO IN(N''DESCRIPCION'',N''AMBOS'') AND
           ((F.MODO=N''EXACTO'' AND LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_DESCR))) COLLATE DATABASE_DEFAULT=F.VALOR COLLATE DATABASE_DEFAULT)
            OR (F.MODO=N''COMIENZA'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) COLLATE DATABASE_DEFAULT LIKE (F.VALOR+N''%'') COLLATE DATABASE_DEFAULT)
            OR (F.MODO=N''CONTIENE'' AND CONVERT(nvarchar(1000),A.ALM_DESCR) COLLATE DATABASE_DEFAULT LIKE (N''%''+F.VALOR+N''%'') COLLATE DATABASE_DEFAULT)))
      )
  )';
        EXEC sys.sp_executesql @Sql;
    END;
    FETCH NEXT FROM C_OBJETOS INTO @Origen,@Destino;
END;
CLOSE C_OBJETOS;
DEALLOCATE C_OBJETOS;
GO

IF OBJECT_ID(N'dbo.CLEAR_CACHE_OPERATIVA',N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CLEAR_CACHE_OPERATIVA
    (
        METRICA nvarchar(50) NOT NULL,
        ORDEN int NOT NULL,
        DIMENSION1 nvarchar(500) NULL,
        DIMENSION2 nvarchar(500) NULL,
        VALOR1 decimal(38,4) NULL,
        VALOR2 decimal(38,4) NULL,
        VALOR3 decimal(38,4) NULL,
        TEXTO1 nvarchar(1000) NULL,
        FECHA_CACHE datetime2(0) NOT NULL
    );
    CREATE CLUSTERED INDEX IX_CLEAR_CACHE_OPERATIVA_METRICA
        ON dbo.CLEAR_CACHE_OPERATIVA(METRICA,ORDEN);
END;
GO

/* Cache operativa: el origen ya aplica la política. No vuelve a ocultar CFN. */
CREATE OR ALTER PROCEDURE dbo.SP_CLEAR_ACTUALIZAR_CACHE_OPERATIVA
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET DEADLOCK_PRIORITY LOW;

    DECLARE @Ahora datetime2(0)=SYSDATETIME(),@LockResult int;
    BEGIN TRY
        BEGIN TRANSACTION;
        EXEC @LockResult=sys.sp_getapplock
            @Resource=N'CLEAR_CACHE_OPERATIVA',@LockMode=N'Exclusive',
            @LockOwner=N'Transaction',@LockTimeout=15000;
        IF @LockResult<0
            THROW 51057,N'Ya existe otra actualización de caché operativa en curso.',1;

        CREATE TABLE #N
        (
            METRICA nvarchar(50) NOT NULL,ORDEN int NOT NULL,
            DIMENSION1 nvarchar(500) NULL,DIMENSION2 nvarchar(500) NULL,
            VALOR1 decimal(38,4) NULL,VALOR2 decimal(38,4) NULL,VALOR3 decimal(38,4) NULL,
            TEXTO1 nvarchar(1000) NULL,FECHA_CACHE datetime2(0) NOT NULL
        );

        SELECT
            A.ALM_NATIVETIMEIN,
            LTRIM(RTRIM(CONVERT(nvarchar(500),A.ALM_TAGNAME))) TAG,
            UPPER(LTRIM(RTRIM(CONVERT(nvarchar(100),A.ALM_ALMPRIORITY)))) PRIORIDAD,
            UPPER(LTRIM(RTRIM(CONVERT(nvarchar(255),A.ALM_ALMSTATUS)))) ESTADO,
            UPPER(LTRIM(RTRIM(CONVERT(nvarchar(500),A.ALM_VALUE)))) VALOR
        INTO #BASE7
        FROM dbo.CLEAR_F_FIXALARMS A
        WHERE A.ALM_NATIVETIMEIN>=DATEADD(day,-6,CONVERT(date,@Ahora))
        OPTION(MAXDOP 1);

        CREATE CLUSTERED INDEX IX_BASE7_FECHA ON #BASE7(ALM_NATIVETIMEIN);
        SELECT * INTO #BASE24 FROM #BASE7 WHERE ALM_NATIVETIMEIN>=DATEADD(hour,-24,@Ahora);

        INSERT #N VALUES(N'KPI',1,N'TOTAL24H',NULL,(SELECT COUNT_BIG(*) FROM #BASE24),NULL,NULL,NULL,@Ahora);
        INSERT #N VALUES(N'KPI',2,N'TAGS_UNICOS24H',NULL,(SELECT COUNT_BIG(DISTINCT NULLIF(TAG,N'')) FROM #BASE24),NULL,NULL,NULL,@Ahora);
        INSERT #N VALUES(N'KPI',3,N'CRITICAS',NULL,(SELECT COUNT_BIG(*) FROM #BASE24 WHERE PRIORIDAD IN(N'HIGH',N'HI',N'ALTA',N'CRITICAL',N'CRITICA',N'CRÍTICA')),NULL,NULL,NULL,@Ahora);
        INSERT #N VALUES(N'KPI',4,N'ACTIVAS',NULL,(SELECT COUNT_BIG(*) FROM dbo.CLEAR_F_FIXALARMS_ONLY),NULL,NULL,NULL,@Ahora);
        INSERT #N VALUES(N'KPI',5,N'RECONOCIDAS',NULL,(SELECT COUNT_BIG(*) FROM dbo.CLEAR_F_FIXALARMS_RECONOCIDAS),NULL,NULL,NULL,@Ahora);
        INSERT #N VALUES(N'KPI',6,N'SUPRIMIDAS',NULL,(SELECT COUNT_BIG(*) FROM dbo.CLEAR_F_FIXALARMS_SUPRIMIDAS24H),NULL,NULL,NULL,@Ahora);
        INSERT #N VALUES(N'KPI',7,N'COMENTADAS',NULL,(SELECT COUNT_BIG(*) FROM dbo.FIXALARMS_COMENTARIOS WHERE ACTIVO=1 AND COMENTARIO IS NOT NULL AND LTRIM(RTRIM(COMENTARIO))<>N''),NULL,NULL,NULL,@Ahora);
        INSERT #N VALUES(N'KPI',8,N'ULTIMA_ALARMA',NULL,NULL,NULL,NULL,(SELECT TOP(1) CONVERT(nvarchar(19),ALM_NATIVETIMEIN,120) FROM #BASE7 ORDER BY ALM_NATIVETIMEIN DESC),@Ahora);
        IF OBJECT_ID(N'dbo.POZOS') IS NOT NULL INSERT #N VALUES(N'KPI',9,N'POZOS',NULL,(SELECT COUNT_BIG(*) FROM dbo.POZOS),NULL,NULL,NULL,@Ahora);
        IF OBJECT_ID(N'dbo.ALM_Importadas') IS NOT NULL INSERT #N VALUES(N'KPI',10,N'IMPORTADAS',NULL,(SELECT COUNT_BIG(*) FROM dbo.ALM_Importadas),NULL,NULL,NULL,@Ahora);

        ;WITH T AS(SELECT TAG,COUNT_BIG(*) TOTAL FROM #BASE24 WHERE NULLIF(TAG,N'') IS NOT NULL GROUP BY TAG),
        R AS(SELECT ROW_NUMBER() OVER(ORDER BY TOTAL DESC,TAG) ORDEN,TAG,TOTAL FROM T)
        INSERT #N SELECT N'TOP_ALARMAS',ORDEN,TAG,NULL,TOTAL,NULL,NULL,NULL,@Ahora FROM R WHERE ORDEN<=20;

        INSERT #N
        SELECT N'TENDENCIA',ROW_NUMBER() OVER(ORDER BY CONVERT(date,ALM_NATIVETIMEIN)),CONVERT(nvarchar(10),CONVERT(date,ALM_NATIVETIMEIN),23),NULL,COUNT_BIG(*),NULL,NULL,NULL,@Ahora
        FROM #BASE7 GROUP BY CONVERT(date,ALM_NATIVETIMEIN);

        ;WITH P AS
        (
            SELECT CASE WHEN PRIORIDAD IN(N'HIGH',N'HI',N'ALTA',N'CRITICAL',N'CRITICA',N'CRÍTICA') THEN N'HIGH'
                        WHEN PRIORIDAD IN(N'MED',N'MEDIUM',N'MEDIA') THEN N'MEDIUM'
                        WHEN PRIORIDAD IN(N'LOW',N'LO',N'BAJA') THEN N'LOW' ELSE N'INFO' END CLASE,COUNT_BIG(*) TOTAL
            FROM #BASE24
            GROUP BY CASE WHEN PRIORIDAD IN(N'HIGH',N'HI',N'ALTA',N'CRITICAL',N'CRITICA',N'CRÍTICA') THEN N'HIGH' WHEN PRIORIDAD IN(N'MED',N'MEDIUM',N'MEDIA') THEN N'MEDIUM' WHEN PRIORIDAD IN(N'LOW',N'LO',N'BAJA') THEN N'LOW' ELSE N'INFO' END
        )
        INSERT #N SELECT N'PRIORIDAD',ROW_NUMBER() OVER(ORDER BY CLASE),CLASE,NULL,TOTAL,NULL,NULL,NULL,@Ahora FROM P;

        ;WITH O AS(SELECT OPERADOR,COUNT_BIG(*) TOTAL FROM dbo.CLEAR_F_FIXALARMS_RECONOCIDAS WHERE OPERADOR IS NOT NULL GROUP BY OPERADOR),
        R AS(SELECT ROW_NUMBER() OVER(ORDER BY TOTAL DESC,OPERADOR) ORDEN,OPERADOR,TOTAL FROM O)
        INSERT #N SELECT N'OPERADORES',ORDEN,CONVERT(nvarchar(500),OPERADOR),NULL,TOTAL,NULL,NULL,NULL,@Ahora FROM R WHERE ORDEN<=3;

        INSERT #N
        SELECT N'HORARIA',DATEPART(hour,ALM_NATIVETIMEIN)+1,CONVERT(nvarchar(2),DATEPART(hour,ALM_NATIVETIMEIN)),NULL,
            SUM(CASE WHEN PRIORIDAD IN(N'HIGH',N'HI',N'ALTA',N'CRITICAL',N'CRITICA',N'CRÍTICA') THEN 1 ELSE 0 END),
            SUM(CASE WHEN PRIORIDAD IN(N'MED',N'MEDIUM',N'MEDIA') THEN 1 ELSE 0 END),
            SUM(CASE WHEN PRIORIDAD NOT IN(N'HIGH',N'HI',N'ALTA',N'CRITICAL',N'CRITICA',N'CRÍTICA',N'MED',N'MEDIUM',N'MEDIA') THEN 1 ELSE 0 END),NULL,@Ahora
        FROM #BASE24 GROUP BY DATEPART(hour,ALM_NATIVETIMEIN);

        INSERT #N
        SELECT N'FLUJO',DATEPART(hour,ALM_NATIVETIMEIN)+1,CONVERT(nvarchar(2),DATEPART(hour,ALM_NATIVETIMEIN)),NULL,
            SUM(CASE WHEN VALOR NOT IN(N'NORMAL',N'OK',N'HABILITADO') THEN 1 ELSE 0 END),
            SUM(CASE WHEN VALOR IN(N'NORMAL',N'OK',N'HABILITADO') THEN 1 ELSE 0 END),NULL,NULL,@Ahora
        FROM #BASE24 GROUP BY DATEPART(hour,ALM_NATIVETIMEIN);

        INSERT #N
        SELECT N'HEATMAP',ROW_NUMBER() OVER(ORDER BY CONVERT(date,ALM_NATIVETIMEIN),DATEPART(hour,ALM_NATIVETIMEIN)),
            CONVERT(nvarchar(10),CONVERT(date,ALM_NATIVETIMEIN),23),CONVERT(nvarchar(2),DATEPART(hour,ALM_NATIVETIMEIN)),COUNT_BIG(*),NULL,NULL,NULL,@Ahora
        FROM #BASE7 GROUP BY CONVERT(date,ALM_NATIVETIMEIN),DATEPART(hour,ALM_NATIVETIMEIN);

        ;WITH I AS
        (
            SELECT CASE WHEN CHARINDEX(N'_',TAG)>0 THEN LEFT(TAG,CHARINDEX(N'_',TAG)-1) ELSE TAG END INSTALACION,
                COUNT_BIG(*) TOTAL,SUM(CASE WHEN PRIORIDAD IN(N'HIGH',N'HI',N'ALTA',N'CRITICAL',N'CRITICA',N'CRÍTICA') THEN 1 ELSE 0 END) CRITICAS
            FROM #BASE24 WHERE NULLIF(TAG,N'') IS NOT NULL
            GROUP BY CASE WHEN CHARINDEX(N'_',TAG)>0 THEN LEFT(TAG,CHARINDEX(N'_',TAG)-1) ELSE TAG END
        ),R AS(SELECT ROW_NUMBER() OVER(ORDER BY TOTAL DESC,INSTALACION) ORDEN,* FROM I)
        INSERT #N SELECT N'INSTALACIONES',ORDEN,INSTALACION,NULL,TOTAL,CRITICAS,NULL,NULL,@Ahora FROM R WHERE ORDEN<=8;

        INSERT #N SELECT N'FILTRO_ESTADO',ROW_NUMBER() OVER(ORDER BY E),E,NULL,NULL,NULL,NULL,NULL,@Ahora
        FROM(SELECT DISTINCT ESTADO E FROM #BASE24 WHERE ESTADO IS NOT NULL) X WHERE E<>N'';
        INSERT #N SELECT N'FILTRO_PRIORIDAD',ROW_NUMBER() OVER(ORDER BY P),P,NULL,NULL,NULL,NULL,NULL,@Ahora
        FROM(SELECT DISTINCT PRIORIDAD P FROM #BASE24 WHERE PRIORIDAD IS NOT NULL) X WHERE P<>N'';
        INSERT #N SELECT N'FILTRO_INSTALACION',ROW_NUMBER() OVER(ORDER BY I),I,NULL,NULL,NULL,NULL,NULL,@Ahora
        FROM(SELECT DISTINCT CASE WHEN CHARINDEX(N'_',TAG)>0 THEN LEFT(TAG,CHARINDEX(N'_',TAG)-1) ELSE TAG END I FROM #BASE24 WHERE NULLIF(TAG,N'') IS NOT NULL) X WHERE I<>N'';

        INSERT #N SELECT N'VALORES',ROW_NUMBER() OVER(ORDER BY VALOR),VALOR,NULL,COUNT_BIG(*),NULL,NULL,NULL,@Ahora FROM #BASE24 WHERE VALOR IN(N'ALARMA',N'NORMAL',N'FALLA') GROUP BY VALOR;
        INSERT #N SELECT N'ESTADOS',ROW_NUMBER() OVER(ORDER BY ESTADO),ESTADO,NULL,COUNT_BIG(*),NULL,NULL,NULL,@Ahora FROM #BASE24 WHERE ESTADO IN(N'OK',N'HI',N'LO',N'CFN') GROUP BY ESTADO;
        INSERT #N SELECT N'PRIORIDADES',ROW_NUMBER() OVER(ORDER BY P),P,NULL,COUNT_BIG(*),NULL,NULL,NULL,@Ahora FROM(SELECT CASE WHEN PRIORIDAD IN(N'LOW',N'BAJA') THEN N'LOW' WHEN PRIORIDAD IN(N'CRITICAL',N'CRITICA',N'CRÍTICA') THEN N'CRITICAL' ELSE PRIORIDAD END P FROM #BASE24) X WHERE P IN(N'LOW',N'CRITICAL',N'INFO') GROUP BY P;

        TRUNCATE TABLE dbo.CLEAR_CACHE_OPERATIVA;
        INSERT dbo.CLEAR_CACHE_OPERATIVA SELECT * FROM #N;
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT>0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH;
END;
GO

IF OBJECT_ID(N'dbo.CLEAR_CACHE_TOP20_24H',N'U') IS NOT NULL
   AND COL_LENGTH(N'dbo.CLEAR_CACHE_TOP20_24H',N'ULTIMA_APARICION') IS NULL
BEGIN
    ALTER TABLE dbo.CLEAR_CACHE_TOP20_24H ADD ULTIMA_APARICION datetime2(3) NULL;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_CLEAR_ACTUALIZAR_CACHE_TOP20_24H
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET DEADLOCK_PRIORITY LOW;
    IF OBJECT_ID(N'dbo.CLEAR_CACHE_TOP20_24H',N'U') IS NULL RETURN;

    CREATE TABLE #NUEVOS_DATOS
    (
        ALM_TAGNAME nvarchar(500) NOT NULL,DESCRIPCION nvarchar(1000) NULL,
        TOTAL_ALARMAS bigint NOT NULL,ALM_ALMEXTFLD2 nvarchar(500) NULL,
        ULTIMA_APARICION datetime2(3) NULL
    );
    INSERT #NUEVOS_DATOS(ALM_TAGNAME,DESCRIPCION,TOTAL_ALARMAS,ALM_ALMEXTFLD2,ULTIMA_APARICION)
    SELECT
        LTRIM(RTRIM(CONVERT(nvarchar(500),A.ALM_TAGNAME))),
        NULLIF(MAX(COALESCE(NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_DESCR))),N''),NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(1000),A.ALM_TAGDESC))),N''),N'')),N''),
        COUNT_BIG(*),
        NULLIF(MAX(COALESCE(NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(500),A.ALM_ALMEXTFLD2))),N''),N'')),N''),
        MAX(CONVERT(datetime2(3),A.ALM_NATIVETIMEIN))
    FROM dbo.CLEAR_F_FIXALARMS A
    WHERE A.ALM_NATIVETIMEIN>=DATEADD(hour,-24,SYSDATETIME())
      AND NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(500),A.ALM_TAGNAME))),N'') IS NOT NULL
    GROUP BY LTRIM(RTRIM(CONVERT(nvarchar(500),A.ALM_TAGNAME)))
    OPTION(MAXDOP 1,RECOMPILE);

    BEGIN TRY
        BEGIN TRANSACTION;
        TRUNCATE TABLE dbo.CLEAR_CACHE_TOP20_24H;
        INSERT dbo.CLEAR_CACHE_TOP20_24H
            (ALM_TAGNAME,DESCRIPCION,TOTAL_ALARMAS,ALM_ALMEXTFLD2,ULTIMA_APARICION,FECHA_ACTUALIZACION)
        SELECT ALM_TAGNAME,DESCRIPCION,TOTAL_ALARMAS,ALM_ALMEXTFLD2,ULTIMA_APARICION,SYSDATETIME()
        FROM #NUEVOS_DATOS;
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT>0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH;
END;
GO

/* El lock transaccional se libera siempre, aun si se corta la sesión. */
CREATE OR ALTER PROCEDURE dbo.SP_ACTUALIZAR_TELEMETRIA_POZOS_GENERAL_CACHE
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET DEADLOCK_PRIORITY LOW;
    SET LOCK_TIMEOUT 15000;
    IF OBJECT_ID(N'dbo.TELEMETRIA_POZOS_GENERAL_CACHE',N'U') IS NULL RETURN;
    IF OBJECT_ID(N'dbo.VW_TELEMETRIA_POZOS_GENERAL') IS NULL RETURN;

    DECLARE @Ahora datetime2(0)=SYSDATETIME(),@LockResult int;
    BEGIN TRY
        BEGIN TRANSACTION;
        EXEC @LockResult=sys.sp_getapplock
            @Resource=N'CLEAR_TELEMETRIA_POZOS_GENERAL_CACHE',@LockMode=N'Exclusive',
            @LockOwner=N'Transaction',@LockTimeout=0;
        IF @LockResult<0
            THROW 51053,N'Ya existe otra actualización de telemetría en curso.',1;

        CREATE TABLE #Alarmas24h
        (
            POZO nvarchar(255) COLLATE DATABASE_DEFAULT NOT NULL PRIMARY KEY,
            TOTAL bigint NOT NULL
        );
        INSERT #Alarmas24h(POZO,TOTAL)
        SELECT UPPER(LTRIM(RTRIM(CONVERT(nvarchar(255),A.ALM_ALMEXTFLD2)))),COUNT_BIG(*)
        FROM dbo.CLEAR_F_FIXALARMS A
        WHERE A.ALM_NATIVETIMEIN>=DATEADD(hour,-24,@Ahora)
          AND A.ALM_ALMEXTFLD2 IS NOT NULL AND A.ALM_ALMEXTFLD2<>N''
        GROUP BY UPPER(LTRIM(RTRIM(CONVERT(nvarchar(255),A.ALM_ALMEXTFLD2))))
        OPTION(MAXDOP 1,RECOMPILE);

        CREATE TABLE #CacheNueva
        (
            POZO nvarchar(255) COLLATE DATABASE_DEFAULT NOT NULL,
            BATERIA nvarchar(255) COLLATE DATABASE_DEFAULT NULL,
            TIPO nvarchar(20) COLLATE DATABASE_DEFAULT NOT NULL,
            ALM int NOT NULL,COMUNICACION nvarchar(255) COLLATE DATABASE_DEFAULT NULL,
            ESTADO nvarchar(255) COLLATE DATABASE_DEFAULT NULL,
            PANTALLA nvarchar(1000) COLLATE DATABASE_DEFAULT NULL,
            ULTIMA_ACTUALIZACION datetime2(0) NULL,FECHA_CACHE datetime2(0) NOT NULL
        );
        INSERT #CacheNueva(POZO,BATERIA,TIPO,ALM,COMUNICACION,ESTADO,PANTALLA,ULTIMA_ACTUALIZACION,FECHA_CACHE)
        SELECT V.POZO,V.BATERIA,V.TIPO,CONVERT(int,ISNULL(A.TOTAL,0)),V.COMUNICACION,V.ESTADO,V.PANTALLA,V.ULTIMA_ACTUALIZACION,@Ahora
        FROM dbo.VW_TELEMETRIA_POZOS_GENERAL V
        LEFT JOIN #Alarmas24h A
          ON A.POZO COLLATE DATABASE_DEFAULT=UPPER(LTRIM(RTRIM(CONVERT(nvarchar(255),V.POZO)))) COLLATE DATABASE_DEFAULT
        WHERE V.POZO IS NOT NULL AND V.POZO<>N''
        OPTION(MAXDOP 1);

        TRUNCATE TABLE dbo.TELEMETRIA_POZOS_GENERAL_CACHE;
        INSERT dbo.TELEMETRIA_POZOS_GENERAL_CACHE
            (POZO,BATERIA,TIPO,ALM,COMUNICACION,ESTADO,PANTALLA,ULTIMA_ACTUALIZACION,FECHA_CACHE)
        SELECT POZO,BATERIA,TIPO,ALM,COMUNICACION,ESTADO,PANTALLA,ULTIMA_ACTUALIZACION,FECHA_CACHE
        FROM #CacheNueva;
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT>0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_CLEAR_SOLICITAR_POLITICA_CFN
    @Modo nvarchar(30),
    @Usuario nvarchar(128),
    @ForzarCompleto bit=0
WITH EXECUTE AS OWNER
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET @Modo=UPPER(LTRIM(RTRIM(@Modo)));
    SET @Usuario=NULLIF(LTRIM(RTRIM(@Usuario)),N'');
    IF @Modo NOT IN(N'OCULTAR_ESTADO',N'MOSTRAR',N'EXCLUIR')
        THROW 51054,N'Modo CFN inválido.',1;

    DECLARE @Anterior nvarchar(30),@Estado nvarchar(20),@Completo bit;
    BEGIN TRANSACTION;
    SELECT @Anterior=MODO_ACTIVO,@Estado=ESTADO
    FROM dbo.CLEAR_ALARM_POLICY WITH(UPDLOCK,HOLDLOCK) WHERE ID=1;
    IF @Estado=N'EJECUTANDO'
    BEGIN
        ROLLBACK TRANSACTION;
        THROW 51055,N'Ya existe una actualización de alarmas en ejecución.',1;
    END;

    IF @Anterior=@Modo AND @ForzarCompleto=0 AND @Estado=N'COMPLETADO'
    BEGIN
        UPDATE dbo.CLEAR_ALARM_POLICY
        SET SOLICITADO_POR=COALESCE(@Usuario,N'WEB'),SOLICITADO_EN=SYSDATETIME(),
            DETALLE=N'La configuración ya estaba aplicada; no fue necesario recalcular.',ULTIMO_ERROR=NULL
        WHERE ID=1;
        COMMIT TRANSACTION;
        RETURN;
    END;

    SET @Completo=CASE WHEN @ForzarCompleto=1 OR @Anterior=N'EXCLUIR' OR @Modo=N'EXCLUIR' THEN 1 ELSE 0 END;
    UPDATE dbo.CLEAR_ALARM_POLICY
    SET MODO_ANTERIOR=@Anterior,MODO_ACTIVO=@Modo,ESTADO=N'PENDIENTE',
        RECALCULO_COMPLETO=@Completo,SOLICITADO_POR=COALESCE(@Usuario,N'WEB'),
        SOLICITADO_EN=SYSDATETIME(),INICIADO_EN=NULL,FINALIZADO_EN=NULL,
        DETALLE=CASE WHEN @Completo=1 THEN N'En cola: reconstrucción completa.' ELSE N'En cola: actualización operativa.' END,
        ULTIMO_ERROR=NULL
    WHERE ID=1;
    COMMIT TRANSACTION;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_CLEAR_PROCESAR_POLITICA_CFN
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT OFF;
    SET DEADLOCK_PRIORITY LOW;

    DECLARE @Completo bit,@Errores int=0,@Mensaje nvarchar(4000)=N'',@Tomada bit=0;
    BEGIN TRY
        BEGIN TRANSACTION;
        UPDATE dbo.CLEAR_ALARM_POLICY WITH(UPDLOCK,HOLDLOCK)
        SET ESTADO=N'EJECUTANDO',INICIADO_EN=SYSDATETIME(),FINALIZADO_EN=NULL,
            DETALLE=N'1/5 · Actualizando caché operativa…',ULTIMO_ERROR=NULL
        WHERE ID=1 AND ESTADO=N'PENDIENTE';
        IF @@ROWCOUNT=1
        BEGIN
            SET @Tomada=1;
            SELECT @Completo=RECALCULO_COMPLETO FROM dbo.CLEAR_ALARM_POLICY WHERE ID=1;
        END;
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT>0 ROLLBACK TRANSACTION;
        RETURN;
    END CATCH;
    IF @Tomada=0 RETURN;

    BEGIN TRY
        IF OBJECT_ID(N'dbo.SP_CLEAR_ACTUALIZAR_CACHE_OPERATIVA',N'P') IS NULL
            THROW 51056,N'No existe SP_CLEAR_ACTUALIZAR_CACHE_OPERATIVA.',1;
        EXEC dbo.SP_CLEAR_ACTUALIZAR_CACHE_OPERATIVA;
    END TRY
    BEGIN CATCH
        SET @Errores+=1;SET @Mensaje=CONCAT(@Mensaje,N'Caché operativa: ',ERROR_MESSAGE(),NCHAR(13));
    END CATCH;

    IF @Completo=1
    BEGIN
        UPDATE dbo.CLEAR_ALARM_POLICY SET DETALLE=N'2/5 · Actualizando Top 20 de 24 h…' WHERE ID=1;
        BEGIN TRY
            IF OBJECT_ID(N'dbo.CLEAR_CACHE_TOP20_24H',N'U') IS NOT NULL
               AND OBJECT_ID(N'dbo.SP_CLEAR_ACTUALIZAR_CACHE_TOP20_24H',N'P') IS NOT NULL
                EXEC dbo.SP_CLEAR_ACTUALIZAR_CACHE_TOP20_24H;
        END TRY
        BEGIN CATCH
            SET @Errores+=1;SET @Mensaje=CONCAT(@Mensaje,N'Top 20 24 h: ',ERROR_MESSAGE(),NCHAR(13));
        END CATCH;

        UPDATE dbo.CLEAR_ALARM_POLICY SET DETALLE=N'3/5 · Actualizando telemetría de pozos…' WHERE ID=1;
        BEGIN TRY
            IF OBJECT_ID(N'dbo.TELEMETRIA_POZOS_GENERAL_CACHE',N'U') IS NOT NULL
               AND OBJECT_ID(N'dbo.SP_ACTUALIZAR_TELEMETRIA_POZOS_GENERAL_CACHE',N'P') IS NOT NULL
                EXEC dbo.SP_ACTUALIZAR_TELEMETRIA_POZOS_GENERAL_CACHE;
        END TRY
        BEGIN CATCH
            SET @Errores+=1;SET @Mensaje=CONCAT(@Mensaje,N'Telemetría de pozos: ',ERROR_MESSAGE(),NCHAR(13));
        END CATCH;

        UPDATE dbo.CLEAR_ALARM_POLICY SET DETALLE=N'4/5 · Reconstruyendo resúmenes de 120 días…' WHERE ID=1;
        BEGIN TRY
            IF OBJECT_ID(N'dbo.CLEAR_ALARMAS_SEMANA_CACHE',N'U') IS NOT NULL
               AND OBJECT_ID(N'dbo.SP_CLEAR_ACTUALIZAR_ALARMAS_SEMANA_CACHE',N'P') IS NOT NULL
                EXEC dbo.SP_CLEAR_ACTUALIZAR_ALARMAS_SEMANA_CACHE @DiasRecarga=120;
        END TRY
        BEGIN CATCH
            SET @Errores+=1;SET @Mensaje=CONCAT(@Mensaje,N'Caché semanal: ',ERROR_MESSAGE(),NCHAR(13));
        END CATCH;

        UPDATE dbo.CLEAR_ALARM_POLICY SET DETALLE=N'5/5 · Actualizando novedades semanales…' WHERE ID=1;
        BEGIN TRY
            IF OBJECT_ID(N'dbo.CLEAR_NOVEDADES_SEMANALES_CACHE',N'U') IS NOT NULL
               AND OBJECT_ID(N'dbo.SP_CLEAR_ACTUALIZAR_NOVEDADES_SEMANALES',N'P') IS NOT NULL
                EXEC dbo.SP_CLEAR_ACTUALIZAR_NOVEDADES_SEMANALES @SemanasRecarga=16;
        END TRY
        BEGIN CATCH
            SET @Errores+=1;SET @Mensaje=CONCAT(@Mensaje,N'Novedades semanales: ',ERROR_MESSAGE(),NCHAR(13));
        END CATCH;
    END;

    UPDATE dbo.CLEAR_ALARM_POLICY
    SET ESTADO=CASE WHEN @Errores=0 THEN N'COMPLETADO' ELSE N'ERROR' END,
        FINALIZADO_EN=SYSDATETIME(),
        DETALLE=CASE WHEN @Errores=0 THEN
            CASE WHEN @Completo=1 THEN N'Configuración aplicada y cachés reconstruidas.' ELSE N'Configuración aplicada; caché operativa actualizada.' END
            ELSE N'La política quedó activa, pero una o más cachés requieren reintento.' END,
        ULTIMO_ERROR=NULLIF(@Mensaje,N'')
    WHERE ID=1;
END;
GO

/* Copia el alcance del login web sin fijar su nombre en el instalador. */
DECLARE @Grants nvarchar(max)=N'';
SELECT @Grants=@Grants+
    N'GRANT SELECT ON OBJECT::dbo.CLEAR_ALARM_POLICY TO '+QUOTENAME(USER_NAME(P.grantee_principal_id))+N';'+NCHAR(13)+
    N'GRANT EXECUTE ON OBJECT::dbo.SP_CLEAR_SOLICITAR_POLITICA_CFN TO '+QUOTENAME(USER_NAME(P.grantee_principal_id))+N';'+NCHAR(13)
FROM sys.database_permissions P
WHERE P.class=1 AND P.major_id=OBJECT_ID(N'dbo.FIXALARMS')
  AND P.state IN(N'G',N'W') AND P.permission_name=N'SELECT'
  AND USER_NAME(P.grantee_principal_id) IS NOT NULL;
IF @Grants<>N'' EXEC sys.sp_executesql @Grants;
ELSE RAISERROR(N'ADVERTENCIA: no se detectaron permisos SELECT explícitos sobre FIXALARMS para copiar. Use los dos GRANT indicados en INSTALAR_CONFIGURACION_ALARMAS_CFN.md para el usuario web.',10,1) WITH NOWAIT;
GO

USE [msdb];
GO
DECLARE @JobName sysname=N'CLEAR - Aplicar configuración de alarmas';
DECLARE @ScheduleName sysname=N'CLEAR - Configuración alarmas cada 1 minuto';
DECLARE @JobId uniqueidentifier=(SELECT job_id FROM dbo.sysjobs WHERE name=@JobName);

IF @JobId IS NULL
BEGIN
    EXEC dbo.sp_add_job @job_name=@JobName,@enabled=1,
        @description=N'Procesa cambios globales CFN solicitados por administradores de CLEAR. No modifica FIXALARMS.';
    SET @JobId=(SELECT job_id FROM dbo.sysjobs WHERE name=@JobName);
END
ELSE
    EXEC dbo.sp_update_job @job_id=@JobId,@enabled=1,
        @description=N'Procesa cambios globales CFN solicitados por administradores de CLEAR. No modifica FIXALARMS.';

IF EXISTS(SELECT 1 FROM dbo.sysjobsteps WHERE job_id=@JobId AND step_id=1)
    EXEC dbo.sp_update_jobstep @job_id=@JobId,@step_id=1,
        @step_name=N'Procesar solicitud pendiente',@subsystem=N'TSQL',@database_name=N'LC_MDB',
        @command=N'EXEC dbo.SP_CLEAR_PROCESAR_POLITICA_CFN;',@retry_attempts=2,@retry_interval=1;
ELSE
    EXEC dbo.sp_add_jobstep @job_id=@JobId,@step_name=N'Procesar solicitud pendiente',
        @subsystem=N'TSQL',@database_name=N'LC_MDB',@command=N'EXEC dbo.SP_CLEAR_PROCESAR_POLITICA_CFN;',
        @retry_attempts=2,@retry_interval=1;

IF NOT EXISTS(SELECT 1 FROM dbo.sysschedules WHERE name=@ScheduleName)
    EXEC dbo.sp_add_schedule @schedule_name=@ScheduleName,@enabled=1,@freq_type=4,@freq_interval=1,
        @freq_subday_type=4,@freq_subday_interval=1,@active_start_time=0;

IF NOT EXISTS
(
    SELECT 1 FROM dbo.sysjobschedules JS
    INNER JOIN dbo.sysschedules S ON S.schedule_id=JS.schedule_id
    WHERE JS.job_id=@JobId AND S.name=@ScheduleName
)
    EXEC dbo.sp_attach_schedule @job_id=@JobId,@schedule_name=@ScheduleName;

IF NOT EXISTS(SELECT 1 FROM dbo.sysjobservers WHERE job_id=@JobId)
    EXEC dbo.sp_add_jobserver @job_id=@JobId;
GO

USE [LC_MDB];
GO

/* Control final: la instalación no dispara una reconstrucción innecesaria. */
SELECT
    MODO_ACTIVO,ESTADO,RECALCULO_COMPLETO,SOLICITADO_POR,SOLICITADO_EN,
    INICIADO_EN,FINALIZADO_EN,DETALLE,ULTIMO_ERROR
FROM dbo.CLEAR_ALARM_POLICY WHERE ID=1;

SELECT
    (SELECT COUNT_BIG(*) FROM dbo.CLEAR_F_FIXALARMS
     WHERE ALM_NATIVETIMEIN>=DATEADD(hour,-24,SYSDATETIME())) AS FILAS_VISIBLES_24H,
    (SELECT COUNT_BIG(*) FROM dbo.CLEAR_F_FIXALARMS
     WHERE ALM_NATIVETIMEIN>=DATEADD(hour,-24,SYSDATETIME())
       AND UPPER(LTRIM(RTRIM(CONVERT(nvarchar(100),ALM_ALMSTATUS))))=N'CFN') AS CFN_VISIBLES_24H,
    (SELECT COUNT_BIG(*) FROM dbo.CLEAR_F_FIXALARMS
     WHERE ALM_NATIVETIMEIN>=DATEADD(hour,-24,SYSDATETIME())
       AND UPPER(LTRIM(RTRIM(CONVERT(nvarchar(500),ALM_VALUE))))=N'FALLA') AS FALLAS_VISIBLES_24H;

PRINT N'INSTALACION COMPLETADA. Modo inicial: OCULTAR_ESTADO.';
PRINT N'dbo.FIXALARMS no fue modificada.';
GO
