USE [LC_MDB];
GO
IF OBJECT_ID('dbo.CLEAR_AI_DIAGNOSTICS','U') IS NULL
BEGIN
  CREATE TABLE dbo.CLEAR_AI_DIAGNOSTICS(
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    FECHA_GENERACION DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    PERIODO_DESDE DATETIME2 NOT NULL,
    PERIODO_HASTA DATETIME2 NOT NULL,
    MODELO NVARCHAR(120) NULL,
    ESTADO NVARCHAR(30) NOT NULL,
    RESUMEN NVARCHAR(MAX) NULL,
    DATOS_JSON NVARCHAR(MAX) NULL,
    ERROR NVARCHAR(MAX) NULL,
    USUARIO NVARCHAR(128) NULL
  );
END
GO
