USE [LC_MDB];
GO
SET NOCOUNT ON;

/* Verificación de solo lectura, acotada a 24 horas para proteger el servidor.
   Todos los resultados CFN_VISIBLE deben ser 0. */
SELECT
    (SELECT COUNT_BIG(*) FROM dbo.FIXALARMS
     WHERE ALM_NATIVETIMEIN>=DATEADD(hour,-24,SYSDATETIME())
       AND ISNULL(UPPER(LTRIM(RTRIM(CONVERT(nvarchar(100),ALM_ALMSTATUS)))),N'')=N'CFN') AS CFN_ORIGEN_SCADA_24H,
    (SELECT COUNT_BIG(*) FROM dbo.CLEAR_F_FIXALARMS
     WHERE ALM_NATIVETIMEIN>=DATEADD(hour,-24,SYSDATETIME())
       AND ISNULL(UPPER(LTRIM(RTRIM(CONVERT(nvarchar(100),ALM_ALMSTATUS)))),N'')=N'CFN') AS CFN_VISIBLE_CLEAR_24H;

IF OBJECT_ID(N'dbo.CLEAR_F_FIXALARMS_24H',N'V') IS NOT NULL
    EXEC(N'SELECT COUNT_BIG(*) AS CFN_VISIBLE_CLEAR_24H FROM dbo.CLEAR_F_FIXALARMS_24H WHERE ISNULL(UPPER(LTRIM(RTRIM(CONVERT(nvarchar(100),ALM_ALMSTATUS)))),N'''')=N''CFN'';');

IF OBJECT_ID(N'dbo.CLEAR_F_FIXALARMS_ONLY',N'V') IS NOT NULL
    EXEC(N'SELECT COUNT_BIG(*) AS CFN_VISIBLE_CLEAR_HISTORICOS_24H FROM dbo.CLEAR_F_FIXALARMS_ONLY WHERE ALM_NATIVETIMEIN>=DATEADD(hour,-24,SYSDATETIME()) AND ISNULL(UPPER(LTRIM(RTRIM(CONVERT(nvarchar(100),ALM_ALMSTATUS)))),N'''')=N''CFN'';');

IF OBJECT_ID(N'dbo.CLEAR_CACHE_OPERATIVA',N'U') IS NOT NULL
    SELECT COUNT_BIG(*) AS CFN_VISIBLE_CACHE_OPERATIVA
    FROM dbo.CLEAR_CACHE_OPERATIVA
    WHERE UPPER(LTRIM(RTRIM(ISNULL(DIMENSION1,N''))))=N'CFN';
GO
