/* CLEAR - infraestructura común de reportes. Ejecutar una sola vez. */
IF OBJECT_ID('dbo.CLEAR_REPORT_CONTACTS','U') IS NULL
BEGIN
  CREATE TABLE dbo.CLEAR_REPORT_CONTACTS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBRE NVARCHAR(150) NULL,
    EMAIL NVARCHAR(254) NOT NULL,
    ACTIVO BIT NOT NULL CONSTRAINT DF_CLEAR_REPORT_CONTACTS_ACTIVO DEFAULT 1,
    USUARIO_CARGA NVARCHAR(128) NULL,
    FECHA_CARGA DATETIME2 NOT NULL CONSTRAINT DF_CLEAR_REPORT_CONTACTS_FECHA DEFAULT SYSDATETIME(),
    FECHA_MODIFICACION DATETIME2 NULL,
    CONSTRAINT UQ_CLEAR_REPORT_CONTACTS_EMAIL UNIQUE(EMAIL)
  );
END;

IF OBJECT_ID('dbo.CLEAR_REPORTES_GUARDADOS','U') IS NULL
BEGIN
  CREATE TABLE dbo.CLEAR_REPORTES_GUARDADOS(
    ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    USUARIO NVARCHAR(128) NOT NULL,
    NOMBRE NVARCHAR(200) NOT NULL,
    DESTINATARIOS NVARCHAR(MAX) NULL,
    ASUNTO NVARCHAR(250) NULL,
    CUERPO NVARCHAR(MAX) NULL,
    ITEMS_JSON NVARCHAR(MAX) NOT NULL,
    ACTIVO BIT NOT NULL DEFAULT 1,
    FECHA_CARGA DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FECHA_MODIFICACION DATETIME2 NULL,
    ULTIMO_ENVIO DATETIME2 NULL
  );
END;
