USE [LC_MDB];
GO
IF OBJECT_ID('dbo.CLEAR_REPORT_SCHEDULES','U') IS NULL
BEGIN
 CREATE TABLE dbo.CLEAR_REPORT_SCHEDULES(
  ID INT IDENTITY(1,1) PRIMARY KEY,
  NOMBRE NVARCHAR(150) NOT NULL,
  TIPO_REPORTE NVARCHAR(50) NOT NULL CONSTRAINT DF_CLEAR_REPORT_TIPO DEFAULT 'dashboard',
  DESTINATARIOS NVARCHAR(MAX) NOT NULL,
  CC NVARCHAR(MAX) NULL,
  CCO NVARCHAR(MAX) NULL,
  ASUNTO NVARCHAR(250) NOT NULL,
  CUERPO NVARCHAR(MAX) NULL,
  FRECUENCIA NVARCHAR(30) NOT NULL CONSTRAINT DF_CLEAR_REPORT_FREQ DEFAULT 'daily',
  DIAS_SEMANA NVARCHAR(50) NULL,
  HORARIOS NVARCHAR(200) NOT NULL CONSTRAINT DF_CLEAR_REPORT_HORA DEFAULT '08:00',
  ACTIVO BIT NOT NULL CONSTRAINT DF_CLEAR_REPORT_ACTIVO DEFAULT 1,
  ZONA_HORARIA NVARCHAR(80) NOT NULL CONSTRAINT DF_CLEAR_REPORT_TZ DEFAULT 'America/Argentina/Buenos_Aires',
  PROXIMA_EJECUCION DATETIME2 NULL,
  ULTIMA_EJECUCION DATETIME2 NULL,
  ULTIMO_ESTADO NVARCHAR(30) NULL,
  ULTIMO_ERROR NVARCHAR(MAX) NULL,
  USUARIO_CARGA NVARCHAR(100) NULL,
  FECHA_CARGA DATETIME2 NOT NULL CONSTRAINT DF_CLEAR_REPORT_FC DEFAULT SYSDATETIME(),
  FECHA_MODIFICACION DATETIME2 NULL
 );
END
GO
IF OBJECT_ID('dbo.CLEAR_REPORT_LOG','U') IS NULL
BEGIN
 CREATE TABLE dbo.CLEAR_REPORT_LOG(
  ID BIGINT IDENTITY(1,1) PRIMARY KEY,
  ID_REPORTE INT NULL,
  FECHA_EJECUCION DATETIME2 NOT NULL CONSTRAINT DF_CLEAR_REPORT_LOG_FECHA DEFAULT SYSDATETIME(),
  DESTINATARIOS NVARCHAR(MAX) NULL,
  ESTADO NVARCHAR(30) NOT NULL,
  ARCHIVO NVARCHAR(500) NULL,
  ERROR NVARCHAR(MAX) NULL,
  DURACION_SEGUNDOS INT NULL,
  USUARIO_EJECUCION NVARCHAR(100) NULL
 );
 CREATE INDEX IX_CLEAR_REPORT_LOG_FECHA ON dbo.CLEAR_REPORT_LOG(FECHA_EJECUCION DESC);
END
GO
IF OBJECT_ID('dbo.CLEAR_REPORT_SETTINGS','U') IS NULL
BEGIN
 CREATE TABLE dbo.CLEAR_REPORT_SETTINGS(
  CONFIG_KEY NVARCHAR(100) NOT NULL PRIMARY KEY,
  CONFIG_VALUE NVARCHAR(MAX) NULL,
  UPDATED_AT DATETIME2 NOT NULL CONSTRAINT DF_CLEAR_REPORT_SETTINGS_FECHA DEFAULT SYSDATETIME(),
  UPDATED_BY NVARCHAR(100) NULL
 );
END
GO
IF OBJECT_ID('dbo.CLEAR_REPORT_LOCK','U') IS NULL
BEGIN
 CREATE TABLE dbo.CLEAR_REPORT_LOCK(LOCK_NAME NVARCHAR(100) NOT NULL PRIMARY KEY,LOCKED_AT DATETIME2 NOT NULL,LOCKED_BY NVARCHAR(150) NULL);
END
GO
SELECT 'Tablas de reportes creadas/verificadas correctamente.' AS RESULTADO;
GO
