USE [msdb];
GO
DECLARE @JobName sysname = N'CLEAR - Histórico TECSS diario 06hs';
DECLARE @JobId uniqueidentifier;
DECLARE @StepId int;
SELECT @JobId=job_id FROM dbo.sysjobs WHERE name=@JobName;
IF @JobId IS NOT NULL
BEGIN
    SELECT @StepId=step_id FROM dbo.sysjobsteps WHERE job_id=@JobId AND step_name=N'Guardar histórico TECSS';
    IF @StepId IS NOT NULL
        EXEC dbo.sp_update_jobstep
            @job_id=@JobId,
            @step_id=@StepId,
            @database_name=N'LC_MDB',
            @command=N'SET NOCOUNT ON; SET XACT_ABORT ON; EXEC dbo.SP_TECSS_GUARDAR_HISTORICO;';
END;
GO
USE [LC_MDB];
GO
IF OBJECT_ID(N'dbo.SP_TECSS_ACTUALIZAR_3SIGMA_CACHE',N'P') IS NOT NULL DROP PROCEDURE dbo.SP_TECSS_ACTUALIZAR_3SIGMA_CACHE;
IF OBJECT_ID(N'dbo.CLEAR_CACHE_TECSS_3SIGMA',N'U') IS NOT NULL DROP TABLE dbo.CLEAR_CACHE_TECSS_3SIGMA;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.TECSS_TECSSAIB_HISTORICO') AND name=N'IX_TECSS_HIST_POZO_FECHA') DROP INDEX [IX_TECSS_HIST_POZO_FECHA] ON dbo.TECSS_TECSSAIB_HISTORICO;
IF COL_LENGTH(N'dbo.TECSS_TECSSAIB_HISTORICO',N'POZO_BUSQUEDA') IS NOT NULL ALTER TABLE dbo.TECSS_TECSSAIB_HISTORICO DROP COLUMN [POZO_BUSQUEDA];
GO
